### ISSUE TITLE
Invite Volunteers (Event-based):  When inviting volunteer that exists in database but has no password he is not receiving invite emails. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#1003]
Volunteer existent in DB but with no password should receive emails as if they did not exist in the database 
 for events.. 
 
Email template used should be:   invite-volunteer-event-new

**Comment by nickolashe** [comment]
@maxtattenbach does this overlap with any other open issues on this theme?

**Comment by MaxTattenbach** [comment]
@nickolashe  no I don't believe so we had created unit tests for invite volunteers and they all passed.   Note that we didn't have the cases for users that don't have password.  

Invite volunteer (non-event-based) is working fine with those volunteers with accounts but no password,

**Comment by MaxTattenbach** [comment]
@tevtonez I'll close this one and focus on #1013
