### ISSUE TITLE
org-signup: Incomplete form crashes instead of returning status_msg

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#101]
<img width="1194" alt="screen shot 2017-06-09 at 6 34 32 pm" src="https://user-images.githubusercontent.com/3347095/26997794-4eb64fba-4d42-11e7-8a16-b292868130aa.png">

**Comment by nickolashe** [comment]
@dannypernik Has this been fixed?

**Comment by dannypernik** [comment]
<img width="1059" alt="screen shot 2017-07-10 at 12 08 19 pm" src="https://user-images.githubusercontent.com/3347095/28030292-c5e6ffe2-6568-11e7-8697-ef7d134d2019.png">

@nickolashe not yet, at least not on develop or master.

**Comment by nickolashe** [comment]
@dannypernik @tsiology i think this one is a low hanging fruit

**Comment by tsiology** [comment]
@dannypernik is this still an issue? Wasn't able to recreate it.

**Comment by tsiology** [comment]
@dannypernik @nickolashe Making org name and org website required input fields prevents this issue, but where do we go after a successful signup? Right now it tries going to profile with a status_msg that is not accounted for in urls.py:

![image](https://user-images.githubusercontent.com/28738472/28734803-312b6a02-73a8-11e7-801a-f2875cf934e9.png)

**Comment by dannypernik** [comment]
@tsiology  So do we just need to account for the status msg in urls.py?

**Comment by tsiology** [comment]
Yes, and add it to top of profile template if desired

**Comment by tsiology** [comment]
PR #230
