### ISSUE TITLE
Biz-Admin/: Fast Folks old receipt is shown for all redemeed offers on the Biz Admin profile

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#1010]
@dannypernik  I believe we had deleted the view receipt button for MVP. 

![image](https://user-images.githubusercontent.com/26234440/34995057-004abeae-fa9b-11e7-8495-48cdfc961b2e.png)

![image](https://user-images.githubusercontent.com/26234440/34995201-61cee6f0-fa9b-11e7-9e6d-7234420bacd2.png)

**Comment by nickolashe** [comment]
i believe its hardcoded at this time

**Comment by dannypernik** [comment]
Removed dropdown menu from redemptions since "View receipt" was only item in menu.

**Comment by nickolashe** [comment]
is this in develop already?

**Comment by nickolashe** [comment]
lets try to reference issue # in the commit message for easy access
