### ISSUE TITLE
invite-volunteers:  regression when inviting to future events

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#1013]
@nickolashe @dannypernik   Hi guys I am bit confused because now we are having issues with invite volunteers to events.  We had tested this before and it was working properly.  I am quite sure I would have gotten this issues when I did testing in Dec.   I am pretty sure this is not happening in master. 

But either way, I know you all worked on the use cases this past week.  See issues below and what I believe is proper functionality.  These are pretty high priority issues considering that the functional requirement is not being met.  

Invite Volunteer - Event Future
1. Volunteers in DB with no password - don't receive event email and don't get added to the event.  (Proper functionality should be: receive event email "new" and added to event)
2. Volunteers in DB with password - don't receive event email and don't get added to the event. (Proper functionality should be: receive event email "existing" and added to event)
3.  New Volunteers not in DB -  receive event email "new"  and get added to event (This is proper functionality)

Invite Volunteers - Event Past.
1. Volunteers in DB with no password - don't receive event email and don't get added to the event.  (Proper functionality should be:  added to event to event with no email)
2. Volunteers in DB with password - don't receive event email and don't get added to the event. (Proper functionality should be: added to event don't receive event email)
3. New Volunteers not in DB -  receive event email "new"  and get added to event (Proper functionality should be: added to event don't receive event email)

**Comment by nickolashe** [comment]
@tevtonez any ideas why this is working differently?

**Comment by nickolashe** [comment]
@MaxTattenbach could you erase everything under "Invite Volunteers - Events Past" above

**Comment by nickolashe** [comment]
@tevtonez I think we need to understand why there is a regression in the functionality of /invite-volunteers

**Comment by nickolashe** [comment]
closing in favor of #1025
