### ISSUE TITLE
Live Dash Board:  Not Allowing to add volunteer with oC account if box to invite oC is clicked. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#1014]
I am unable to add volunteer via live dash board if he already has an account and the incorrect message dispalys: "Server Error....."  

Note that the status message below the "Server Errror..." is there from the other volunteers that were added, I created a separate issue because that message should be changed. 

When selecting invite box and adding an active volunteer on oC the proper functionality should be:  Add him to the dashboard, don't send invite email and don't display an Error message. 

![image](https://user-images.githubusercontent.com/26234440/35003521-b42ad32a-fab2-11e7-96d2-b734ecba3b3d.png)

**Comment by nickolashe** [comment]
@tevtonez which unit test corresponds to the use case described here?

**Comment by tevtonez** [comment]
@nickolashe I doubt we have a use case for it. oC MVP doesn't contain it either.

**Comment by nickolashe** [comment]
@MaxTattenbach @dannypernik i believe the issue has been fixed. can you give it another try?
