### ISSUE TITLE
redeem-currents: proof-read the text to make sure the use of biz-name is consistent

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#1020]
`offer.org.name` must be replaced with the `biz_name` entered in the popup

**Comment by dannypernik** [comment]
@nickolashe as long as we use 'openCurrents' as the business name for the offer, I believe we're okay to keep the variable as is. We've notified the user that they are redeeming a special offer, and they are in fact redeeming Currents with openCurrents, not biz_name, in this case.

**Comment by nickolashe** [comment]
ok, feel free to close. its just i think i've seen you are substituting it in some places already.

**Comment by nickolashe** [comment]
in that case we should that all references to biz names are consistent
