### ISSUE TITLE
time-tracker: Error when "Someone else" selected and existing volunteer is added as admin

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#1052]
this occurred on opencurrents.com/time-tracker when entering “Someone else” for admin and typing in an email for admin that was already in the DB but not currently assigned to an org:

![img_2401](https://user-images.githubusercontent.com/3347095/35829560-dba10d26-0a88-11e8-93b3-f2939ed49786.PNG)

**Comment by nickolashe** [comment]
@dannypernik can you retest pls

**Comment by dannypernik** [comment]
@nickolashe issue is fixed on develop server.
