### ISSUE TITLE
login: 403 error when "Log in" clicked twice

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#1053]
<img width="1242" alt="screen shot 2018-02-05 at 3 24 25 pm" src="https://user-images.githubusercontent.com/3347095/35829638-255a12b4-0a89-11e8-9c3b-07ca6ba71c49.png">

**Comment by nickolashe** [comment]
@dannypernik can you retest pls

**Comment by dannypernik** [comment]
@nickolashe working
