### ISSUE TITLE
live-dashboard: add event location to header

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#106]

**Comment by nickolashe** [comment]
@dannypernik What's the status of this one?

**Comment by dannypernik** [comment]
<img width="321" alt="screen shot 2017-07-10 at 4 36 54 pm" src="https://user-images.githubusercontent.com/3347095/28041201-1b6842e4-658e-11e7-9ff9-7051fd578d7e.png">

@nickolashe what do you think? Seems a bit busy.

**Comment by nickolashe** [comment]
what if we make location start on a new libe?

**Comment by nickolashe** [comment]
*line

**Comment by dannypernik** [comment]
@nickolashe Basically it pushes the form further and further down which I'm finding aesthetically and functionally unappealing.

**Comment by dannypernik** [comment]
Maybe if we abbreviated the location at the first comma

**Comment by dannypernik** [comment]
would be super nice to display just the name of the location and link to it in google maps. v6 or something :)

**Comment by nickolashe** [comment]
with Keep Austin beautiful
at Texas Rowing Center
(location in smaller font)

**Comment by nickolashe** [comment]
how about that?

**Comment by dannypernik** [comment]
yeah that would be nice. Google Places autocomplete actually puts a comma after the name of a place so I could change the Texas rowing center name from hyphen to comma and we could truncate at first comma?

**Comment by nickolashe** [comment]
which first comma you mean?

**Comment by nickolashe** [comment]
or what do you mean by first comma

**Comment by dannypernik** [comment]
Google places autocomplete for this location is "Texas Rowing Center, 1541 West Cesar Chavez, Austin, TX 78703" so if we only used the part before the first comma I think we're in business. Wouldn't even be hard to link to a google maps search of the full location.

**Comment by nickolashe** [comment]
what's the status of this one?

**Comment by dannypernik** [comment]
@nickolashe I need some variable name that truncates location at first comma.

**Comment by nickolashe** [comment]
@karbmk @tsiology i think we can create a custom template tag to do this
