### ISSUE TITLE
Opt-in box remains clicked (opted-in) after opting someone in in the live dash board

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#112]

**Comment by nickolashe** [comment]
@MaxTattenbach @dannypernik I don't understand what the issue is here

**Comment by dannypernik** [comment]
@nickolashe the thinking here is that once one person opts in, the checkbox is automatically set for future volunteers. @MaxTattenbach 's thinking is that each volunteer should explicitly opt in, otherwise we could have some accidental opt-ins. I tend to agree.

**Comment by nickolashe** [comment]
can you give a specific example perhaps

**Comment by dannypernik** [comment]
Admin adds a new volunteer who wants an invite to openCurrents, they check the "Invite to openCurrents" checkbox. After clicking "Add volunteer", the checkbox remains checked. If the admin doesn't notice this, the next volunteer they add may be accidentally invited to openCurrents.

**Comment by dannypernik** [comment]
<img width="316" alt="screen shot 2017-07-27 at 1 23 37 pm" src="https://user-images.githubusercontent.com/3347095/28706026-ffa6f0de-7337-11e7-9232-feddb7f1d029.png">

@MaxTattenbach @nickolashe what do you think of this as an alternative UI? Not 100% self explanatory but this would mean the admin doesnt have to click the checkbox every time

**Comment by nickolashe** [comment]
not sure i prefer this to the current one

**Comment by nickolashe** [comment]
is the checkbox being reset now each time?

**Comment by nickolashe** [comment]
i just checked that the checkbox is still persistent
