### ISSUE TITLE
Make email optional on live-dashboard

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#121]

**Comment by nickolashe** [comment]
@karbmk reassigning this one to you

**Comment by nickolashe** [comment]
@dannypernik actually, can you elaborate please? how will we able to create an account in this case?

**Comment by dannypernik** [comment]
@nickolashe this is for the case that we want to track hours for a nonprofit but the volunteer doesn't want Currents. (In fact this could potentially replace the invite checkbox - no email = no invite.) Are we able to track hours without a user? If not, perhaps we could create a 'null' user for each org that would add hours (but not Currents) for each check-in without email?

**Comment by nickolashe** [comment]
ok, does the fact that they don't want currents warrant not asking for their email? if we this dummy user route this will require additional changes. also, may be they'll change their mind going forward.

**Comment by dannypernik** [comment]
@nickolashe and I don't know if the unique constraint would prevent us from registering multiple volunteers without emails and tracking hours accordingly? Perhaps more trouble than it's worth. And I bet the nonprofits always want the emails anyway. We can close this if you agree.

**Comment by nickolashe** [comment]
agreed
