### ISSUE TITLE
Create Project submission error on Opencurrents server

### ISSUE THREAD

**Issue by karbmk** [opencurrents/opencurrents#135]
![screen shot 2017-07-06 at 2 37 19 pm](https://user-images.githubusercontent.com/8406712/27929545-0308a546-6259-11e7-8fa6-02fc800aa6ad.png)

Able to reproduce this error when you try submitting a new Project.

**Comment by nickolashe** [comment]
@karbmk this is off develop, correct?

**Comment by nickolashe** [comment]
i am aware this is not working yet

**Comment by nickolashe** [comment]
https://github.com/opencurrents/opencurrents/pull/182
