### ISSUE TITLE
admin-profile: Org hours appear to be around 4x too large

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#138]
<img width="675" alt="screen shot 2017-07-07 at 3 14 02 pm" src="https://user-images.githubusercontent.com/3347095/27977146-02437e52-632f-11e7-9d34-ecece96c9a1c.png">

**Comment by nickolashe** [comment]
needs testing

**Comment by nickolashe** [comment]
I think this is working now
