### ISSUE TITLE
admin-profile: Event Start/End times are displaying the month instead of minutes

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#145]
<img width="982" alt="screen shot 2017-07-09 at 7 27 06 pm" src="https://user-images.githubusercontent.com/3347095/27998980-a5b66c12-64dc-11e7-99e1-116366796ce8.png">

Incorrect time is showing on the page as well as in the database.

**Comment by nickolashe** [comment]
@dannypernik this is just the /admin gui, i am pretty sure the app is showing the right times (can you doublecheck)?

**Comment by dannypernik** [comment]
oc.com is showing correctly, things are strange on my local...

**Comment by nickolashe** [comment]
can you be more specific pls, in /admin gui or on one of the pages in the app?

**Comment by dannypernik** [comment]
<img width="989" alt="screen shot 2017-07-12 at 5 09 41 pm" src="https://user-images.githubusercontent.com/3347095/28142143-33beff20-6725-11e7-980a-176433bbcd74.png">
<img width="1113" alt="screen shot 2017-07-12 at 5 10 37 pm" src="https://user-images.githubusercontent.com/3347095/28142144-33c01b76-6725-11e7-9f79-a9b07bcd545f.png">

the last event on the admin-profile page

**Comment by nickolashe** [comment]
that's definitely not a month number there, it must be some test event you created locally

**Comment by nickolashe** [comment]
notice that the admin panel is still not showing minutes properly and this is what needs to be fixed
