### ISSUE TITLE
org-signup: Volunteer nominated Keep Austin Beautiful and was designated an admin

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#155]
I can only assume this is how tara.rains7@gmail was added as an OrgUser to KAB. Raises the question - if someone names himself a leader or employee of an org, should he or she automatically be assigned admin status?

**Comment by nickolashe** [comment]
Yes, I am aware this is not working yet. This is within the authorization / permissioning scope which I have not had time to get to yet.

**Comment by nickolashe** [comment]
I think they should not be assigned the status right away, only upon approval.

**Comment by dannypernik** [comment]
@nickolashe agreed

**Comment by nickolashe** [comment]
@dannypernik @MaxTattenbach so are we ok with manual approval of admins by us for now?

**Comment by dannypernik** [comment]
Yes

**Comment by dannypernik** [comment]
PR #244
