### ISSUE TITLE
event-detail: Get form working and sending optional message to volunteer coordinator

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#156]
I will need to create an email template in order to message coordinator, ping me when you get there.

**Comment by tsiology** [comment]
I've proven that the optional message is being saved and is accessible by logging it from views, by i think we need to flesh out how to get it to the email template

**Comment by tsiology** [comment]
I found that the datetime was causing an error in sending the email. Removing that field allows the emails to send successfully again. Will look into this. 

Also still want to have a subject appear in the registration email to the coordinator.

**Comment by nickolashe** [comment]
@tsiology What error specifically were you seeing?

**Comment by tsiology** [comment]
From log/views.py,
ERROR:openCurrents.views:unable to send contact email: datetime.datetime(2017, 7, 15, 12, 0, tzinfo=<UTC>) is not JSON serializable (<type 'exceptions.TypeError'>)

Looking online, I think I can provide a serializer method to get past this.

**Comment by nickolashe** [comment]
Yes, providing a custom serializer would work. Which field are we sending this datetime for?

**Comment by tsiology** [comment]
Sending it as DATE so the email can detail the time/date of the event being registered for.

**Comment by tsiology** [comment]
Added in PR #162
