### ISSUE TITLE
profile: welcome-popup should only display once for a user

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#158]
We could set this as only displaying when user is coming from confirm-account page.

This line auto-opens the popup on load: https://github.com/opencurrents/opencurrents/blob/master/openCurrents/templates/profile.html#L223

**Comment by tsiology** [comment]
completed in PR #162

**Comment by dannypernik** [comment]
welcome-popup does not seem to be opening on user's first login.

**Comment by dannypernik** [comment]
duplicate of #519
