### ISSUE TITLE
As soon as you log into new account the account shows "Here are some ways to get started"

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#164]
I don't think the focus of the first landing is correct.   Mentioning Organization sign-up and Community Meetings is the write approach.  Perhaps just showing the Pop-up is better.

**Comment by dannypernik** [comment]
Ah, we changed this when logging in but apparently not for creating account. @nickolashe I believe I've made the necessary redirect revision as part of PR #160

**Comment by nickolashe** [comment]
what's the status of this one?

**Comment by dannypernik** [comment]
done
