### ISSUE TITLE
Optional contact box - from volunteer to org does not work or lack the submit message button. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#165]
I would eliminate this feature at the moment.

**Comment by dannypernik** [comment]
@tsiology how close are we on this one? The email is sending to the admin when a volunteer registers, correct? But is the volunteer then registered to the event?

**Comment by tsiology** [comment]
@dannypernik If this is the contact box on the event-detail page, then I think we are done as soon as PR #162 is merged. When user hits register, the coordinator will be emailed if it's the first time the user is registering to that event. If an optional contact message is entered, it will be included in the email to the coordinator. If the user registers for the same event additional times, an email will only be sent if a contact message is entered.

As far as the volunteer then being registered, they are entered under "user event registrations" for that event. I may need to investigate more on the event side of things to see if they are truly registered, but I think yes.

**Comment by dannypernik** [comment]
Awesome!

**Comment by nickolashe** [comment]
what's the status of this one?
