### ISSUE TITLE
Pop-up Message - slight ammendment

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#167]
Original Message: 

We're excited to have you with us in the community. We are just getting started with our testing phase. Soon we will connect you with opportunities to volunteer for Currents and exchange them for partial payment with participating businesses.

If you'd like to help us fulfill our mission even sooner, please don't hesitate to reach out!

Proposed Message: 

We're excited to have you with us in the community. We are just getting started with our testing phase. Soon we will connect you with opportunities to volunteer, see what like minded peers are doing in your community, create and earn Currents through social action and exchange your Currents through a digital marketplace.  

If you'd like to learn more on openCurrents and our community please reach out!

**Comment by nickolashe** [comment]
what's the status of this one?

**Comment by dannypernik** [comment]
Updated the welcome message based on our current progress, though not sure if welcome message is displaying ( #158 )
