### ISSUE TITLE
Get in touch in Pop-up not working - button should be linked to tawk.to

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#168]

**Comment by dannypernik** [comment]
I believe this is also fixed In PR #160

**Comment by nickolashe** [comment]
what's the status of this one?

**Comment by dannypernik** [comment]
@karbmk which PR includes the welcome popup?

**Comment by nickolashe** [comment]
the popup does open, can we test that the messages are sent?

**Comment by dannypernik** [comment]
@nickolashe messages are confirmed sent via tawk.to popup
