### ISSUE TITLE
Enable signup as Individual or Org from homepage

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#17]
See screenshots. If signup as Org, user receives validation email, then confirms email and password. User should then be directed to Pilot org application, and Org name should be autopopulated. Note the checkbox on screenshots.

<img width="1009" alt="screen shot 2017-04-19 at 9 23 31 am" src="https://cloud.githubusercontent.com/assets/3347095/25185243/779bd7f2-24e2-11e7-9cbd-ebd3c200abb9.png">
<img width="914" alt="screen shot 2017-04-19 at 9 23 39 am" src="https://cloud.githubusercontent.com/assets/3347095/25185246/7964317e-24e2-11e7-81e5-7a37ac1a9f87.png">

**Comment by nickolashe** [comment]
@dannypernik Until we have a well-defined site map, when you use terms like "Pilot org application", can you also include the corresponding template name please.

**Comment by nickolashe** [comment]
@dannypernik Also, I created 3 different labels to assign task priorities. When you create one, can you suggest a priority on it as well.

**Comment by dannypernik** [comment]
@nickolashe sounds good. Pilot org application's template is org-signup

**Comment by nickolashe** [comment]
@dannypernik Are we done with this one?

**Comment by dannypernik** [comment]
@nickolashe yep!
