### ISSUE TITLE
admin panel: Names not displaying on data fields

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#176]
<img width="495" alt="screen shot 2017-07-20 at 1 33 57 pm" src="https://user-images.githubusercontent.com/3347095/28433178-484147b0-6d50-11e7-91a0-9e6966433990.png">

At some point we lost the names and details of objects in the admin panel. Makes it quite tedious to debug.

**Comment by dannypernik** [comment]
@nickolashe any idea why this is happening all of the sudden? This used to display the org name

**Comment by nickolashe** [comment]
what's the status of this one?

**Comment by dannypernik** [comment]
not sure what changed but working now
