### ISSUE TITLE
invite-volunteers: Add status message to admin-profile whenever event is created and/or volunteers are invited

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#187]
After clicking "Send invites" on invite-volunteers, page should direct to admin-profile with a green status message. Status message scenarios:

Admin creates event with create-event and invites volunteers: "You have created event(s) at X location(s) and invited Y volunteer(s) to the openCurrents community. Nice!"

Admin creates an event and skips invite: "You have created event(s) at X location(s). Nice!"

Admin invites volunteers without creating an event: "You have invited Y volunteer(s) to the openCurrents community. Nice!"

**Comment by tsiology** [comment]
PR #200

**Comment by dannypernik** [comment]
@tsiology thanks please move to "Built" on the pipeline whenever an issue is ready for testing
