### ISSUE TITLE
event-detail: Org name is displaying as "non-profit Keep Austin Beautiful" instead of "Keep Austin Beautiful"

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#189]
<img width="807" alt="screen shot 2017-07-25 at 11 38 33 am" src="https://user-images.githubusercontent.com/3347095/28583180-d956a020-712d-11e7-96df-3896973abe5e.png">

**Comment by karbmk** [comment]
Should be rectified in PR #181
