### ISSUE TITLE
Make homepage revisions based on Max's input

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#19]
Desktop home
-Always Sign me up/Tell me more
-More spacing for Our mission page
-Back button
-Seeks to… Engage?
-Shrink only on desktop?
-Version of homepage without question
-Fix Sign me up on How it Works
-Change pointer to arrow on How it works
-“Volunteer invests time”
-“Organization approves work”
-Move Everyone to top center
-Change “I want to join the team” to “I have a question”
-“Who We Are”

With Nicko
-Enable 2 options for Sign me up - Individual or Organization
-Convey message that we are only signing up a few pilot organizations
-Email whenever org signs up
-Org-signup confirmation?

Mobile
-Change cutoff for small?
-Change background color for 
-Everyone at top on Who Benefits?
-All buttons consistent
-Remove img zoom on mobile landscape

**Comment by nickolashe** [comment]
@dannypernik Is this done?

**Comment by dannypernik** [comment]
@nickolashe done. Marking as such.
