### ISSUE TITLE
Create a UserEventRegistration record for any volunteers invited through invite-volunteers

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#194]

**Comment by nickolashe** [comment]
@karbmk I think this is working, right?

**Comment by karbmk** [comment]
Yes. some modifications of it has been added to PR

**Comment by nickolashe** [comment]
@karbmk that PR has not been merged though. have those changes made into develop?

**Comment by karbmk** [comment]
Nope I think it's not in develop

**Comment by dannypernik** [comment]
@nickolashe do we need to merge this to master before Bike Austin invites their people?

**Comment by nickolashe** [comment]
@karbmk does the current version of invite-volunteer form in develop register users for events?

**Comment by karbmk** [comment]
You mean for user event registration? Yes

**Comment by nickolashe** [comment]
@dannypernik so i think the answer to your question is no, we don't need to
