### ISSUE TITLE
live-dashboard: Are all events for all orgs accessible to any admin?

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#213]
On my local server, I'm able to change the event id in /live-dashboard/#/ and access any event through a single admin.

**Comment by dannypernik** [comment]
@nickolashe I'm thinking an admin should only be able to access their own org's events, including through URL manipulation.

**Comment by nickolashe** [comment]
agreed

**Comment by nickolashe** [comment]
@tsiology I think we should check whether event org matches that of admin explicitly when serving any pages related to the event

**Comment by tsiology** [comment]
I believe PR #244 now has a working fix so only admins of the org can access live-dashboard of events
