### ISSUE TITLE
Box for communicating with Org in event page is associated with register.  It should be independent from it. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#215]
@dannypernik 
![issue 1 communication](https://user-images.githubusercontent.com/26234440/28690541-2f3f506a-72df-11e7-89d9-e4f38637e133.PNG)

**Comment by dannypernik** [comment]
@MaxTattenbach I think we can change the "Register" button to "Contact" if the user is already registered. How does that sound?

**Comment by nickolashe** [comment]
what's the status of this one?

**Comment by dannypernik** [comment]
@nickolashe I think it makes sense for the button to say Register or RSVP before vol is registered, then Send message after vol is registered. what conditional logic would be required to do so?

**Comment by dannypernik** [comment]
Also do we need to change something to prevent a user from registering multiple times on subsequent form submissions?

**Comment by nickolashe** [comment]
@dannypernik assume you have a context variable as usual (feel free to name it is_registered or something else). don't worry about multiple registrations.

**Comment by tsiology** [comment]
PR #294

**Comment by nickolashe** [comment]
i think this has been done already
