### ISSUE TITLE
On Profile I believe manage "Manage org" shouldn't be the main button should be moved.  

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#216]
Also, don't like the label "Manage org" perhaps relabel it or only make the org clickable. 

![issue 2 manage org](https://user-images.githubusercontent.com/26234440/28691039-178807b2-72e1-11e7-856e-ea7bb6a4a752.PNG)

**Comment by dannypernik** [comment]
@MaxTattenbach this button only shows on admins' profile. I actually think it should be a main button for admins.

**Comment by nickolashe** [comment]
what's the status of this one?

**Comment by dannypernik** [comment]
<img width="1110" alt="screen shot 2017-08-09 at 1 24 01 am" src="https://user-images.githubusercontent.com/3347095/29107843-bf238180-7ca1-11e7-98fb-0c09b30d6cd4.png">

@nickolashe @MaxTattenbach how about this? IMO it's really important that the admin has a clear way to get to admin-profile, which will be their most common page. Do you think the icon works?

**Comment by MaxTattenbach** [comment]
Looks a lot better!

Max Tattenbach
Co-creator
www.opencurrents.com

**Comment by dannypernik** [comment]
This is added in design branch

**Comment by nickolashe** [comment]
works for me
