### ISSUE TITLE
Not clear where the copy and past goes to. Why are they inviting them? Is this to one particular event?

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#217]
![issue 4 not showing profile name](https://user-images.githubusercontent.com/26234440/28691512-dabaf162-72e2-11e7-975c-69c57ec12cde.PNG)

**Comment by dannypernik** [comment]
@MaxTattenbach perhaps we need a subtitle Invite volunteers... "to your event" or "to track hours"

**Comment by nickolashe** [comment]
I agree we need to clarify

**Comment by dannypernik** [comment]
@karbmk what should I put here to get event name to display?

https://github.com/opencurrents/opencurrents/commit/487c96e2f25862e4eb331fa15007188b19232834

**Comment by nickolashe** [comment]
@dannypernik is `event.project.name` not working for you?

**Comment by dannypernik** [comment]
@nickolashe nope. Check branch design#217

**Comment by nickolashe** [comment]
@dannypernik https://github.com/opencurrents/opencurrents/commit/71e58c7db2d0f6e2d3f832a52e472dc600466b19 should fix this for you

**Comment by dannypernik** [comment]
Yep thanks
