### ISSUE TITLE
Name of Admin not displayed on subsequent pages. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#218]
I think that the admin page should be displayed on subsequent pages. 

![issue 4 not showing profile name](https://user-images.githubusercontent.com/26234440/28691570-1ac3c46e-72e3-11e7-858b-8ed86fbf1ea2.PNG)

**Comment by dannypernik** [comment]
@MaxTattenbach hmmm perhaps we put the user's name next to the ~waveburger~ in the header? this would be present on all pages. it would also mean name would be displayed twice when user is at their profile

**Comment by nickolashe** [comment]
what's the status of this one?

**Comment by dannypernik** [comment]
<img width="888" alt="screen shot 2017-08-09 at 3 16 13 am" src="https://user-images.githubusercontent.com/3347095/29111778-3acc1d92-7cb1-11e7-925d-4d60861cd8d9.png">
<img width="315" alt="screen shot 2017-08-09 at 3 16 35 am" src="https://user-images.githubusercontent.com/3347095/29111777-3acb6668-7cb1-11e7-8c44-3d5d0960e0e9.png">

@nickolashe @MaxTattenbach Name for medium+ screens, icon for small. In design branch

**Comment by nickolashe** [comment]
@dannypernik what's the purpose of the icon in the small version?

**Comment by dannypernik** [comment]
@nickolashe to bring you back to profile. We can get rid of it if we want to, we have a link to profile in the menu

**Comment by nickolashe** [comment]
got it. i think it is somewhat redundant.

**Comment by dannypernik** [comment]
Removed it on small.

**Comment by nickolashe** [comment]
can we link this to a PR?

**Comment by dannypernik** [comment]
PR #279
