### ISSUE TITLE
Org sign-up error showing.   Can't register my non-profit in Costa Rica, Costas Verdes

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#222]
![issue 6](https://user-images.githubusercontent.com/26234440/28693302-9db26b2c-72e9-11e7-9f65-e1fb661548d7.PNG)

**Comment by MaxTattenbach** [comment]
@nickolashe This seems to be happening when we register and org from inside a profile.

**Comment by tsiology** [comment]
PR #230
