### ISSUE TITLE
invite-volunteer emails: Autofill email in home.html

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#226]
Both invite-volunteer and invite-volunteer-event email templates. Let me know if I need to change the emails.

**Comment by nickolashe** [comment]
what's the status of this one?

**Comment by dannypernik** [comment]
@karbmk I believe this is done, close if correct

**Comment by nickolashe** [comment]
@karbmk ?

**Comment by karbmk** [comment]
Yes this is already implemented.
