### ISSUE TITLE
org-signup success message update

### ISSUE THREAD

**Issue by tsiology** [opencurrents/opencurrents#231]
Completing org-signup sends user to profile with the status_msg "Thank you for nominating {org_name} to openCurrents!"

But there is no nominate/approval process happening; org is created immediately. Update status_msg to say "Thank you for registering {org_name} with openCurrents!" ??

**Comment by dannypernik** [comment]
@tsiology We need to remove automatic org approval.

**Comment by tsiology** [comment]
@dannypernik I spent time going through every iteration of existing/new org/user and could not reproduce that issue. I thought it was happening consistently, but it looks like not. 

@nickolashe @karbmk The issue I had seen was at signup, when doing so as an org, it redirected me straight to confirmation page where you set password with the token included in the url. It should always send them to check-email. Again, I was not able to repeat it, but maybe run through org signup to double check.

**Comment by nickolashe** [comment]
what's the status of this one?

**Comment by tsiology** [comment]
I don't think anything has been started for making Org creations need approval first. Making OrgUser creations take manual approval is in progress.

**Comment by nickolashe** [comment]
@tsiology @dannypernik i think orgs can be created as long as access is not granted by default (which is what Tim is working on). thoughts?

**Comment by dannypernik** [comment]
Agreed. Will make approval easier as well, so we don't have to manually create the org

**Comment by nickolashe** [comment]
did we change the message yet?

**Comment by tsiology** [comment]
Changed "nominating to" to "registering with" in PR #271
