### ISSUE TITLE
confirm-account: New user logged into previous account on same device

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#233]
![image](https://user-images.githubusercontent.com/3347095/28883101-eede29f4-7772-11e7-94b9-874512f74498.png)

This is a screenshot taken from a friend's phone after she created an account and set her password in confirm-account. I must have logged into her device previously, and was never logged out. And somehow that login is being maintained despite her verifying her account.

But it sounds like it didn't save her password... she logged out and tried logging back in with her details, but it didnt accept the password. When she reset her password, it let her create a password that did not meet all of the password requirements. After creating the new (insufficient) password, she got this error:

![image](https://user-images.githubusercontent.com/3347095/28883843-7101ab98-7775-11e7-985c-eec8f380860c.png)

Luckily it was my girlfriend who experienced this, glad she let us know!

**Comment by nickolashe** [comment]
what's the status of this one?

**Comment by dannypernik** [comment]
@karbmk @tsiology are we now checking all password requirements?

**Comment by nickolashe** [comment]
i believe this is work in progress https://github.com/opencurrents/opencurrents/pull/235

**Comment by nickolashe** [comment]
we should expire sessions, i think there is an issue for this as well

**Comment by nickolashe** [comment]
this one is related https://github.com/opencurrents/opencurrents/issues/234
