### ISSUE TITLE
invite-volunteers: Status message for non-event invites

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#239]
"You've invited X volunteer(s) to the openCurrents community. (Y volunteer(s are)(is) already (a) member(s).) Thank you!"

**Comment by nickolashe** [comment]
@dannypernik I think this message is too specific. why don't we just report number of volunteers that we registered for the event?

**Comment by dannypernik** [comment]
@nickolashe agreed. @tsiology is this ready in a PR?

**Comment by tsiology** [comment]
I'm unclear on if there is a desired change. 

PR #200 displays the following possible messages:
You have created events at {{ num_events }} location{{ num_events|pluralize }} and registered {{ num_vols }} volunteer{{ num_vols|pluralize }} to the event. Nice!

You have created events at {{ num_events }} location{{ num_events|pluralize }}. Nice!

You have invited {{ num_vols  }} volunteer{{ num_vols|pluralize }} to the openCurrents community. Nice!

**Comment by dannypernik** [comment]
@tsiology this looks good. The 2nd message that does not include volunteers invited can be used when an event is created without adding anyone, and the 3rd message can be used when volunteers are invited but not to an event.

**Comment by nickolashe** [comment]
@tsiology is this done already?

**Comment by tsiology** [comment]
@nickolashe Yes, PR #200 has those conditions.
