### ISSUE TITLE
Empty view in approve hours

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#243]
When all of the weeks have been traversed, i was brought to an empty screen (still on approve-hours template)

<img width="1421" alt="screen shot 2017-08-04 at 1 18 03 pm" src="https://user-images.githubusercontent.com/6278359/28985464-7cdad806-7917-11e7-9bca-9fd71adfd77f.png">

**Comment by karbmk** [comment]
PR #250
