### ISSUE TITLE
Differentiate between red and green status messages

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#26]
class="alert" makes text red, class="success" makes text green.

**Comment by nickolashe** [comment]
@dannypernik Is this issue still relevant?

**Comment by dannypernik** [comment]
@nickolashe yes. There are a few places where I'd like to add a success message after a user completes an action. Instead of making a new template, we can display it at the top of their profile template. When an admin edits or deletes a project, for example.

**Comment by nickolashe** [comment]
what's the status of this one?

**Comment by dannypernik** [comment]
@nickolashe Tim has been adding status messages directly into the templates, and so I've been able to make green status messages. Here's an example: https://github.com/opencurrents/opencurrents/blob/approve_hours/openCurrents/templates/admin-profile.html#L20

Is this acceptable or should we be handling status messages differently?

**Comment by nickolashe** [comment]
@dannypernik @tsiology we should probably be passing messages in the context and not through the url (this ties back to our convo on how we can make urls more concise)
