### ISSUE TITLE
create-event: display error message when time is wrong format

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#263]
<img width="821" alt="screen shot 2017-08-09 at 3 50 57 am" src="https://user-images.githubusercontent.com/3347095/29113232-21778282-7cb6-11e7-859e-0911ebee0fad.png">

I received this screen when entering letters instead of a start time. Try other irrational inputs too.

**Comment by tsiology** [comment]
PR #265 will validate the time data format.
