### ISSUE TITLE
Consider moving to a private repo

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#27]
@dannypernik What are your thoughts on this?

**Comment by dannypernik** [comment]
@nickolashe  I know you mentioned recently that you thought we should move to private given that we are a for-profit business. Could it not be advantageous to make most of our code open source while keeping certain aspects private?

**Comment by nickolashe** [comment]
@dannypernik It could be. Which parts are you thinking specifically?

**Comment by dannypernik** [comment]
@nickolashe I don't know that there's anything in our MVP that would need to be kept private. What do you think?

**Comment by nickolashe** [comment]
@dannypernik lets close this once you'll have set up the payment on github
