### ISSUE TITLE
admin-profile: weird display of past manual tracking events

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#270]
I am seeing the following on develop branch:

<img width="1115" alt="screen shot 2017-08-09 at 5 26 34 pm" src="https://user-images.githubusercontent.com/6278359/29149287-0d13f970-7d28-11e7-8e10-0794ff551f57.png">

**Comment by tsiology** [comment]
We've ended up with pieces of the events_group_current/upcoming/past change in develop while others are not. PR #259 has the other piece of the update that sends only GR events to the template.

**Comment by tsiology** [comment]
@nickolashe I can make a new branch to fix this specifically.

**Comment by tsiology** [comment]
This is similar to issue #258 which would also be solved with merging from PR #259

**Comment by nickolashe** [comment]
@tsiology yes I think you right that this is a duplicate of #258 .
