### ISSUE TITLE
edit-event: Event time was changed and ended up a different time in the database.

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#278]
I noticed that Linda’s event was set for 4am to 6am. I received 2 emails the day before the event saying that the event details were changed. The first one said 2-4pm, and the next said 9am-11am. Neither of these match the event's listed time. Looks like it came from Linda’s account.

**Comment by nickolashe** [comment]
i think i see the error, these times need to be explicitly assigned org's timezone:
https://github.com/opencurrents/opencurrents/blob/master/openCurrents/views.py#L848-L851

**Comment by karbmk** [comment]
I'm on it

**Comment by dannypernik** [comment]
Duplicate of #403
