### ISSUE TITLE
Verify admin is user in org admin_<orgid> group 

### ISSUE THREAD

**Issue by tsiology** [opencurrents/opencurrents#293]
Done for admin-profile, should also be done on these pages in case of URL sharing or manipulation:

ApproveHours, CreateEvent, EditEvent, InviteVolunteers, LiveDashboard

**Comment by nickolashe** [comment]
@tsiology i think this is working already

**Comment by nickolashe** [comment]
https://github.com/opencurrents/opencurrents/pull/244

**Comment by tsiology** [comment]
Ohh I hadn't noticed the new mixin for these other pages as well. Thanks!
