### ISSUE TITLE
Event-Detail: Multiple registrations for user

### ISSUE THREAD

**Issue by baldwinsmith** [opencurrents/opencurrents#297]
<img width="1488" alt="screen shot 2017-08-15 at 6 23 28 pm" src="https://user-images.githubusercontent.com/31051081/29341006-8be60338-81e7-11e7-8759-435aaf70c0a1.png">

User can register to to the same event multiple times after clicking on the register button

**Comment by nickolashe** [comment]
https://github.com/opencurrents/opencurrents/pull/336
