### ISSUE TITLE
time-tracker: Check that date is no more than 2 weeks in the past nor in the future

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#301]
The datepicker sets only the past week as available, but nothing prevents the user from changing the date manually.

**Comment by dannypernik** [comment]
Currently, if a volunteer manually enters a date more than a week before present, the hours get recorded and added to Currents, but it does not add a record in "Hours approved"

**Comment by dannypernik** [comment]
@nickolashe we had a volunteer strongly suggest that we allow them to record hours up to 2 weeks in the past. Max and I are okay with this.

**Comment by dannypernik** [comment]
Changed timepicker to allow 2 weeks into the past. Input still needs to be validated to ensure this.

**Comment by nickolashe** [comment]
@MaxTattenbach

**Comment by MaxTattenbach** [comment]
@nickolashe just gave it a round of testing, still possible to record hours manually more than 2 weeks in the past and in the future.  A status message should pop-up indicating this.

**Comment by nickolashe** [comment]
@MaxTattenbach turns out i forgot to merge the fix to develop. can you double check regarding dates too far in the past again. pretty sure future dates won't work for you regardless.
