### ISSUE TITLE
Date should displayed mm/dd/Year

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#304]
![create event date](https://user-images.githubusercontent.com/26234440/29341878-d745036a-81ec-11e7-98e0-c3a5b5f90cff.PNG)

**Comment by dannypernik** [comment]
@MaxTattenbach I disagree. Other parts of the world order their months and days differently, this is the only format that is universally understandable. And it actually makes more sense than our format - going from year to month to day is from most general to most specific. Given that there's a dropdown calendar, it doesn't really matter.

**Comment by nickolashe** [comment]
no strong preference here
