### ISSUE TITLE
Redesign "Add location" flow in create-project

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#31]
We can't use existing one because we don't know how many locations have been submitted and the input names depend on that. If we could use a multiple choice input element somehow and add options to that list, I think this would work.

**Comment by nickolashe** [comment]
If the above option does not work, we could also submit the number of locations as a separate input in the form, but that would be soft of ad hoc imho.

**Comment by dannypernik** [comment]
@nickolashe not sure I understand how the multiple choice input would work in this case, let's discuss by skype

**Comment by nickolashe** [comment]
Ah right, I think this should be just a select box actually

**Comment by nickolashe** [comment]
@dannypernik So the "[]" syntax is apparently some PHP legacy. I am still not clear how we can implement this.

**Comment by nickolashe** [comment]
This commit solves it:
https://github.com/opencurrents/opencurrents/commit/015e28386160303f5ab0276b81b68eb8ebb2d803
