### ISSUE TITLE
Admin-profile: mark approve hours button to make it clear that hours are pending approval

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#310]
Note in the image below there is no way for Admin to see that he/she has some hours to be approved.  I suggest at the end of each week (on Friday) the Admin should get an reminder email to approve hours. 
![no -pop-up once you have hours submitted](https://user-images.githubusercontent.com/26234440/29363863-2da59516-8257-11e7-8e9e-605c5e853538.PNG)

**Comment by dannypernik** [comment]
@MaxTattenbach when hours are pending approval, a popup that should display the first time an admin logs in each week informing them of hours pending. Coupled with the conditional styling of the button based on hours present, I think we are doing enough to inform them.
