### ISSUE TITLE
Time-Tracker: We are lacking a pop-up that tells volunteer that hours can't be submitted on backwards fashion. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#311]
Its not clear to volunteer that hours are not being submitted.  
![time tracking backward timing](https://user-images.githubusercontent.com/26234440/29364037-d78a1cfa-8257-11e7-9fbf-4ac936950227.PNG)

**Comment by nickolashe** [comment]
the argument is whether this should be presented with a popup or upon form submission. is the former then we need to use javascript for validation. not clear its worth the complexity increase.

**Comment by dannypernik** [comment]
@nickolashe @MaxTattenbach Display as status message if user puts times in reverse. Only makes sense to display after form is submitted.
