### ISSUE TITLE
Time-tracker:  Volunteer is able to submit future hours on same day or future day

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#313]
Note on the Admin side he is not able to see the hours, when manually tracked prior current time.   Unclear to what is happening on the backed.   

I think best would be to restrict this so no hours can be submitted in forward. It should display a pop-up on the Time-Tracker

**Comment by dannypernik** [comment]
Duplicate of #301

**Comment by nickolashe** [comment]
as well as #448
