### ISSUE TITLE
Approve-hours: The time of work and the detail should be displayed as well not only the day. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#315]
Not Clear why I am approving hours for. 
![lacking detail and time](https://user-images.githubusercontent.com/26234440/29366657-35e8e666-8260-11e7-8d21-4719f048f51f.PNG)

**Comment by nickolashe** [comment]
concatenate descriptions into a single (comma-separated) string and show next to the date
