### ISSUE TITLE
Approve-hours:  How does the logic/restriction work for the week

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#316]
Note I have submitted hours for the 8/15/2017 and they are not showing up on admins profile.  Is this do to the weeks restriction. 

Should we have two weeks showing up the past and the Current on.  I am concerned about the delay between the volunteer submitting and the approval.  In today day and age they all want immediate gratification. 

![discongruency with time on week](https://user-images.githubusercontent.com/26234440/29367064-57e8190c-8261-11e7-94b8-698af5d09703.PNG)

**Comment by nickolashe** [comment]
lets make sure we are showing hours from current week as well

**Comment by dannypernik** [comment]
@nickolashe @MaxTattenbach not sure if I'm following but this is set up to display hours one week at a time. If volunteers want quick gratification, they can check in with admins. I'm not interested in making admins approve hours any more frequently. Compare it to earning a paycheck - most payment is biweekly if not monthly.

**Comment by MaxTattenbach** [comment]
@dannypernik note there will be issues w/ volunteers submitting hours and Managers not being able to see them. For example - Hi did can you aprove my hour?  or did you receive my hour?  No I don't see it in my account. ;-)

**Comment by nickolashe** [comment]
@dannypernik why can't we show hours for the current week? i think this would be a matter of a small change on the backend.

**Comment by dannypernik** [comment]
@nickolashe @MaxTattenbach turns out we're already displaying issues for current week. Max would like us to give some indication to admins that additional hours may be present for later weeks. (It's possible volunteers will ask for approval but the admin won't immediately see the hours if previous weeks have not been approved.) I don't love the idea of a message that says "Confirm hours to see later weeks", I think it will be very easy to miss. Would there be an easy way to add a "Next" button to display the next week without approving or declining the first week's hours?

**Comment by nickolashe** [comment]
that's how i was initially imagining the UI here with my idea of pagination if you recall.

**Comment by nickolashe** [comment]
i think we need to spend more time reviewing designs together.

**Comment by nickolashe** [comment]
i am not sure how hard it would be change at this point, @karbmk @tsiology thoughts?

**Comment by dannypernik** [comment]
@MaxTattenbach @nickolashe after speaking with @tsiology and @karbmk it sounds like being able to move between weeks is a big change that will take time. We will look to implement it in a later phase. In the meantime, I will add a message above the Confirm button that displays "Confirm hours to view submissions for additional weeks."

**Comment by MaxTattenbach** [comment]
That should work.

Max

Max Tattenbach
Co-creator
www.opencurrents.com

**Comment by dannypernik** [comment]
PR #259

**Comment by nickolashe** [comment]
works for me
