### ISSUE TITLE
Profile:   Pending Currents, or Hours Submitted and Currents Created should be displayed on the profile. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#318]
![hours submitted lacking](https://user-images.githubusercontent.com/26234440/29367911-ec489890-8263-11e7-93c8-b0f26e7c4028.PNG)

**Comment by nickolashe** [comment]
@dannypernik i don't we are showing any data on hours submitted but not reviewed yet, are we?
