### ISSUE TITLE
create-event & edit-event: Invite unregistered coordinator to openCurrents

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#320]
If admin who is creating an event selects someone else to be the coordinator, we need to check to see if this person has an account. If not, we need to send an invite email and inform the admin that he/she will remain the coordinator until the other admin creates an account.

**Comment by nickolashe** [comment]
@dannypernik is this actually related to event-detail? isn't related to create-event and edit-event?

**Comment by dannypernik** [comment]
@nickolashe yes you're right. Changing the title

**Comment by dannypernik** [comment]
@nickolashe at this point, would it be better / easier to make a dropdown of current admins than a textbox where user may enter a new admin to org? Note that if we keep the current text fields, I was thinking that when a new admin is entered, we need a message to user saying "You are the coordinator of this event until the new admin has created an account."

**Comment by nickolashe** [comment]
sounds good to me

**Comment by dannypernik** [comment]
Closing this and addressing in #374
