### ISSUE TITLE
Event-detail:   Text box says confirm registration - shouldn't it be the button that say Confirm Registration.  Seems confusin

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#324]
![event detail confirm registration](https://user-images.githubusercontent.com/26234440/29412467-90610d6c-831e-11e7-8cee-94f4cf999ddb.PNG)

**Comment by nickolashe** [comment]
@MaxTattenbach can you clarify please? is this for sending the message to the coordinator?

**Comment by nickolashe** [comment]
https://github.com/opencurrents/opencurrents/pull/336
