### ISSUE TITLE
Time-tracker:   Pop-up of time overlap being displayed on the refreshed page rather than the original page. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#326]
Note that the pop-up is being displayed on the wrong page.  When the hours overlap the pop-up should come out as you click  "save" not refreshing the page. 

![pop-up of repeated time showing not displayed on the correct page](https://user-images.githubusercontent.com/26234440/29412933-50fcbab6-8320-11e7-8153-057bb88261db.PNG)

**Comment by nickolashe** [comment]
@MaxTattenbach how important is it to have it on the same page, in your opinion?

**Comment by nickolashe** [comment]
i think having the status message there should allow them to pick the right hours on the second attempt
