### ISSUE TITLE
Time-tracker:   Detecting overlap of time when there is none in some cases. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#327]
For example as it is right now the software won't allow to record from 12 - 12.15 (entry one)  and from 12.15 - 12.30 (entry two).     I am assuming the problem is being caused by the 12.15 matching.     Perhaps in logic we could use a > than rather than equal.

**Comment by nickolashe** [comment]
yes, that sounds right to me. @karbmk can we double check we are using strict inequality?

**Comment by nickolashe** [comment]
@karbmk should be an easy one
