### ISSUE TITLE
Time-tracker & Approve Hours: Unable to track hours after an error overlap in time is detected.     

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#328]
For example:  Once a volunteers submits and overlapping time the system won't successfully send record time for approval.  In some cases it displays on the front-end to the volunteer that time was successfully recorded but it time does not appear on the admins profile.

**Comment by MaxTattenbach** [comment]
Max and Karthik to try and reproduce.

**Comment by dannypernik** [comment]
@MaxTattenbach I believe this is now working properly, reopen if not
