### ISSUE TITLE
Fix radio buttons on event-detail 

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#33]
Currently, I am able to select multiple locations simultaneously, and not able to deselect.

**Comment by dannypernik** [comment]
I've added name="location-[]" to each radio button, I believe this will correct the issue though I'm not sure how to view the event-detail template due to a required parameter

**Comment by nickolashe** [comment]
I am confused now, is this form even supposed to let the user pick multiple locations?

**Comment by dannypernik** [comment]
I'm assuming view-project became event-detail and that a user is coming here after selecting a project from upcoming-projects. If this is the case, then no, a user should only be allowed to pick one location. I believe adding name="location-[]" to a set of radio buttons puts them into the same set and allows only one to be selected at a time.

**Comment by nickolashe** [comment]
I think this will work

**Comment by dannypernik** [comment]
@nickolashe I'm not able to test this page because I assume I need a project ID to load event-detail
