### ISSUE TITLE
Admin-Profile:  No Create Event button when approval of hours are pending. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#331]
![no create event on admin page](https://user-images.githubusercontent.com/26234440/29434008-013bde66-8367-11e7-84ae-4273171032f4.PNG)

**Comment by nickolashe** [comment]
create event unavailable when pending hours to approve and there is at least one upcoming event

**Comment by nickolashe** [comment]
@dannypernik I think Max and I agreed we always need both buttons, and the approve hours button will be decorated differently if there are hours pending approval.

**Comment by dannypernik** [comment]
@nickolashe ok I've pushed changes that make approve-hours primary button (blue) if hours to be approved, and create-event button primary if no hours to approve. #353
