### ISSUE TITLE
Validate that end_time > start_time on create-project and edit-project

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#34]

**Comment by nickolashe** [comment]
check time_end within the same day

**Comment by nickolashe** [comment]
@dannypernik When creating an issue, can you please also set the "Project" and "Milestone" tags

**Comment by dannypernik** [comment]
@nickolashe noted. will do.

**Comment by nickolashe** [comment]
Validate the form in Django forms (upon submitting) or in Javascript (before submitting)

**Comment by edsfocci** [comment]
More work needs to be done still.

**Comment by nickolashe** [comment]
@edsfocci what else need to be done here you think?
