### ISSUE TITLE
approve-hours: redesign UI

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#352]
Add approve hours button next to defer and decline
Rename "Confirm hours" => Confirm

@dannypernik I think these are pretty important changes to make the UI more user-friendly

**Comment by dannypernik** [comment]
@nickolashe If we add "Approve" buttons to every volunteer, I worry that admins will think they have to click every "Approve" button. What if we have a message just above the Confirm button that says "Hours will be approved unless you defer or decline them."

**Comment by nickolashe** [comment]
That sounds good, as long as we rename "Confirm hours" to just "Confirm"

**Comment by dannypernik** [comment]
PR #259
