### ISSUE TITLE
time-tracker and approve-hours: Volunteer selects admin

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#358]
I've simplified the time-tracker page and included a dropdown for admin. Here's what we need to change:

- Select org box should populate with orgs who have at least 1 admin approved by us.
- Move the admin select box to forms.py. Populate with all admins of an org, and add a final option named "Someone else" with value="other-admin". The volunteer selects this last option if their admin isn't listed.
- Approve-hours should only show volunteers who selected the logged in admin, plus any volunteers who selected "Someone else" for the admin's org. Admins will still use "Defer hours" button for unassigned volunteers.
- Add a last option to "Select organization" dropdown with value="other-org" and displaying "Another organization". When this option is selected, the nominate-popup should appear. See the js code on line 188 of time-tracker.html.
- When a volunteer returns to this page, use his/her previously selected org and admin as default values.
- List of admins should only be populated once an org is selected. Until then, admin dropdown should be disabled.
- Connect nomination form that displays when user selects "Another org" from org dropdown
- Redirect to /profile on nomination form submission and display status message: "Thank you for nominating {org_name}! We will reach out soon."

**Comment by nickolashe** [comment]
I think we need to clarify bullet point 2 above in that we list all volunteers who selected "Someone else" **for the admin's org**

**Comment by nickolashe** [comment]
@dannypernik can we break this up into more fine-grained issues pls?

**Comment by dannypernik** [comment]
@nickolashe I'll break this up today or tomorrow when I have a chance. @MaxTattenbach note that the admin dropdown could delay our manual tracking rollout due to the number of changes required.

**Comment by MaxTattenbach** [comment]
@dannypernik @nickolashe  We can huddle around this issue.  We could get a few organizations testing before this change particularly those who only have one admin.  I'd rather not roll this out with those orgs that have more than one admin, it could get confusing.

**Comment by dannypernik** [comment]
@nickolashe just split this into issues #371 #372 and #373
