### ISSUE TITLE
Process email confirmation: error while setting up password for a signup account in design branch

### ISSUE THREAD

**Issue by karbmk** [opencurrents/opencurrents#360]

**Comment by nickolashe** [comment]
@karbmk design branch has been merged to develop. can you make sure you are able to reproduce the issue in develop?

**Comment by karbmk** [comment]
Sure

**Comment by nickolashe** [comment]
@karbmk can you provide more details on what you are seeing here pls

**Comment by karbmk** [comment]
![screen shot 2017-08-22 at 6 07 17 pm](https://user-images.githubusercontent.com/8406712/29633070-a78fb4c0-880a-11e7-85b5-bc07e14fa0cd.png)

**Comment by nickolashe** [comment]
@karbmk lets try to understand what caused the error. can you confirm if it's the multiple users with the same email or something else?

**Comment by dannypernik** [comment]
@karbmk Is this now closed?
