### ISSUE TITLE
Enforce uniqueness constraint on user email

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#361]

**Comment by dannypernik** [comment]
@nickolashe just to make sure I'm estimating consistently, are you indicating that this issue will take 3 hours?

**Comment by nickolashe** [comment]
we need to:
1. go through the entire code base and check if we are making any assumptions regarding uniqueness
2. clean up existing data in db to meet the constraint
3. add the constraint at the model level

could be quicker, this is just an estimate

**Comment by dannypernik** [comment]
@nickolashe should this be in one of our other milestones?

**Comment by nickolashe** [comment]
enforce lowercase

**Comment by nickolashe** [comment]
@dannypernik @MaxTattenbach i've made minor adjustments to the email field in some forms to enforce lowercase emails. can you please double check all forms referenced in https://github.com/opencurrents/opencurrents/pull/884/commits/63ecff5cec9eba5e72c536ad2ed5356ae2176c01 are still showing up correctly.

**Comment by dannypernik** [comment]
Max found an issue with popup biz form: #889

**Comment by MaxTattenbach** [comment]
@nickolashe seem that all the sign-up forms to create a new account are not allowing to create new user when entering existent email with capitals letters which is good. 

Although.  

Invite volunteers and live dashboard are still accepting uppercase.  

When using live dashboard and adding a existent email with a capital letter a new is being created in DB. 

Also, when inviting volunteers on invite volunteer forms inside a org profile - its recrating emails when using capital letters.

**Comment by nickolashe** [comment]
time-tracker

**Comment by MaxTattenbach** [comment]
Time-tracker as well @nickolashe

**Comment by MaxTattenbach** [comment]
@nickolashe @tevtonez @dannypernik  Tested all the forms on the platform and they all are working as desired with the CAPS lock issues we use to have.   I'll close the issue.

@nickolashe What I am not clear is that this issue was not in to be tested but is now working.  Lets make sure changes related to this get pushed to master in the next merge.
