### ISSUE TITLE
Record all admin actions on user time logs

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#363]

**Comment by nickolashe** [comment]
@karbmk the model changes needed to implement this are ready:
https://github.com/opencurrents/opencurrents/pull/362

**Comment by nickolashe** [comment]
@karbmk notice this has lower priority than current MT v0.1 issues

**Comment by dannypernik** [comment]
@nickolashe how much time is left for this one?

**Comment by nickolashe** [comment]
this has been completed
