### ISSUE TITLE
event-detail: Updated email templates

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#365]
If coordinator messages registrants, send coordinator-messaged template:

(NOTE: the See event details button includes variable `*|EVENT_ID|*` in the URL: `www.opencurrents.com/event-detail/*|EVENT_ID|*` )
<img width="690" alt="screen shot 2017-08-24 at 3 13 50 pm" src="https://user-images.githubusercontent.com/3347095/29686550-f9093fc2-88de-11e7-9439-433df587b9dc.png">

If volunteer registers and sends message, send volunteer-messaged template with `*|REGISTER|* = True`. If volunteer is already registered and sends a message, send volunteer-messaged with `*|REGISTER|* = False`. (NOTE: I have also added `*|ADMIN_FIRSTNAME|*` as a variable in this template. I can't send this over to Mandrill yet since it would affect emails in production, so I am creating a duplicate email called volunteer-messaged-test that we can use in development.)

<img width="674" alt="screen shot 2017-08-24 at 2 33 05 pm" src="https://user-images.githubusercontent.com/3347095/29685685-c703263a-88db-11e7-8025-ad8714da43e5.png">

**Comment by tsiology** [comment]
@dannypernik Looks like the volunteer-messaged-test email template is being called and handling REGISTER logic as expected. One comment, those emails are sending with no subject.

**Comment by tsiology** [comment]
PR #294

**Comment by tsiology** [comment]
coordinator-messaged is being called as expected as well, except for the comment I made in slack about using "name" instead of USER_FIRSTNAME, I think it is good.

**Comment by dannypernik** [comment]
@tsiology if all is good here other than sending new volunteer-messaged template to Mandrill, feel free to close this

**Comment by tsiology** [comment]
Pending the merge of PR #294 which has some changes requested, but yeah I think the email templates are working well.
