### ISSUE TITLE
approve-hours: admin-specific volunteers

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#372]
- Approve-hours should only show volunteers who selected the logged in admin
- Popup displays when user selects "Not sure" for admin asking them to contact organization
- Inputs for admin-name and admin-email slide down when "Someone else" is selected by volunteer.
- Email template "volunteer-invites-admin" sent to new admin inviting them to openCurrents
- Email template "new-admin-invited" sent to bizdev@opencurrents.com letting them know an admin has been invited (we'll manually approve admins)
- Logged in admin should not be displayed in admin dropdown (admin cannot submit hours to himself)

**Comment by nickolashe** [comment]
all volunteers who selected "Someone else" will be shown on a single page. the weekly hours view only shows admin-assigned volunteers.

**Comment by dannypernik** [comment]
<img width="862" alt="screen shot 2017-08-30 at 12 19 00 am" src="https://user-images.githubusercontent.com/3347095/29857935-c9c878a4-8d20-11e7-849a-302fdfc3d953.png">

Send to invited admin when "Someone else" selected

**Comment by dannypernik** [comment]
<img width="862" alt="screen shot 2017-08-30 at 12 19 00 am" src="https://user-images.githubusercontent.com/3347095/29858073-665b1dd4-8d21-11e7-920d-2483cbbcaaf6.png">

Admin 'danny@opencurrents.com' is not showing up here. I'm logged in as drpernik@gmail.com so that admin should not display in this list. Not sure if this is related to the fact that I'm manually overriding the 'disabled' setting on admin select by removing it in Chrome developer tools. (Admin select is not currently being enabled when org is selected.)

**Comment by dannypernik** [comment]
@nickolashe @karbmk the last step before closing this issue is making sure that an email is sent to new admin. Everything else is working
