### ISSUE TITLE
create-event: set coordinator with dropdown of admins 

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#374]

**Comment by dannypernik** [comment]
@nickolashe I believe that the logged-in admin name and email autofills on pageload. Are you seeing something different? Or do you mean use an autocomplete dropdown when admin changes coordinator? Do we want to invite a new admin from this page if a new email is entered? If not, this could just be a select box with existing admins.

**Comment by nickolashe** [comment]
@dannypernik its the latter (when changing coordinator). yes, i think we want the invite.

**Comment by dannypernik** [comment]
This would be fixed if we go with a dropdown list of admins as discussed in #320

**Comment by nickolashe** [comment]
agreed

**Comment by dannypernik** [comment]
@karbmk I've added select boxes in HTML on create-event and edit-event in branch `issue#374`. These need to be moved to forms, and we need to add in error handling that I commented out just above the select boxes. Here are the changes, note we are removing the coordinator name and email text boxes, which means we can get rid of inviting new admin through this page: https://github.com/opencurrents/opencurrents/commit/b13e7da120236b7e8cbe3de51b82604020f04770

**Comment by nickolashe** [comment]
@karbmk does #471 include this one?

**Comment by dannypernik** [comment]
Curious on the status of this one

**Comment by nickolashe** [comment]
i don't think anyone worked on this yet

**Comment by dannypernik** [comment]
@nickolashe I will design the coordinator dropdown in branch `coordinator`

**Comment by dannypernik** [comment]
I tried setting up the dropdown in forms but there were a lot of references to coordinator_firstname and coordinator_email that were throwing errors. I started commenting these out in forms and views but figured I'd leave it. Also wasn't sure how to set up choices to display the org's admins in the dropdown.

Default coordinator should be the logged in admin.

**Comment by dannypernik** [comment]
shavone@bikeaustin.org requested this issue on 10/20

**Comment by nickolashe** [comment]
pretty old issue actually

**Comment by dannypernik** [comment]
yup
