### ISSUE TITLE
approve-hours: auto-display details for first volunteer

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#377]
We are using Foundation's Accordion feature to display the details on approve-hours page. Adding `is-active` class to `class="accordion-item"` will auto-display that section. Is there an easy way to only apply that class to the first volunteer in the `for` loop that displays all volunteers?

**Comment by karbmk** [comment]
display the 1st one separately and loop through the rest i think!

**Comment by nickolashe** [comment]
use `forloop.first` django template tag

**Comment by dannypernik** [comment]
`{% if forloop.first %}` I believe

**Comment by dannypernik** [comment]
I've added `{% if forloop.first %}` to approve-hours branch, PR #259
