### ISSUE TITLE
time-tracker: Status message for hours-overlap not displaying

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#385]
<img width="862" alt="screen shot 2017-08-30 at 12 19 00 am" src="https://user-images.githubusercontent.com/3347095/29856554-3a4104e6-8d19-11e7-8d7b-d97afcac633a.png">

Displays in URL but not on page

**Comment by nickolashe** [comment]
i think https://github.com/opencurrents/opencurrents/pull/369/commits/775e73bfa99beb9de8c7b2f052355b5a32f38456 should fix it. @dannypernik can you confirm?
