### ISSUE TITLE
approve-hours: create a new action log instead of updating the requests for approval.

### ISSUE THREAD

**Issue by karbmk** [opencurrents/opencurrents#388]

**Comment by karbmk** [comment]
@nickolashe , If I understand it correctly we are going to keep the record that requested approval as it is and create a new action timelog record? If so since we are getting the approval hours based on the action_type approval_requests why not we update it. Else it will be duplicate record apart from action type being different which makes the get from action timelog ambiguous.

**Comment by dannypernik** [comment]
Hmm....

**Comment by nickolashe** [comment]
@karbmk can you clarify which part is ambiguous in your opinion? i'd like us to have full history of admin actions. there are several cases why we may need this:
1. so we can present this history back to admin, in case they need to review it or make changes from decline to approved or vice versa
2. imagine a scenario where hours require sign off by multiple persons

**Comment by nickolashe** [comment]
@dannypernik updated the priority and time estimates per your question

**Comment by dannypernik** [comment]
@nickolashe sounds good
