### ISSUE TITLE
time-tracker: error page if user submits date or start/end time in wrong format

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#389]
Should either display error message: "Please enter start and end time with format HH:mm am/pm"
or: "Please enter a valid date with format yyyy-mm-dd"

**Comment by dannypernik** [comment]
<img width="681" alt="screen shot 2017-08-31 at 1 34 25 pm" src="https://user-images.githubusercontent.com/3347095/29939423-6495f16e-8e51-11e7-9f55-f4f358753970.png">

I also received this error when trying to submit hours on 9/31 (September only has 30 days.) So we should display above message in this instance too

**Comment by nickolashe** [comment]
@karbmk i think this can be handled easily using forms validation

**Comment by MaxTattenbach** [comment]
Logic is already in create event template which does not allow to create invalid entries.

**Comment by nickolashe** [comment]
just verified this is already working properly
