### ISSUE TITLE
Live dashboard: have the volunteer move into the registered section once added

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#39]
And change to "Add volunteer" (only 1 a time needed)

**Comment by nickolashe** [comment]
This commits implements live checkin (without refresh):
https://github.com/opencurrents/opencurrents/commit/a7e5a7013dd3befa581f0e908f4d15f291014a36

**Comment by dannypernik** [comment]
@nickolashe you just mean so that the new volunteers appear in the same section as the registered vols, right? If so, I've revised it.
