### ISSUE TITLE
Approve Hours: Not clear what this means "Hours will be approved unless you decline them."

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#395]
Is this after a certain amount of time or when?  Also shouldn't it be backwards - hours should will declined if not approved. 

![hours will be approved unless you decline](https://user-images.githubusercontent.com/26234440/29927773-ede0e1f6-8e2c-11e7-9bab-a29ab535dcf4.PNG)

**Comment by nickolashe** [comment]
agreed its vague

**Comment by nickolashe** [comment]
i think the intention is to justify this "Confirm" button and what it does

**Comment by nickolashe** [comment]
my suggestion was to have an approve button explicitly instead

**Comment by MaxTattenbach** [comment]
Agree.  Change "Confirm" to  "Approve" And lets eliminate hours will be
approved unless you decline them.  Unless that means that if at the end of
the week hours will be automatically approved.  Ok for this round but
should be eventually changed if the prior is the case.

Max Tattenbach
Co-creator
www.opencurrents.com

**Comment by dannypernik** [comment]
Made these changes in time-tracker_new branch
