### ISSUE TITLE
Admin Profile:  Pop-up label when no hours pending approval

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#396]
Lets change "You have reviewed all hours submitted to you. Nicely done!"  to "There are no volunteer hours pending approval." 

![pop-up all hours](https://user-images.githubusercontent.com/26234440/29928044-9aac1c5c-8e2d-11e7-82b8-5fb4960445bb.PNG)

**Comment by nickolashe** [comment]
sounds good to me

**Comment by nickolashe** [comment]
in fact the current message is not always true since some of the hours may have been declined

**Comment by dannypernik** [comment]
@nickolashe @MaxTattenbach I prefer this be a positive message. Note that it says all hours have been "reviewed", not "approved". Also, it's not necessarily true that no hours are pending approval because there could be pending hours for a different admin.

**Comment by MaxTattenbach** [comment]
Review sounds very passive.  So should change the button to "Review
Hours"?  Since the message says review?   I wouldn't think its a good idea.

Max Tattenbach
Co-creator
www.opencurrents.com

**Comment by nickolashe** [comment]
how about "There are no hours that need your approval"?

**Comment by dannypernik** [comment]
I'm tempted to just change this and be done with it but it raises the question of what should be opened as an issue in the first place. Anything that is being marked 'priority low' should be considered as whether it's productive to raise. @MaxTattenbach can you please explain why the current message is a problem? Or if you don't think it's worth further debate, just close the issue. For the record, "There are no volunteer hours" is a passive sentence ('are' is a passive verb). "You have reviewed all hours" is an active sentence.

**Comment by dannypernik** [comment]
Talked to Max and I'm fine with changing the message to include "approved" since the message displays when "Approve hours" is clicked.
