### ISSUE TITLE
Admin-Profile:  Hours Approved status message doesn't go away when refreshing page.

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#398]
![pop-up hours approved](https://user-images.githubusercontent.com/26234440/29929197-7b84d9ce-8e30-11e7-9197-f13f72d17a64.PNG)

**Comment by nickolashe** [comment]
saw this one too. it looks even more cumbersome if you try clicking Approve hours button then and it shows another message on top of this one (that there are no hours to approve)

**Comment by dannypernik** [comment]
@nickolashe begs the question if there's a way to pass status message without relying on URL - which will result in persistent status message when page is refreshed

**Comment by nickolashe** [comment]
there is a way but its not straightforward, i'd rather punt on this for now

**Comment by dannypernik** [comment]
dup of #563
