### ISSUE TITLE
Create Event: Unclear that the buttons of public or private are not clickable. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#407]
Note we are using the same type of button for click and select.  I think it would be much better if the buttons for select are are different for the clicking.  I got confused by this when testing.

![buttons display](https://user-images.githubusercontent.com/26234440/29982997-7f5c993a-8f19-11e7-988c-8334d55755ca.PNG)

**Comment by dannypernik** [comment]
@MaxTattenbach I will add a ? icon next to these

**Comment by nickolashe** [comment]
@dannypernik i think this has been done already?

**Comment by dannypernik** [comment]
yep
