### ISSUE TITLE
Create Event:  Lets change the "Create" Button to "Next"  since we are not finalizing the process and actually taking them to the invite volunteers.

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#408]

**Comment by dannypernik** [comment]
@MaxTattenbach event is created as soon as they click "Create"

**Comment by nickolashe** [comment]
interesting subtlety

**Comment by nickolashe** [comment]
technically Danny is correct, but not sure what's best from the UI perspective

**Comment by dannypernik** [comment]
I'd like to leave it. "Next" makes it seem like the event-creation process is longer, and there's no "Complete" button at the end so it's a little anticlimactic. I think it's good for the user to know they've created an event when they submit the create-event form even if they dont invite volunteers. @MaxTattenbach please close if you're good with this.

**Comment by nickolashe** [comment]
"anticlimactic" wins it

**Comment by MaxTattenbach** [comment]
Sorry Danny, I guess I never closed the issue.  Fine with me.

Max Tattenbach
Co-creator
www.opencurrents.com

**Comment by dannypernik** [comment]
All good
