### ISSUE TITLE
invite-volunteers & live-dashboard: email should not be case sensitive

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#410]
<img width="727" alt="screen shot 2017-09-04 at 11 31 01 am" src="https://user-images.githubusercontent.com/3347095/30034591-f4c1166a-9167-11e7-8460-3f63f319ded6.png">

Max and I ran several tests with same name, different name, and emails with and without capital letters. We concluded that we just need to make sure that emails with different capitalization are considered the same email address on both of these pages.

**Comment by tevtonez** [comment]
here is the fix for invite-volunteers part: 008a9fd

**Comment by MaxTattenbach** [comment]
@tevtonez Ok - I'll test once it has been merged to develop.  But yes I think that should solve the problem of multiple users being created.

**Comment by tevtonez** [comment]
@MaxTattenbach thanks!

**Comment by nickolashe** [comment]
@tevtonez i think the remaining step we discussed here is to add lower conversion to the js in live-dashboard

**Comment by tevtonez** [comment]
@nickolashe yup, this fix is included in #964 PR

**Comment by tevtonez** [comment]
I also checked time tracker form (as per discussion with Max) - looks like all fields are lowercased there too
