### ISSUE TITLE
event-detail: *|EVENT_ID|* in coordinator-messaged email template not getting passed

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#411]
<img width="593" alt="screen shot 2017-09-04 at 12 08 49 pm" src="https://user-images.githubusercontent.com/3347095/30034850-d600a2f2-9169-11e7-9609-51343dec3f2b.png">

Email template has same name as variable here, for some reason it's not populating:
https://github.com/opencurrents/opencurrents/blob/develop/openCurrents/views.py#L1360

**Comment by nickolashe** [comment]
@dannypernik is this when linking from email back to our site?

**Comment by nickolashe** [comment]
for reference, in html %7C is the `|` symbol. is this what is used to quote email template vars in mandril?

**Comment by dannypernik** [comment]
@nickolashe yes linking from email to event page. Yes template vars use format `*|EVENT_ID|*` and it's getting converted to %7C in the URL because the variable is not populating

**Comment by nickolashe** [comment]
i know we've been using mandrill vars in links before, such as for verification tokens. which email template is this so i can take a look?

**Comment by dannypernik** [comment]
@nickolashe coordinator-messaged

**Comment by nickolashe** [comment]
#456

**Comment by nickolashe** [comment]
@dannypernik can you test on the dev server

**Comment by nickolashe** [comment]
bump

**Comment by dannypernik** [comment]
Hm looks like the link is right, but new error: 

<img width="744" alt="screen shot 2017-09-12 at 4 00 14 pm" src="https://user-images.githubusercontent.com/3347095/30348019-8b0cbd38-97d3-11e7-8651-175109ab4db9.png">

**Comment by nickolashe** [comment]
@dannypernik i think this just means that event id does not exist, but we need handle this properly nevertheless

**Comment by dannypernik** [comment]
oops yep it's because I didn't change the URL.
