### ISSUE TITLE
invite-volunteer after create-event: Wrong email template and wrong URL

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#412]
When volunteer is invited to an event, they are currently sent to invite-volunteer. Instead, volunteers who **do not have a password saved** should be sent invite-volunteer-event-new, while volunteers **with a password saved** should be sent invite-volunteer-event-existing.

Since we want event-detail to be public, we need to have a signup/login popup to be displayed when non-logged-in user clicks "Register".

Also need to discuss whether volunteers should be automatically registered to events or just display invitees all together.

**Comment by karbmk** [comment]
PR #383

**Comment by nickolashe** [comment]
@karbmk i can't see in the pr where the issue is being addressed

@dannypernik can you pull these changes and confirm that the issue is still open please

**Comment by dannypernik** [comment]
@karbmk I received invite-volunteer-event-existing when inviting a user who does not have a password saved. invite-volunteer-event-new should be used instead.

The correct template was used when sending to a user with a password saved.

**Comment by nickolashe** [comment]
@karbmk has this been addressed yet?

**Comment by dannypernik** [comment]
@nickolashe @karbmk I'm expanding this issue to include a bug I just found because it occurs in the same instance - after an admin creates an event. Check out the URL shown after I click "Create" on create-event:

<img width="655" alt="screen shot 2017-09-09 at 1 14 32 pm" src="https://user-images.githubusercontent.com/3347095/30242709-24c234dc-9561-11e7-9f91-7197dc07913f.png">

**Comment by nickolashe** [comment]
@dannypernik what is the bug exactly? we did change the format of the url.

**Comment by dannypernik** [comment]
%5B is `[` and %5D is `]`

Looks like they are getting passed into the URL.

**Comment by nickolashe** [comment]
what makes you think its a bug? we are passing a list of id's now instead of a single id. i think you've participated in the discussion related to this.

**Comment by dannypernik** [comment]
Oh ok. Cool :)
