### ISSUE TITLE
create-event: Private events showing up on upcoming-events

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#413]
Event is showing is_public=FALSE, but the event still displays in upcoming-events.

**Comment by dannypernik** [comment]
@nickolashe @MaxTattenbach Begs the question: Should private events be displayed on upcoming-events? We could display "(This is an invite-only event)". Intention is to show all the activity in the community. My preference is to leave them off the page.

**Comment by MaxTattenbach** [comment]
Rather they showed up as private events but not strong either way.

Max Tattenbach
Co-creator
www.opencurrents.com

**Comment by nickolashe** [comment]
i don't think private events should be showing on that page

**Comment by nickolashe** [comment]
is this still the case?

**Comment by dannypernik** [comment]
Looks like this is working properly in dev server. Private events show up only for admins of org in upcoming events. I could see this being confusing for admins who think their private events are showing up for volunteers, but it's good for now.

**Comment by nickolashe** [comment]
it'd be easy to mark those appropriately
