### ISSUE TITLE
time-tracker: Error page when submitting hours (though hours were submitted)

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#416]
Submitted this data:
<img width="670" alt="screen shot 2017-09-05 at 10 34 55 am" src="https://user-images.githubusercontent.com/3347095/30069403-48bd26f0-9226-11e7-88fb-ad950e541765.png">

Received this error:
![image](https://user-images.githubusercontent.com/3347095/30069700-1341e4d8-9227-11e7-9f8b-28c9a5cdaa33.png)

Tried again with same details - hours overlap detected (I also checked the database, the entry is there)
<img width="666" alt="screen shot 2017-09-05 at 10 35 10 am" src="https://user-images.githubusercontent.com/3347095/30069411-4da77620-9226-11e7-8f4a-bf17708edb01.png">

**Comment by nickolashe** [comment]
https://github.com/opencurrents/opencurrents/commit/5114dbed82fe74eb4bef02c44cc6c4be6471624e
