### ISSUE TITLE
Email Confirmation of Volunteer:  Message could be improved telling the coordinator what event this is. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#417]
![event confirmation email to admin](https://user-images.githubusercontent.com/26234440/30070124-1be3e4be-9228-11e7-8af5-35c3cfadf5c5.PNG)

**Comment by nickolashe** [comment]
agreed

**Comment by dannypernik** [comment]
@nickolashe or @karbmk could you create variable `*|EVENT_NAME|*`? Let me know when it's there and I'll update the template

**Comment by dannypernik** [comment]
@nickolashe @karbmk We need to add `*|EVENT_NAME|*` to `volunteer-messaged` `volunteer-registered` and `coordinator-messaged` templates. Please let me know when it's complete.
