### ISSUE TITLE
invite-volunteers: When inviting to an event, email does not send if user present

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#418]
I think this is happening because invite-volunteers does not send an email to existing user if we're simply inviting them to track hours (ie. clicking the link in the waveburger menu). However, both new and existing users should be invited to event when admin navigates to invite-volunteer through the event's mini-menu (and thus has an event_id associated).

**Comment by karbmk** [comment]
PR #383

**Comment by nickolashe** [comment]
@karbmk i can't see in the pr where the issue is being addressed

**Comment by nickolashe** [comment]
@dannypernik can you pull these changes and confirm that the issue is still open please

**Comment by dannypernik** [comment]
@nickolashe invite-volunteers did in fact invite an existing user to an event, so it's working. However I did find a small issue with the status message - it should say you invited 1 volunteer to the event, not to openCurrents:

<img width="512" alt="screen shot 2017-09-06 at 4 58 50 pm" src="https://user-images.githubusercontent.com/3347095/30136467-b5abfd46-9324-11e7-9d75-b68c0b928a56.png">

**Comment by nickolashe** [comment]
so when invite is event-specific, the status mag should say invited to the event, not opencurrents
