### ISSUE TITLE
event-detail: Display coordinator name

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#421]

**Comment by dannypernik** [comment]
PR #510

**Comment by dannypernik** [comment]
@nickolashe do we have a way to display `{{ coordinator.firstname }} {{ coordinator.lastname }}` on event-detail? You can search the above var names in event-detail on coordinator_name branch

**Comment by nickolashe** [comment]
i thought we are removing coordinator from some page, was it not from this one?

**Comment by dannypernik** [comment]
@nickolashe nope removing coordinator_firstname and coordinator_email inputs from create-event. we want to show the name of the person the volunteer is contacting in event-detail.
