### ISSUE TITLE
Email Inviting Volunteer Coordinator:   Not displaying the invited by. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#424]
When selecting someone else the BizDev email does not display "Invited By"
![invited by](https://user-images.githubusercontent.com/26234440/30078385-9c5285aa-9242-11e7-85ec-09dd1c98356f.PNG)

**Comment by nickolashe** [comment]
probably a discrepancy in the email template var

**Comment by dannypernik** [comment]
In MailChimp: Invited by: *|FNAME|* *|LNAME|*

**Comment by nickolashe** [comment]
so we must not be passing those vars in

**Comment by dannypernik** [comment]
`sendTransactionalEmail(
                'new-admin-invited',
                None,
                [
                    {
                        'name': 'ORG_NAME',
                        'content': org.name
                    },
                    {
                        'name': 'ADMIN_NAME',
                        'content': admin_name
                    },
                    {
                        'name': 'ADMIN_EMAIL',
                        'content': admin_email
                    },
                    {
                        'name': 'FNAME',
                        'content': self.request.user.first_name
                    },
                    {
                        'name': 'LNAME',
                        'content': self.request.user.last_name
                    }
                ],
                'bizdev@opencurrents.com'`

**Comment by nickolashe** [comment]
is the mandrill syntax `*|<var>|*` ?

**Comment by dannypernik** [comment]
@nickolashe yes but note that in views, the `*| |*` are not set

**Comment by nickolashe** [comment]
@dannypernik i meant in your comment do we need stars around bars?

**Comment by dannypernik** [comment]
Yes.

**Comment by nickolashe** [comment]
https://github.com/opencurrents/opencurrents/issues/424#issuecomment-328260357

**Comment by dannypernik** [comment]
Ah sorry @nickolashe that was due to Github's markup, `* *` makes something italic

**Comment by nickolashe** [comment]
ok, so another possibility is that admin did not have a first and last name?

**Comment by dannypernik** [comment]
@nickolashe perhaps you're right. looks like it's working fine for me:

<img width="608" alt="screen shot 2017-09-24 at 9 20 28 am" src="https://user-images.githubusercontent.com/3347095/30783524-d2de831e-a109-11e7-82dd-f292071dd780.png">
