### ISSUE TITLE
admin-profile: Check conditions for showing approve-hours popup

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#425]
Admin should see popup on first login of the week if pending hours are present

**Comment by dannypernik** [comment]
@nickolashe @karbmk just checked and the approve-hours message still pops up on /profile when no hours are present.

**Comment by nickolashe** [comment]
https://github.com/opencurrents/opencurrents/pull/508/commits/fe43f0ffe7559f05c94a6d22b67dffd14e48a9a5

**Comment by nickolashe** [comment]
@dannypernik can you check again with this fix
