### ISSUE TITLE
time-tracker in prod: Orgs are being listed that have no approved admin

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#432]
For example, Carlee McConnell signed up Safe Kids Austin led by Dell Children's Medical Center. She has not been approved as an admin but this org is listed in the dropdown.

**Comment by nickolashe** [comment]
@dannypernik do you see this as a problem? they can be submitting hours until we approve the admin.

**Comment by dannypernik** [comment]
If someone signed up junk orgs, they would immediately show up in this list. I think it's best to require approval first. (For example, one org is currently listed twice with slightly different names)

**Comment by nickolashe** [comment]
how about we additionally approve orgs? i think this would take care of this problem.

**Comment by dannypernik** [comment]
This would be an extra step for us when approving admins, I'd rather not. @karbmk was it you who completed the issue of only displaying orgs with 1 or more admins in time-tracker? Check out this screenshot, I'm really confused as to why the orgs are not consistent between database and select box in production (I deleted some of the orgs that are still showing in the select box and some of the names are different)

<img width="1151" alt="screen shot 2017-09-06 at 3 49 32 pm" src="https://user-images.githubusercontent.com/3347095/30145566-a7ec14b0-9357-11e7-9517-06535e41fba8.png">

**Comment by nickolashe** [comment]
the main issue has been resolved, created #449 to address the last comment
