### ISSUE TITLE
live-dashboard: Baldwin's hours not converting to Currents

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#443]
Baldwin was checked into the KAB lake cleanup, but he has 0 Currents in his account.

<img width="715" alt="screen shot 2017-09-08 at 11 16 30 am" src="https://user-images.githubusercontent.com/3347095/30222642-1026e088-948d-11e7-9b4f-efcac0daae34.png">

**Comment by nickolashe** [comment]
is this a past event?

**Comment by dannypernik** [comment]
Yep. Aug 12

**Comment by nickolashe** [comment]
created #448
