### ISSUE TITLE
org-admin: show all past events

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#444]
<img width="1016" alt="screen shot 2017-09-08 at 12 28 40 pm" src="https://user-images.githubusercontent.com/3347095/30223649-58966394-9491-11e7-8a7a-a328f3078bcb.png">

<img width="794" alt="screen shot 2017-09-08 at 11 16 49 am" src="https://user-images.githubusercontent.com/3347095/30223645-569eb956-9491-11e7-8c70-e19211fff06a.png">

**Comment by nickolashe** [comment]
we are only showing past 3 events:
https://github.com/opencurrents/opencurrents/blob/develop/openCurrents/views.py#L1059

**Comment by dannypernik** [comment]
Oh. I'm ok with that but I think we need a "See all" button. I think the cleanest way to do this would actually be to pull all events into the template but set the height of the div to only display the latest 3. Then "See all" would expand the height of the div. Only issue is whether passing all events into the template would eventually affect time for pageload.

**Comment by nickolashe** [comment]
it would eventually, but probably not anytime soon

**Comment by dannypernik** [comment]
@nickolashe if it's quick, could we remove the limit on displaying 3 events for now? Going forward Max is thinking we could display the org's livefeed on admin-profile and past events on a separate page.

**Comment by nickolashe** [comment]
i think a proper way would be to include an "expand" list button below the first N events, which would fetch the entire list on demand

**Comment by nickolashe** [comment]
did we reach any consensus here

**Comment by dannypernik** [comment]
I'd like to be able to click expand and have the events slide down, but I'm thinking theyd already need to be fetched prior to click in order for a smooth slideDown. I've heard of "Lazy load" where a page loads the rest of the content first then hidden content second, perhaps theres an easy way to do that on the backend and I can add the "expand" button?

**Comment by MaxTattenbach** [comment]
I wouldn't worry about fetching past events, if they are non-existent at
the moment.  No body needs them.  It was merely testing.

Max Tattenbach
Co-creator
www.opencurrents.com

**Comment by nickolashe** [comment]
agreed, too much trouble for the time available

**Comment by nickolashe** [comment]
@dannypernik out of curiosity, when you say "they'd already need to be fetched", how many events would you feel comfortable with fetching ?

**Comment by dannypernik** [comment]
If three were shown initially, I'm thinking we could fetch an additional 7 so that when "see more" is clicked, they would see 10. And then 10 at a time each time "see more" is clicked.

@MaxTattenbach not sure what you mean by non-existent events? I feel that it would be better to show all events rather than just 3 assuming the 'show more' button is not considered MVP. I know I for one was confused when I wasn't seeing one of the past events in admin-profile

**Comment by MaxTattenbach** [comment]
Ok - got it.  As in fetch events I thought we were referring to events that
happened previously from our "release".  Something similar to the issue we
were having with the Currents in the DB tracked prior a certain date.   I
do think we should fetch events and Currents manually created.

Max

Max Tattenbach
Co-creator
www.opencurrents.com

**Comment by dannypernik** [comment]
So @nickolashe can we just show all past events in org-admin for now? Note that nothing comes after 'Past events' in org-admin so there's no harm in listing all of them IMO

**Comment by nickolashe** [comment]
@dannypernik i thought we implemented the change - has this been merged already?

**Comment by dannypernik** [comment]
@nickolashe @MaxTattenbach sorry shouldn't have moved to "To be tested" - past events template is in PR #1007 where I'm asking Kostya for a solution to a failing test.

**Comment by nickolashe** [comment]
@dannypernik that PR has been merged 4 days ago
