### ISSUE TITLE
time-tracker: figure out the reason for discrepancy between org list and db

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#449]

**Comment by dannypernik** [comment]
@nickolashe is there any easy way to test it on a hosting provider other than heroku?

**Comment by nickolashe** [comment]
are you saying heroku is the reason?

**Comment by dannypernik** [comment]
I can't yet say it's not the reason

**Comment by nickolashe** [comment]
correct me if i am wrong, but i think we've verified that changes occur in the db

**Comment by dannypernik** [comment]
Yes, they change in the db. But the interface doesnt update until we deploy changes. I don't know really, just spitballing

**Comment by nickolashe** [comment]
got it, what about locally

**Comment by dannypernik** [comment]
shoot, nope doesn't work locally either

**Comment by dannypernik** [comment]
oh wow. locally I added 'autocomplete':'off' in forms.py to the org select box, and it worked. I'm wondering why it didn't work for me when I tried on test server. Perhaps I added to wrong branch? Testing again

**Comment by dannypernik** [comment]
Haha ok here's one for you... it seems that the select box cache refreshes locally whenever I modify forms.py. I verified that it's unrelated to the attributes of the org box by making a change in a different part of the file. My testing process was to check which orgs were showing on time-tracker, delete OrgUser and remove admin group from admin, and refresh time-tracker. List did not update. However, after changing a line in forms.py (removing autocomplete line from the other select box), the test org was removed from org select.

**Comment by dannypernik** [comment]
Oo, perhaps...?? https://snakeycode.wordpress.com/2014/11/20/django-forms-choices-and-caching/

**Comment by nickolashe** [comment]
i think #451 should fix it
good job on finding the cause @dannypernik

**Comment by nickolashe** [comment]
@dannypernik @MaxTattenbach can you double check the fix works for you pls

**Comment by dannypernik** [comment]
@nickolashe Works! Also verified that a new admin populates after being added to db.
