### ISSUE TITLE
Non Profit Sign-up: Not sending email to Biz Dev Email and can't find org to associate in the data base

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#463]
Please check 

@nickolashe @dannypernik  Business sign-up is working but not non-profit.

**Comment by dannypernik** [comment]
@MaxTattenbach it's working for me. I received test email and org was created (I assume you received too). Did you possibly sign up with an email address that was already in the db? Not sure what we want to happen in that instance

**Comment by MaxTattenbach** [comment]
@dannypernik that's very weird.  So I just created a new one see the org registered but I am not getting the email to Biz Dev.

**Comment by MaxTattenbach** [comment]
Guys got it.   Three of the test email cam in at once.  About one hour late.

**Comment by MaxTattenbach** [comment]
@dannypernik @nickolashe;  my bad.  Seems that this is working.  May have been that it was associated to an existing account.
