### ISSUE TITLE
Offer Page #2: Set Offer

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#465]
Suggestions:

Lets add a "?" bubble next to C Share:  Lets define it. 

C Share:  The portion of a product that is paid with Currents.  Or something simple.

**Comment by dannypernik** [comment]
@MaxTattenbach don't you think the main question above it makes it clear?

<img width="603" alt="screen shot 2017-09-13 at 6 10 01 pm" src="https://user-images.githubusercontent.com/3347095/30404944-ca404462-98ae-11e7-8453-7d91692bbd46.png">

**Comment by MaxTattenbach** [comment]
@dannypernik Its clear to me but specially important to define it if we are going to use it elsewhere.

**Comment by dannypernik** [comment]
I suggest we leave as is and define elsewhere if we use it elsewhere.
