### ISSUE TITLE
Offer Page #4: General Comments.

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#467]
General Comments:

Want to think if there is a way to mention Current share.  I'll take a lead on the language. 

As an authorized representative of [Business Name], I agree to accept [a maximum of] Currents [per month] as partial payment for the following products and services:

[20%] of [Products]
[20%] of [Services]
[20%] of [Item 1]
Customers will pay full price at point of sale and provide openCurrents with proof of purchase. At the end of the month, openCurrents will invoice [Business Name] for the total amount discounted to customers, then reimburse customers the discounted amount. For every $10 discounted, [Business Name] can choose to receive 1 Current or claim a $10 charitable donation

**Comment by dannypernik** [comment]
@MaxTattenbach I agree it would be nice to get rid of mentions of discounts.

**Comment by dannypernik** [comment]
Check https://opencdesign.herokuapp.com/offer
