### ISSUE TITLE
Profile: Lets change "Give Time" button, to "Create Currents"

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#469]
Note that we had previously changed the button from "earn Currents" to "give time".

Give time is not necessary correct as in manual tracking they already gave time.   I think Create Currents would be better.

**Comment by dannypernik** [comment]
I changed "Earn Currents" to "Give time" because I think it is clearer to end users how to track time. "Earn Currents" requires the user to think more and is thus less intuitive. @nickolashe ?

**Comment by nickolashe** [comment]
I guess technically Max is correct. @dannypernik What's unintuitive about "Earn Currents"?

**Comment by dannypernik** [comment]
K will change it

**Comment by MaxTattenbach** [comment]
I actually like Create more than Earn.

Max Tattenbach
Co-creator
www.opencurrents.com

**Comment by dannypernik** [comment]
<img width="219" alt="screen shot 2017-09-18 at 2 07 26 pm" src="https://user-images.githubusercontent.com/3347095/30559603-c8f51072-9c7a-11e7-898d-9f7c64b9e94e.png">

what do you guys think of this? If we use "Create Currents" and "Redeem Currents" thats 3 'Currents' in the space of 2 inches. Also the buttons are too long and move to a new line on medium screens

**Comment by nickolashe** [comment]
looks good to me

**Comment by dannypernik** [comment]
@MaxTattenbach ?

**Comment by dannypernik** [comment]
Seems like we've agreed on "Volunteer"
