### ISSUE TITLE
Reedem-Currents: Messaging

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#472]
Danny, 

1. Lets focus on putting the message on paying full price/how it works (general concept) on the Market Place page rather than on the Redeem Currents.  With this being said lets add this message in the Market Place, 

2.  Same with "learn more". Lets take the entire "Note" to the market place. 

3.  Change text in "Note":  (Assumes its in the Market Place)
You will pay the full price with participating vendors at point of sale whether its via eCommerce or at physical location.  You then select the vendor where you purchased and exchange your Currents for Dollars.

3.  Change  "Learn More" text to:

In order to make it as easy as possible for businesses to accept Currents, we have designed the exchange process in such a way that nothing changes at point of sale.  As a result, more businesses are now accepting Currents, which means you can use Currents to get more of what you want.

@dannypernik  note that the volunteers are not waiting until the end of the month when redeeming Currents. They are getting Pending USD as soon as they upload the proof of purchase and if we think it matches then we can disburse USD once they do so.  .

**Comment by dannypernik** [comment]
@MaxTattenbach I think from a cash flow perspective it would be better to wait until payment is due from vendors to disburse cash. Yes this is a very small liability now but it will grow over time. Let's design this to be scalable from the start so we dont give people the expectation of getting their money right away. Not until CLO

**Comment by dannypernik** [comment]
@MaxTattenbach the more I look at it, the more sure I am that the note about paying full price should go on the redeem-currents screen. I'm adding the 3 screens you suggested, so it will go on the 'Shelf price' page which makes sense.

**Comment by MaxTattenbach** [comment]
@dannypernik I am OK with actually disbursing money at the end of the month, but do note that we will most likely not get paid back from the vendors immediately.

**Comment by MaxTattenbach** [comment]
@dannypernik I'll add a few separate issues for the pages so we don't have it all in one.

**Comment by nickolashe** [comment]
i think initially may be easier to go with end-of-the month disbursements.

**Comment by MaxTattenbach** [comment]
Agree, but pending dollars are immediate.

Max Tattenbach
Co-creator
www.opencurrents.com

**Comment by dannypernik** [comment]
Agree to showing pending dollars immediately

**Comment by dannypernik** [comment]
Changes made based on our conversation: https://opencdesign.herokuapp.com/redeem-currents

Will add messaging on marketplace
