### ISSUE TITLE
public-record: Display orgs, vols, businesses 10 per page

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#474]
https://opencdesign.herokuapp.com/public-record

Need to show orgs, vols, or businesses based on select box, and show 10 entries on each page.
I will likely need to do more to set up pagination, let me know when you get there.

@nickolashe @MaxTattenbach do we want to enable data export on this page? Currently export is set up for admins, Nicko will it be easy enough to reuse export code for this page? Note that we have an extra data field: Organization name.

**Comment by MaxTattenbach** [comment]
I don't think its necessary to be able to download data. 

@dannypernik  In design for the leader board we should perhaps  have total of Currents Issued per month of the ecosystem., somewhat like a counter. 

Also lets think if we want to categorize by "top" or by the latest issuers.  To be discussed.

**Comment by dannypernik** [comment]
Removed export-data button and changed page name from leaderboard to public-record:

https://github.com/opencurrents/opencurrents/commit/8ae97c6cddd99d01af7a605bc7296629e14b9e0e

**Comment by dannypernik** [comment]
done by Danil
