### ISSUE TITLE
business-profile: create template

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#475]
Include business' Currents, place, view, (edit?) and delete offers, and see redeemed offers

**Comment by dannypernik** [comment]
@nickolashe I'm thinking I should be able to create a biz-admin page and leave /profile design untouched. Profile currently displays org name under user name with the gear icon next to it. Can we just modify the URL of the gear based on whether the org is a nonprofit or business?

**Comment by nickolashe** [comment]
did you mean biz-admin will take place of org-admin?

**Comment by dannypernik** [comment]
@nickolashe no I was thinking admin-profile will be directed to if user is admin of nonprofit, and biz-profile will be directed to if user is admin of business. Does that work?

**Comment by dannypernik** [comment]
Perhaps I should change name of admin-profile to org-profile (but intended to be just for nonprofits)

**Comment by dannypernik** [comment]
@nickolashe I see we have duplicate issues for this and others within General MVP milestone. Do you want to close this or #475 ?

**Comment by nickolashe** [comment]
yes sounds good on biz-profile / org-profile

**Comment by nickolashe** [comment]
this is #475 in fact, so i can only close this _and_ #475

**Comment by nickolashe** [comment]
did you mean some other issue? this one was meant for the change on the front-end

**Comment by dannypernik** [comment]
Haha oops yes I meant #495 which I guess is a backend issue whereas this one is a front-end
