### ISSUE TITLE
Create event: pick existing project or create new one based on autocomplete

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#48]

**Comment by nickolashe** [comment]
Implements autocomplete of existing project names for org:
https://github.com/opencurrents/opencurrents/commit/31864eb9d8a7939d29488757a721720b8c93ac66

**Comment by dannypernik** [comment]
@nickolashe It seems like the most useful field to autofill based on prior project would be Event description, followed by multiple locations. At the moment is anything autofilled into the form besides name?
