### ISSUE TITLE
Offer Form: Confirmation

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#490]

**Comment by dannypernik** [comment]
Note that #488, #489, and #490 are actually a single form. Only "Confirm" button submits.

**Comment by nickolashe** [comment]
@dannypernik collecting input from previous screens on confirmation is needed, as we discussed

**Comment by dannypernik** [comment]
@nickolashe are inputs now being collected?

**Comment by nickolashe** [comment]
yes, i think so
