### ISSUE TITLE
Redeem Form: "Other PoP"

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#492]

**Comment by dannypernik** [comment]
Note #491, #492, #493, and #494 are all the same form.

For "I have other PoP" popup, we are using the same input field. We need to mark whether the user uploads a receipt from main page or other PoP from popup. We could either do this as a checkbox that is checked for one and unchecked for the other, or we could add a second input form. Let me know which one you'd prefer @nickolashe

**Comment by nickolashe** [comment]
we can use the same input with some way of letting the backend know the type of PoP submitted

**Comment by dannypernik** [comment]
Sounds good. Adding a hidden checkbox in design branch
