### ISSUE TITLE
Offer Delete form

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#497]

**Comment by dannypernik** [comment]
@nickolashe trying to remember what we said for the design of this one. Are we good with having a popup displaying "Are you sure you want to delete?" on biz-admin page? The button inside the popup would be a submit button.

**Comment by nickolashe** [comment]
yes i think this will work here

**Comment by dannypernik** [comment]
Cool, popup is in biz-admin on develop
