### ISSUE TITLE
offer: Display dropdown after error message when Limit is clicked

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#517]

**Comment by nickolashe** [comment]
@dannypernik i don't understand what the issue is about. can you please add a description and assign to someone

**Comment by dannypernik** [comment]
@nickolashe pretty tricky to explain actually, I can show you this sometime on screenshare and we can brainstorm how to fix it. Assigning both of us

**Comment by nickolashe** [comment]
@dannypernik  i think you were planning to elaborate on the issue

**Comment by MaxTattenbach** [comment]
Lets discuss if necessary.

**Comment by dannypernik** [comment]
fixed
