### ISSUE TITLE
Beta messaging 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#518]
Let's include the beta messaging in the website.

**Comment by dannypernik** [comment]
@MaxTattenbach where do you envision this messaging? In a Welcome popup automatically displayed when the user first logs in? Or on the homepage?

**Comment by MaxTattenbach** [comment]
I think both home page and profile. I would place it next to or close to
the openCurrents logo (home button).

**Comment by dannypernik** [comment]
"Beta" added next to logo. Popup is included in separate issue
