### ISSUE TITLE
Nominate Org:  Should display email of the user so we can follow-up with him. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#520]
![image](https://user-images.githubusercontent.com/26234440/31408699-11ea5520-adcf-11e7-9300-44e58f7330e9.png)

**Comment by dannypernik** [comment]
<img width="695" alt="screen shot 2017-10-15 at 5 37 24 pm" src="https://user-images.githubusercontent.com/3347095/31590033-8f9d3bfa-b1cf-11e7-93ec-c6033e826f17.png">
