### ISSUE TITLE
Check that redeem currents form does not allow uploading files other than images

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#521]

**Comment by dannypernik** [comment]
@nickolashe there's an `accept="image/*"` attribute in html that limits acceptable files to images:

https://github.com/opencurrents/opencurrents/blob/design/openCurrents/templates/redeem-currents.html#L53

This limits filetypes to PNGs, JPEGs, and GIFs.

**Comment by nickolashe** [comment]
@dannypernik yes, thanks. this task was meant to be a unit test case spec.

**Comment by dannypernik** [comment]
Gotcha @nickolashe should we leave this open?

**Comment by nickolashe** [comment]
yes
