### ISSUE TITLE
event-detail: Incorrect behavior when coordinator sends message to volunteers

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#529]
Currently, event-detail always directs to registration-confirmed on submit. This page states, "You're all set! Thank you for helping (org_name) (event_name) on (event_date)."

However, when a message is simply being sent from this page, either by a volunteer or by a coordinator, we should display a status message on profile or org-admin respectively.

We can display these status messages (with `class="success"`) on profile and org-admin:
If previously registered volunteer messages: "Your message has been sent the event coordinator."
If coordinator messages volunteers: "Your message has been sent to the event's invitees."

Last but not least, we get an UnboundLocalError if submit button is clicked when message field is empty. Note that this textbox is optional when volunteer is registering but should be required when vol is already registered or coordinator is accessing page.

![image](https://user-images.githubusercontent.com/3347095/31577922-8b345290-b0dc-11e7-9c0c-230886ba5b7a.png)

**Comment by nickolashe** [comment]
refactor `event_register`

**Comment by nickolashe** [comment]
error fixed, need to show status message on event-detail

**Comment by nickolashe** [comment]
@dannypernik do you know what the status is on this one?

**Comment by dannypernik** [comment]
@nickolashe the error no longer displays. However, status message is still not displaying when "Send message" input field is blank, even though it's passed into URL.

I don't mind the "You're all set!" message displaying on registration-confirmed when volunteers message coordinator, but we need a different message when the coordinator is contacting volunteers. `{% if coordinator %}' used in event-detail would do the trick.

**Comment by nickolashe** [comment]
@dannypernik think you push the corresponding change?

**Comment by dannypernik** [comment]
@nickolashe started PR #879 but not sure how to get `{% if coordinator %}` working. Tried copying a few things over from EventDetailView but to no avail

**Comment by MaxTattenbach** [comment]
@dannypernik  can you test this one.  Not sure I follow.

**Comment by MaxTattenbach** [comment]
@dannypernik @nickolashe  Email is being sent to volunteers with correct information,  Although the post state for the admin shows an error.   Similar to #929 when volunteer contacts admin through event detail. 

This is the post-state after contacting the volunteers. 

![image](https://user-images.githubusercontent.com/26234440/34441924-61386f38-ec84-11e7-9e11-189afe689699.png)

**Comment by dannypernik** [comment]
@MaxTattenbach I believe this and #929 are now working? Can you verify?
