### ISSUE TITLE
biz-admin: list both pending and approved redemption requests

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#541]

**Comment by nickolashe** [comment]
add $ do dollar figures

**Comment by nickolashe** [comment]
@dannypernik you can help out with the UI here if you'd like

**Comment by dannypernik** [comment]
@nickolashe I've copied the "Redeemed offers" section (including all logic) and made 2 sections - "Pending redemptions" and "Accepted redemptions". You'll need to change the variables in the logic accordingly. This is currently unDRY and when I find time to continue front-end refactoring, I'd like to figure out how to create blocks for these kind of lists.

**Comment by nickolashe** [comment]
@dannypernik I suggest going forward we never implement new features unDRY but rather make the effort to figure out the proper way. Otherwise we'll end up with a huge backlog that's increasingly hard to manage.
