### ISSUE TITLE
org-admin: Event Drop Down - Add to list "View & Contact Invitees".  

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#543]
Not intuitive that it's from "View Event Details" where you contact volunteers.  I would leave "View Event Details" but just leave the details of the events ad another section to contact them. 

![image](https://user-images.githubusercontent.com/26234440/31801873-82a31f02-b510-11e7-9b32-707832c5e1ff.png)

**Comment by dannypernik** [comment]
@nickolashe Will `{% if user is coordinator %}` or something to that effect be available in org-admin.html? Only coordinator can view and contact invitees so we would need to add that logic inside the event dropdown.

**Comment by nickolashe** [comment]
yes we can make that happen. should this be moved to General mvp?

**Comment by dannypernik** [comment]
Pushed to develop and moved to General mvp. Search `{% if user is coordinator %}` (currently commented out) in org-admin to find where conditional statement needs to be added.
