### ISSUE TITLE
event-detail: Change message after Contacting Coordinator on View Event Detail.

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#545]
It should say your message has been sent to the coordinator's email. 

@nickolashe we'll need conditional variable to change the text. See comments below and the use-case spreadsheet:
https://docs.google.com/spreadsheets/d/15mnrkl4Rc5dsFX8VAGOeuPPfCQTPHyOWV1SVwkXIqNQ/edit?usp=sharing

**Comment by dannypernik** [comment]
@nickolashe this refers to the `registration-confirmed` page, which the user is directed to after registering or sending a message. There's 2 scenarios where we need different messages - when someone messages the coordinator after having previously signed up, and when a coordinator messages volunteers. (The 3rd scenario, which the confirmation page was originally designed for, is when a volunteer registers for the 1st time.)

Do we have a variable that we can use on registration-confirmed to change the message in these cases? I'm curious if we may want to display a status message on profile instead, as even the title of registration-confirmed is incorrect in the additional scenarios. Thoughts?

**Comment by nickolashe** [comment]
@dannypernik what would be the easiest in your opinion?

**Comment by dannypernik** [comment]
@nickolashe perhaps using registration-confirmed but renaming it event-confirmation would be easier so you don't have to change the routing. One point to note is that we can't use `if is_registered` (currently used on event-detail) to distinguish between users who are registering for the first time and users who are already registered and just sending a message. Once the user reaches registration-confirmed, is_registered would be true in both cases. However perhaps the same is true for the status message.

**Comment by nickolashe** [comment]
broadly speaking, this is a giant piece of confusion for me with the whole coordinator / registered / invited / notified bonanza. please see my other message regarding this being a perfect candidate for a use case specs.

**Comment by dannypernik** [comment]
@nickolashe I've done three happy paths for the event-detail template
https://docs.google.com/spreadsheets/d/15mnrkl4Rc5dsFX8VAGOeuPPfCQTPHyOWV1SVwkXIqNQ/edit?usp=sharing

**Comment by nickolashe** [comment]
dup of #529
