### ISSUE TITLE
event-detail:  If volunteer is invited but has not signed up, email is not listed. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#546]
Emails are copied but not listed. 

![image](https://user-images.githubusercontent.com/26234440/31802772-9c3ea9fe-b515-11e7-8d85-796ff58b1e06.png)

**Comment by nickolashe** [comment]
@dannypernik could you also remember to change the milestone when modifying an issue to make sure it is under my radar

**Comment by dannypernik** [comment]
@nickolashe noted

**Comment by dannypernik** [comment]
@nickolashe should we also include this in the Bike Austin epic since it's related to the copy/paste email button?

**Comment by nickolashe** [comment]
sounds good

**Comment by dannypernik** [comment]
PR #878
