### ISSUE TITLE
Back buttons needed throughout the dropdowns of the events. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#547]
![image](https://user-images.githubusercontent.com/26234440/31802869-3a969666-b516-11e7-934c-ba7a7b09f299.png)

**Comment by dannypernik** [comment]
@MaxTattenbach I don't understand. A back button back to profile?

**Comment by MaxTattenbach** [comment]
Lets do a run but there seems to be several places were a back to profile
button would be useful.

**Comment by dannypernik** [comment]
Ok

**Comment by dannypernik** [comment]
@MaxTattenbach I've added a "Back to profile" link on event-detail but note that people are coming from different pages in different scenarios. An admin will come from org-admin while a volunteer will come from upcoming-events if a new event and profile if they are already registered. Do you want a link to profile on event-detail? I'm fine with it either way.

**Comment by nickolashe** [comment]
perfect candidate for an exact use case spec run

**Comment by dannypernik** [comment]
I've added the happy path use cases for event-detail to the spreadsheet:
https://docs.google.com/spreadsheets/d/15mnrkl4Rc5dsFX8VAGOeuPPfCQTPHyOWV1SVwkXIqNQ/edit?usp=sharing

**Comment by dannypernik** [comment]
back button added on event-detail
