### ISSUE TITLE
Manual Tracking:  On Iphone 4 plugins if calendar not working.   

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#549]
Gala was also unable to view admins to submit hours.

**Comment by dannypernik** [comment]
@nickolashe @MaxTattenbach :/ not sure what to do about this one. I don't have a way to test it and haven't found any solutions based on a preliminary search.

**Comment by nickolashe** [comment]
not sure either

**Comment by dannypernik** [comment]
Mobile browsers have native date and time pickers for input type="date" or "time". Unfortunately, Chrome and Opera desktop browsers have undesirable interface for these input types, and it's not clear how to disable it entirely. Unfortunately, for the time being @MaxTattenbach and I have agreed not to worry about date and time pickers on iPhone 4. Our custom pickers are working fine on newer iPhones.
