### ISSUE TITLE
event-detail: show if event is public or private

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#558]

**Comment by dannypernik** [comment]
@nickolashe added "(Public/private) event" to event-detail in `event_privacy` branch. Variable needs to be included there.

**Comment by nickolashe** [comment]
event model already contains a field `is_public`:
https://github.com/opencurrents/opencurrents/blob/develop/openCurrents/models.py#L141

**Comment by nickolashe** [comment]
event-detail is a DetailView and the context object name is `event`:
https://github.com/opencurrents/opencurrents/blob/develop/openCurrents/views.py#L1849-L1851

**Comment by dannypernik** [comment]
got it, thanks
