### ISSUE TITLE
Time-Tracker: Double error message display.  Lets keep the one below. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#561]
![image](https://user-images.githubusercontent.com/26234440/31854325-ba236930-b65c-11e7-8157-172d93374ce6.png)

**Comment by dannypernik** [comment]
@MaxTattenbach it will be helpful if you can include the URL in your screenshots. Is this in openc.herokuapp?

**Comment by dannypernik** [comment]
nvm I found it

**Comment by nickolashe** [comment]
what was the issue?
