### ISSUE TITLE
Profile: Eliminate Parenthesis on Dollars

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#562]
![image](https://user-images.githubusercontent.com/26234440/31854345-3dc4acae-b65d-11e7-8d6a-758927503803.png)

**Comment by dannypernik** [comment]
@MaxTattenbach this shows that these are hardcoded numbers, not yet variables. @nickolashe we don't have var names for dollars yet, correct?

**Comment by nickolashe** [comment]
dollars are WIP
