### ISSUE TITLE
Redeem Currents:  Display text after some one writes in the text box - I don't have proof-of-purchase

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#564]
Note after selecting "I don't have proof-of-puchase " it should deplay in the main screen after cbefore clicking "Next"
![image](https://user-images.githubusercontent.com/26234440/31854446-22573214-b65f-11e7-8aac-5e801e140ea3.png)

**Comment by dannypernik** [comment]
pushed to develop
