### ISSUE TITLE
Offer:  Current logo out of proportion in Internet explorer

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#565]
![image](https://user-images.githubusercontent.com/26234440/31856725-ed649b26-b68d-11e7-9530-60fcae7e157b.png)

**Comment by dannypernik** [comment]
@MaxTattenbach we're just requesting a really large share, right?

**Comment by dannypernik** [comment]
@MaxTattenbach can you try clearing your cache on IE and rechecking this page? Here's instructions to clear cache on IE: https://kb.wisc.edu/page.php?id=15141

**Comment by dannypernik** [comment]
fixed in develop
