### ISSUE TITLE
offer: When Confirming offer the the percentage does not match the set offers input. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#566]
The offer was with 60% Current share and still displays as 25%.  This was with Internet Explorer browser 

![image](https://user-images.githubusercontent.com/26234440/31856736-50afc05c-b68e-11e7-8d6e-7e2fb612e35b.png)

**Comment by MaxTattenbach** [comment]
It does display correctly in the Biz Admin Profil
![image](https://user-images.githubusercontent.com/26234440/31856756-a923df7a-b68e-11e7-9915-289807e604a0.png)

**Comment by dannypernik** [comment]
@MaxTattenbach @nickolashe not sure how to troubleshoot IE-related issues, as I can't reproduce them. Is this error only happening on IE and not chrome or FF?

**Comment by nickolashe** [comment]
@dannypernik sounds like a problem with input aggregation again?

**Comment by nickolashe** [comment]
@dannypernik i think i've seen a commit related to this recently?

**Comment by dannypernik** [comment]
@nickolashe I had made a similar change to the redeem-offer page. Just pushed to develop
