### ISSUE TITLE
Profile: After redeeming Offers Current Balance doesn't decrease and pending dollars doesn't go down

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#567]

**Comment by nickolashe** [comment]
pending dollars should go up i believe, and yes this is not implemented yet

**Comment by nickolashe** [comment]
i think decreasing current balance is debatable since the offer has not been accepted yet

**Comment by nickolashe** [comment]
agreed on decrementing available currents balance

**Comment by MaxTattenbach** [comment]
Correct Nicko. Current balance goes down and pending USD up!

**Comment by dannypernik** [comment]
@nickolashe just to confirm, we decided that when user redeems an offer, Currents available goes down and Pending dollars goes up? And if offer is declined, Currents available increases while Pending dollars decreases.
