### ISSUE TITLE
Chash Out:  Change message

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#568]
If you Confirm the "Send Dollars" you will receive an email in the next 48 hours from Dwolla, our ACH provider. In one easy step, your cash will be in your bank account.   Let's keep changing this world one Current at a time. 

![image](https://user-images.githubusercontent.com/26234440/31856802-a9ac3b3e-b690-11e7-877a-b379ae1e8fdc.png)

**Comment by dannypernik** [comment]
<img width="815" alt="screen shot 2017-10-30 at 3 28 13 pm" src="https://user-images.githubusercontent.com/3347095/32193975-fac5c2f4-bd86-11e7-8cd9-a3ef125ec8a8.png">

**Comment by nickolashe** [comment]
is this in develop?

**Comment by nickolashe** [comment]
@dannypernik can you please remember to include a brief message of where things can be found

**Comment by dannypernik** [comment]
@nickolashe yea sorry. this is in develop.
