### ISSUE TITLE
Chash Out: Amount of Cash needs to be displayed in the confirmation. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#569]
I suggest this always equal the total amount in the balance.  - Change button to "Send Dollars" rather than "Send Cash". 

![image](https://user-images.githubusercontent.com/26234440/31856835-d2ad52c4-b691-11e7-916a-0659c1414276.png)

**Comment by dannypernik** [comment]
yep. changed 'cash' to 'dollars' and made it clear full balance will be transferred.

**Comment by dannypernik** [comment]
Realized Max wants to display the total dollars being cashed out in popup.

**Comment by dannypernik** [comment]
Pushed to develop
