### ISSUE TITLE
Redeem-Offers:  Not working on Cel Phone. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#571]
Going from Add Receipt to Record price on Safari is not possible.

**Comment by dannypernik** [comment]
@MaxTattenbach please edit these titles to match the name of the page, so redeem-offers instead of Redeem Offers. This will allow us to search for issues more easily.

**Comment by MaxTattenbach** [comment]
Danny - they all match page titles. Next time i'll make sure to include
hyphens. Thanks!

**Comment by dannypernik** [comment]
@MaxTattenbach thanks. Nicko also mentioned one that you named based on a description of a popup. Please use the page URL for popup-related issues too.

**Comment by MaxTattenbach** [comment]
Got it!

Max Tattenbach
Co-creator
www.opencurrents.com

**Comment by dannypernik** [comment]
fixed in develop
