### ISSUE TITLE
profile:  Change Message: Display "Date, $ Amount and Currents"

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#575]
For Example, if an offer was redeemed with Fast Folks.  Current Share 50% for 15 dollars. 
Then message should display:

10/15 - you redeemed $7.5 for 0.75C with Fast Folks  

![image](https://user-images.githubusercontent.com/26234440/31856933-3ce20204-b695-11e7-8810-85b33989d26b.png)

**Comment by dannypernik** [comment]
@MaxTattenbach how about: 10/15 - Fast folks accepted C0.75 for $7.50
By the way, the reason I didn't use this language in the first place is that if redemption is pending, the business has not actually accepted the transaction so this statement is not true. We could say 'Fast Folks accepts C0.75 for $7.50'?

**Comment by nickolashe** [comment]
i think lets show the following:
when status is pending: Fast Folks offers $7.50 for C0.75
when status is approved: Fast folks accepted C0.75 for $7.50

**Comment by dannypernik** [comment]
@nickolashe received "Could not convert string to float" error when trying to copy logic from biz-admin page. Pushed to issue#575 branch:

![Uploading Screen Shot 2017-10-25 at 4.55.53 PM.png…]()

**Comment by dannypernik** [comment]
I commented out the variables to avoid the error

**Comment by nickolashe** [comment]
@dannypernik so `disc` is undefined here as we discussed. can you write what you are looking for in terms of the existing variables?

**Comment by nickolashe** [comment]
format the date of redemption
