### ISSUE TITLE
marketplace:  Remaining offers on market place should go down as offers get redeemed

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#576]
![image](https://user-images.githubusercontent.com/26234440/31856974-c1003d84-b696-11e7-879e-ba681985218f.png)
![image](https://user-images.githubusercontent.com/26234440/31856977-d0f7fb64-b696-11e7-9b6d-cb962d09a6ab.png)

**Comment by dannypernik** [comment]
And removed when 0 remain for a given month
