### ISSUE TITLE
Redeem-Currents: Confirm Exchange - Amount should change according to percentage of price of good/service

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#577]
Note for this example Fast Folks is accepting 60% Current Share and the Service is $100. Then confirmation message should be 6 Currents for $60, not 10 C for $100. 

![image](https://user-images.githubusercontent.com/26234440/31857022-e8119c1e-b697-11e7-8667-a9ed469d1b59.png)

**Comment by nickolashe** [comment]
@dannypernik looks like the conversion of inputs is incorrect here

**Comment by dannypernik** [comment]
Ah good catch @MaxTattenbach . fixed
