### ISSUE TITLE
Confirm Exchange: After Confrim Exchange Status message should appear and User should be redirected to profile

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#578]
Currently - nothing happens after clicking confirm

![image](https://user-images.githubusercontent.com/26234440/31857050-acc8d7b6-b698-11e7-9d1c-3db7e8f0e77f.png)

**Comment by nickolashe** [comment]
@MaxTattenbach you must have went the route of other PoP (see issue #540). Confirm does work the main route (uploading receipt).

**Comment by nickolashe** [comment]
@MaxTattenbach can you verify it works for you please

**Comment by dannypernik** [comment]
@MaxTattenbach

**Comment by MaxTattenbach** [comment]
@nickolashe, It works uploading a receipt.  It seems doesn't work when only text is uploaded
