### ISSUE TITLE
Redeem Currents: Upload Receipt - Change message

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#579]
Change Text to: To exchange Currents for dollars with Fast Folks, upload your receipt as proof of purchase. Receipts are the best proof of purchase others such as an image of your bank statement, may or may not be accepted. Why do I pay full price?

Upload Receipt/Proof of Purchase

 I don't have proof of purchase. 

![image](https://user-images.githubusercontent.com/26234440/31857072-758eed5c-b699-11e7-9980-31c4fab69f3d.png)

**Comment by dannypernik** [comment]
@MaxTattenbach changed the title to "Upload receipt or proof of purchase" and changed "Why am I paying full price" to "why do I pay full price". I don't think the additional sentence in the text is necessary. If you're ok with this, you can close the issue.
