### ISSUE TITLE
opencurrents logo in header logs you out

### ISSUE THREAD

**Issue by everydaydaniel** [opencurrents/opencurrents#58]
I recommend having the header link to the user profile. It seems to log you out if you click it, makes it a little useless to have.

**Comment by nickolashe** [comment]
@everydaydaniel I agree, can you please make the change?

**Comment by dannypernik** [comment]
@nickolashe @everydaydaniel I've added the following logic to check for admin status, let me know if this will work with all templates:
`{% if orgid %}
      <a href="{% url 'openCurrents:admin-profile' %}">
      {% else %}
      <a href="{% url 'openCurrents:profile' %}">
      {% endif %}`

**Comment by nickolashe** [comment]
thats correct
