### ISSUE TITLE
Redeem Currents: Upload Receipt - display status message if nothing is uploaded or description added. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#580]
The message could be:  It's unlikely "XX" will accept Currents without any proof of purchase or description of the transaction. 
![image](https://user-images.githubusercontent.com/26234440/31857111-8f79bca0-b69a-11e7-8e5c-e919998fd359.png)

**Comment by dannypernik** [comment]
@nickolashe should status message issues such as this one be assigned to you in General MVP?

**Comment by nickolashe** [comment]
do we see this message appearing before or after submitting the form?

**Comment by dannypernik** [comment]
@nickolashe I see it as occurring after submitting.

**Comment by nickolashe** [comment]
ok, are they aware of the notion one way or another prior to submitting?

**Comment by dannypernik** [comment]
I think they should expect to need to do one or the other. However we could disable "Next" buttons in both offer and redeem-currents until input is made if we want to.

**Comment by nickolashe** [comment]
i think that would be a good idea if its not to involved

**Comment by dannypernik** [comment]
I'm having trouble getting disabled/enabled to work properly. Biggest problem is that disabled property on Next button was not preventing the page from sliding to next page when clicked. I tried adding an if statement to only slide when button was enabled, but now it won't slide under either condition. Also I've not had success in adding disabled field back to button if text or image is removed.

@nickolashe can we just go with a status message for this one?

**Comment by nickolashe** [comment]
post-submit that is? sounds good to me

**Comment by nickolashe** [comment]
@danny can you transfer to the use case doc pls

**Comment by dannypernik** [comment]
done. A comment for you there as well on redeem-currents happy path

**Comment by dannypernik** [comment]
Transferred to use case doc and to General MVP
