### ISSUE TITLE
redeem-currents: provide textbox as alternative PoP

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#581]
@dannypernik @nickolashe - we should decide if we want to inhibit going forward from add receipt if neither a receipt or description are added.   I think best to make it necessary to either upload receipt or to add a description.   If this is the case just adding a description should allow you to confirm the offer. 

![image](https://user-images.githubusercontent.com/26234440/31857134-3aaaa09e-b69b-11e7-9f22-b84b381dc3cf.png)

**Comment by nickolashe** [comment]
@dannypernik can we start by adding a textbox to the form?

**Comment by dannypernik** [comment]
@nickolashe this is a duplicate of an issue I've closed. Textbox is `{{ form.redeem_no_proof }}`. Please close if you're good with this.

**Comment by nickolashe** [comment]
got it. is it in develop?

**Comment by nickolashe** [comment]
please close if so

**Comment by dannypernik** [comment]
@nickolashe does the input automatically get submitted to the backend if `form.redeem_no_proof` is defined in forms.py and added to HTML? Or do you have to do something else with it?

**Comment by nickolashe** [comment]
i need to make sure it is saved, yes

**Comment by dannypernik** [comment]
Ok, over to you.

**Comment by nickolashe** [comment]
i don't actually, so reopening
