### ISSUE TITLE
Home: Amend messaging on sign-up for clarity and distinction between users, orgs and individuals. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#601]

**Comment by dannypernik** [comment]
@MaxTattenbach check out https://opencdesign.herokuapp.com and scroll down to the form at the bottom of the page. See if the buttons there do the trick in your opinion.

**Comment by MaxTattenbach** [comment]
Unable to access opencdesign.herokuapp.com.   I am getting an error.

Max Tattenbach
Co-creator
www.opencurrents.com

**Comment by dannypernik** [comment]
@MaxTattenbach it's working for me, not sure the problem

**Comment by dannypernik** [comment]
Ready in home_signup branch (PR #759)

**Comment by dannypernik** [comment]
Closing PR in favor of links directly to forms on various landing pages
