### ISSUE TITLE
invite-volunteers: Preview email

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#609]
Let admins see what content will be sent in their email invite

**Comment by dannypernik** [comment]
<img width="728" alt="screen shot 2017-10-29 at 11 10 01 pm" src="https://user-images.githubusercontent.com/3347095/32154408-82ec5a50-bcfe-11e7-8f89-19200867c122.png">
<img width="719" alt="screen shot 2017-10-29 at 11 10 24 pm" src="https://user-images.githubusercontent.com/3347095/32154410-84872a3e-bcfe-11e7-8028-1a48c6260940.png">

@nickolashe @MaxTattenbach Different email previews based on whether admin is inviting volunteers to record hours or to an event. Note that variables for event date, time, and location are not currently available in this template (at least as far as I'm aware) but I think this works fine for MVP purposes.

**Comment by dannypernik** [comment]
Included in personal_message branch

**Comment by nickolashe** [comment]
should we move to General mvp?

**Comment by dannypernik** [comment]
@nickolashe I don't believe there's anything for you to do on the backend for this one, unless you want to add variables for event date, time, and location. I don't think it's necessary unless the vars are already accessible.

**Comment by nickolashe** [comment]
i am ok with the way it is
