### ISSUE TITLE
org-admin: Can we delete this status message div?

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#611]
https://github.com/opencurrents/opencurrents/blob/f09278250f702ed0272b05a36c6333840eb204a2/openCurrents/templates/org-admin.html#L16

@nickolashe Looks like we're using conditional statements below it to display the status messages. Just want to make sure there's not some case where we use it.

**Comment by nickolashe** [comment]
@dannypernik i am not seeing any conditionals, mind linking me to those directly?

**Comment by dannypernik** [comment]
https://github.com/opencurrents/opencurrents/blob/f09278250f702ed0272b05a36c6333840eb204a2/openCurrents/templates/org-admin.html#L15-L52

**Comment by dannypernik** [comment]
@nickolashe am I good to delete this?

**Comment by nickolashe** [comment]
yes

**Comment by dannypernik** [comment]
Ready in layouts branch (PR #629)
