### ISSUE TITLE
event-detail: Send confirmation email to volunteer when registered to event

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#613]
Template name: volunteer-confirmation
<img width="629" alt="screen shot 2017-10-31 at 6 37 30 pm" src="https://user-images.githubusercontent.com/3347095/32253770-ab3d7ba2-be6a-11e7-8cab-814fe12adf7e.png">

Here are the variables we need for this template. I modified the invite-volunteer-event-existing template since it had many of the same variables. adding EVENT_DESCRIPTION and EVENT_ID to that list. (also note that the text of button is not EVENT_ID, i just put it there so you know it's part of the URL)

**Comment by nickolashe** [comment]
ORG_NAME = event.project.org.name
EVENT_ID = event.id
EVENT_TITLE = event.project.name
EVENT_START_TIME = event.datetime_start
EVENT_END_TIME = event.datetime_end
EVENT_LOCATION = event.location
EVENT_DESCRIPTION = event.description
ADMIN_FIRSTNAME = event.coordinator.first_name
ADMIN_LASTNAME = event.coordinator.last_name

(see Event model in models.py)

**Comment by dannypernik** [comment]
PR #654 needs to be tested on master

**Comment by dannypernik** [comment]
@nickolashe can you look at the merge conflict on PR #654? It looks like all of the lines from 2355 to 2368 may need to be included but I can't be sure.

**Comment by dannypernik** [comment]
@nickolashe bump

**Comment by nickolashe** [comment]
i thought this was merged long time ago?

**Comment by dannypernik** [comment]
Just double checked and it appears not.

**Comment by nickolashe** [comment]
i am not sure it makes sense to try resolve the conflict at this point, but instead implement the change again

**Comment by dannypernik** [comment]
PR #860

**Comment by MaxTattenbach** [comment]
@dannypernik @nickolashe I am going to close this.  Users are getting confirmation email after signing up for event.
