### ISSUE TITLE
Upcoming Events:  Display no Events when none are existent. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#619]
![image](https://user-images.githubusercontent.com/26234440/32301280-52abeb10-bf2b-11e7-8db0-bdeb661f518a.png)

**Comment by dannypernik** [comment]
@nickolashe I'd like to use `{% empty %}` with this for loop:
https://github.com/opencurrents/opencurrents/blob/develop/openCurrents/templates/upcoming-events.html#L108
but am I correct in thinking if there are events with event_type = "MN", the `{% empty %}` message will not display?

Can we use `{% for event in events_group_upcoming %}` (as in org-admin)?

**Comment by dannypernik** [comment]
@nickolashe on `volunteer-opportunities.html` I'd like to only display "See upcoming events" button if upcoming events are present. Perhaps we can use `{% if events_group_upcoming %}` variable that's used in org-admin?

**Comment by dannypernik** [comment]
@nickolashe

**Comment by nickolashe** [comment]
@dannypernik `{% if events %}`

**Comment by nickolashe** [comment]
consult the view for any existing context vars

**Comment by nickolashe** [comment]
in this case its a ListView and the context object name is `events`:
https://github.com/opencurrents/opencurrents/blob/develop/openCurrents/views.py#L1971

**Comment by dannypernik** [comment]
@nickolashe am I correct in thinking `{% if events %}` will be true if manually tracked records exist? I'm interested in checking for group events.

**Comment by nickolashe** [comment]
i would think there can't be future manual events? does not hurt to impose the filter explicitly. could you create an issue @dannypernik? i don't think its blocking however.

**Comment by dannypernik** [comment]
True. ok creating issue #886. However, `events` isn't accessible to volunteer-opportunities template, it's currently a hard-coded list of initial nonprofits. Wish I knew what needed to be done beyond `context_object_name` to get variable working.

**Comment by nickolashe** [comment]
get_query_set needs to be defined. See UpcomingEventsView

**Comment by dannypernik** [comment]
@MaxTattenbach "See upcoming events" button should only display on volunteer-opportunities.html if upcoming events are present. (Access vol-opps by clicking Volunteer on profile then View opportunities)

**Comment by MaxTattenbach** [comment]
@dannypernik  functionality is working and will close the issue.   Although, I personally think it's a bad idea of deleting buttons because then when users check out the site they wouldn't know that you can actually find events on openCurrents' site.   I believe its better to have a popup displaying when no events are present.   Post MVP.
