### ISSUE TITLE
Other opportunities: Add new pop-up after clicking other opportunities with logos and link to volunteering site

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#625]
Logos: to be linked to their Austin section for volunteering.   Give Pulse, Volunteer Match, Volunteer Hub.

Suggested text:
In the following sites, you can access many opportunities to volunteer with Austin charities.  Once you volunteer, let the volunteer coordinator know that you want to earn Currents for the time you volunteered.  To request Currents after volunteering go to "I already volunteer"  in record hours.  Remember you can always donate back the value of your Currents to your favorite nonprofit when redeeming offers which helps them fundraise. 

- Let's leave this last sentence because it will get folks telling there volunteer coordinator about it.

**Comment by dannypernik** [comment]
Designed in time_tracker_update (#781)
