### ISSUE TITLE
Profile:  Create Pop-up for non happy path when cashing out.

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#633]
Suggested Text:  "Exchange your Currents with participating vendors in the marketplace to earn USD, you must have a positive USD balance to cash out"    Got it (button)

![image](https://user-images.githubusercontent.com/26234440/32417430-47591336-c21f-11e7-8456-08474d1d5420.png)

**Comment by dannypernik** [comment]
Has been designed and is covered by issue #596
