### ISSUE TITLE
marketplace: Limit offers and to decide what happens to an offer that has been fully redeemed in the market place

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#635]
I suggest we leave it in the marketplace for the meantime as 0/"X"  available and if someone clicks it alert message displays. 

I've added the unhappy path in spec for redemptions

**Comment by dannypernik** [comment]
IMO an offer that has reached its limit for the month should not be displayed in the marketplace. It will be displayed at the beginning of the next month when its monthly number available resets.

**Comment by MaxTattenbach** [comment]
I think rather than disappearing offer freezing the redeem button is
better.

**Comment by nickolashe** [comment]
@MaxTattenbach moving to "To be tested"
