### ISSUE TITLE
time-tracker: Send emails to admin and bizdev@opencurrents.com when user records hours with non-registered NPF

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#637]
Row 7 of time-tracker sheet: https://docs.google.com/spreadsheets/d/15mnrkl4Rc5dsFX8VAGOeuPPfCQTPHyOWV1SVwkXIqNQ/edit?usp=sharing

"Request Currents from another organization or admin" button drops down extra fields: Organization name, Admin name, Admin email

**Comment by dannypernik** [comment]
Designed in time_tracker_update branch and merged into layouts

**Comment by nickolashe** [comment]
@MaxTattenbach @dannypernik you can this one a test now

**Comment by MaxTattenbach** [comment]
I am unable to submit  the form when user records hours with non-registered NPF.  Error: Admin Field required

![image](https://user-images.githubusercontent.com/26234440/33965360-31f61f3c-e021-11e7-8dc6-f349d655cf99.png)

**Comment by dannypernik** [comment]
@MaxTattenbach I assume you tested this? Given that we're only requiring one successful test before closing, let's leave a comment "Working" or something similar when closing issues.

**Comment by MaxTattenbach** [comment]
@dannypernik I don't think I closed it.  We were waiting for PR before testing.

**Comment by MaxTattenbach** [comment]
I am unable to submit forms it says that it can only submit hours for up to 2 weeks in the past. 

![image](https://user-images.githubusercontent.com/26234440/34276975-78023a58-e669-11e7-9809-6826faebc978.png)

**Comment by nickolashe** [comment]
pushed a fix, can you try again @MaxTattenbach

**Comment by MaxTattenbach** [comment]
@nickolashe its working now.
