### ISSUE TITLE
User attempts to redeem but does not have enough currents

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#641]
- if less than current share allow to redeem that many
- if no currents return an error

**Comment by dannypernik** [comment]
@nickolashe perhaps we should show an error on marketplace if user clicks 'redeem' and doesn't have Currents? Instead of displaying error on redeem-currents?

**Comment by MaxTattenbach** [comment]
Agree with Danny.  I think the error should be displayed in Market Place.


Max Tattenbach
Co-creator
www.opencurrents.com
