### ISSUE TITLE
time-tracker: Volunteer requests Currents with non registered admin of a registered NPF

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#656]

**Comment by MaxTattenbach** [comment]
@tevtonez note that biz dev is not getting email only Admin.  Both biz dev and Admin most receive email.

**Comment by MaxTattenbach** [comment]
@tevtonez same issue with password of new admin which is being created

**Comment by dannypernik** [comment]
@MaxTattenbach could you give more detail here? I don't understand

**Comment by MaxTattenbach** [comment]
This is working now.
