### ISSUE TITLE
time-tracker: Volunteer requests Currents with an existing non-approved admin through "Someone else"

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#662]

**Comment by MaxTattenbach** [comment]
@tevtonez  both admin and biz dev are getting the email, which seems like form is being submitted.  Although this shows up on the screen.  Pending Currents are not being created. 

![image](https://user-images.githubusercontent.com/26234440/34287053-535b280e-e6aa-11e7-8942-c7271cc97b7a.png)

**Comment by tevtonez** [comment]
@MaxTattenbach I cannot reproduce it with the latest code from develop branch. Let's meet and see exact steps to reproduce. Thanks!

**Comment by MaxTattenbach** [comment]
This is seems be working.
