### ISSUE TITLE
time-tracker: Volunteer requests Currents via "someone else" and admin already exists and admin has admin privileges

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#663]

**Comment by MaxTattenbach** [comment]
@tevtonez error message indicating that admin already is affiliated is missing

**Comment by tevtonez** [comment]
@MaxTattenbach after e16a108 commit it says this:
![screenshot 2017-12-22 16 18 52](https://user-images.githubusercontent.com/343347/34303024-e26aada6-e733-11e7-8256-3a3a628074ac.png)

is it ok, or it should say 'The coordinator is already affiliated with an existing organization.' ?

**Comment by dannypernik** [comment]
@MaxTattenbach I had initially told @tevtonez the status message shown in the screenshot above. If you'd like him to change it to your suggestion I'm fine with that too

**Comment by tevtonez** [comment]
I changed the pipeline 'to be tested' to bring it up to your radar.

**Comment by MaxTattenbach** [comment]
@tevtonez   Thanks!
