### ISSUE TITLE
time-tracker: Volunteer requests Currents via "Request Currents from another non-profit" and NPF admin already exists and is present in NPF's admin group

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#664]

**Comment by MaxTattenbach** [comment]
@tevtonez There should be an error message indicating to volunteer that admin is already registered with another organization.    

Email is not been sent to biz dev nor existing admin which is correct functionality.  Missing error message

**Comment by tevtonez** [comment]
@MaxTattenbach this e16a108 commit should fix it
![screenshot 2017-12-22 16 28 48](https://user-images.githubusercontent.com/343347/34303382-4d41cc12-e735-11e7-83c4-5dd7b458fbdd.png)

**Comment by MaxTattenbach** [comment]
@maxtattenbach to test with email associated with biz.   Test successful with email associated with another npf

**Comment by dannypernik** [comment]
@MaxTattenbach are you saying there's another case you'll be testing here? Just sending a message to keep this on your radar. I can also test if you like. I know we decided "Tested and working" was a bucket for issues we want to test twice.

**Comment by MaxTattenbach** [comment]
@dannypernik it was a note for me as I couldn't finish testing due to lack of access to DB

**Comment by MaxTattenbach** [comment]
@tevtonez @nickolashe This is working now will close.
