### ISSUE TITLE
Org Admin Profile Additions

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#669]

**Comment by nickolashe** [comment]
@tevtonez @dannypernik @MaxTattenbach what is the status of this epic now? can the implementation and tests be considered done?

**Comment by tevtonez** [comment]
@nickolashe I believe yes.

**Comment by MaxTattenbach** [comment]
I'll move to to be tested.

**Comment by MaxTattenbach** [comment]
@tevtonez   Functionality in Org Admin Profile Additions is working correctly.
