### ISSUE TITLE
marketplace: Change so that the most recent posted offers are shown first.  

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#674]
Note the 25% for all product and services was the most recently posted offer

![image](https://user-images.githubusercontent.com/26234440/32863113-067372fe-ca20-11e7-80b1-eb54744f76b0.png)

**Comment by nickolashe** [comment]
@MaxTattenbach moved to "To be tested" pipeline

**Comment by MaxTattenbach** [comment]
Looks good!

Max Tattenbach
Co-creator
www.opencurrents.com

**Comment by nickolashe** [comment]
@MaxTattenbach do you know how to close issues?

**Comment by MaxTattenbach** [comment]
Thanks, @nickolashe Nicko I just learned how to close issues this morning.   Seems that we no longer have blockers and are good to go, let's discuss in our call today in the morning.
