### ISSUE TITLE
profile: Pending Balance in profile should illustrate transaction minus fees. It currently isn't. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#676]
Note that in the profile after completing a transaction $35 were passed to pending dollars rather than the $31.5.  Note there was $5 previous in the Pending balance that's why it's adding up to 40. 

![image](https://user-images.githubusercontent.com/26234440/32864030-36835970-ca23-11e7-82ee-78d7579d449e.png)

![image](https://user-images.githubusercontent.com/26234440/32864454-dc39518e-ca24-11e7-8f43-922efe842027.png)

**Comment by nickolashe** [comment]
@MaxTattenbach moved to "To be tested" pipeline

**Comment by MaxTattenbach** [comment]
@nickolashe - Balance is adding up correctly. 

@dannypernik @nickolashe we just have to decide if we want to illustrate full amounts or amounts minus fees in "my reedemed offeres".  Currently it shows full amount which I am fine with.

**Comment by nickolashe** [comment]
i think for consistency we should change that one as well. what do you guys think?

**Comment by dannypernik** [comment]
@nickolashe the wording in 'My redeemed offers' is "[biz] offers $Y for X Currents" or "[biz] accepted X Currents for $Y". I think it makes more sense to use the amount minus fees so that available dollars equals the sum of the approvals (at least before the first cashout). In this case, I think we'd want to change the language to "You requested $Z for X Currents from [biz]" or "You received $Z for X Currents from [biz]". (Z = amount minus fees)

**Comment by nickolashe** [comment]
ok agreed

**Comment by MaxTattenbach** [comment]
@dannypernik @nickolashe.  how about "You will receive $Z for X Currents from [Biz]."

**Comment by nickolashe** [comment]
can we retest this one

**Comment by dannypernik** [comment]
Working. I changed the offer_redeemed text on profile, as it should say "You received $X for oC Y from Biz" not "Biz received $X for oC Y". @MaxTattenbach want to double check and close?

**Comment by MaxTattenbach** [comment]
@nickolashe  note that the $ amount is now displaying the net amount but the Current amount is incorrect.  

For example in the redemption of Dec 13, there were 17.5 Currents redeemed.  It should state the Net amount of $ with the total amount of Currents given to the business. 

It should say.

You requested $157.50 for 17.5 C  from openCurrents

![image](https://user-images.githubusercontent.com/26234440/33962089-f4ee4f84-e015-11e7-895a-0dd5cdacd9a4.png)

**Comment by MaxTattenbach** [comment]
@nickolashe working good and balances adding up correctly.
