### ISSUE TITLE
biz-admin: Messaging in Pending transactions is not reflecting proper amounts and not adding up to pending balance

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#679]
The error happens when there is a partial redemption of the offer.  For example in the last transaction listed the amount paid by the volunteer was $1,000, but he only had 5 Currents.    

The message will only work consistently if the amounts are pulled directly from the transaction or "My Redeemed Offers" from Profile rather than assuming that all offer is completely redeemed. 

![image](https://user-images.githubusercontent.com/26234440/32865942-f4fdb9d4-ca2a-11e7-8081-f3fb4e02c788.png)

**Comment by nickolashe** [comment]
ah yes, good catch. easy fix.

**Comment by nickolashe** [comment]
@MaxTattenbach pls confirm partial redemption requests are listed correctly

**Comment by MaxTattenbach** [comment]
Nicko these are not listing correctly in the biz admin (it assumes
redemption is complete), although they are listed correctly in profile.

Max

Max Tattenbach
Co-creator
www.opencurrents.com

**Comment by nickolashe** [comment]
got it, thanks

**Comment by MaxTattenbach** [comment]
@nickolashe  ok to close.  It's showing it correctly.
