### ISSUE TITLE
Biz Admin:  Receipt and Text - from transaction doesn't seem to be displaying along to the transaction. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#680]
When clicking view receipt it seems to be hard-coded, text or no [icture not passing along. 

![image](https://user-images.githubusercontent.com/26234440/32866634-50d7542e-ca2e-11e7-9fb6-c8150ddcc394.png)

**Comment by nickolashe** [comment]
dup #542
