### ISSUE TITLE
Invite Volunteers

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#707]

**Comment by tevtonez** [comment]
please, note that the tests are failing in this branch because they were fixed in another branch with this commit: cce27dd

**Comment by nickolashe** [comment]
@tevtonez @dannypernik @MaxTattenbach what is the status of this epic now? can the implementation and tests be considered done?

**Comment by MaxTattenbach** [comment]
@nickolashe I can do a round of testing for these scenarios, I'll move to the  To be Tested bucket.

**Comment by MaxTattenbach** [comment]
@nickolashe can't currently test as email aren't working.

**Comment by MaxTattenbach** [comment]
@tevtonez @nickolashe  closed the vast majority of the issues in this epic.   Moved to needs work until we address  #720, #721, #722, #723.

**Comment by tevtonez** [comment]
@MaxTattenbach 
Thanks for pointing it out! I didn't get the idea of these cases but now it makes sense to me. 
Code is updated, and will be ready to test after PR.

**Comment by nickolashe** [comment]
@MaxTattenbach @tevtonez this has been merged to develop. do we need to retest #720-#723?

**Comment by tevtonez** [comment]
@nickolashe @MaxTattenbach I don't think we have to, but I believe it's always good to have an extra round of testing if possible.

**Comment by MaxTattenbach** [comment]
@tevtonez @nickolashe I'll close this epic.  Functionality has been tested and is working properly.
