### ISSUE TITLE
live-dashboard add volunteers to Registered list even if email already exists in system

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#71]

**Comment by nickolashe** [comment]
@dannypernik did you say that this eventually worked for you?

**Comment by dannypernik** [comment]
No but possible that it's only preventing the logged in user from adding
themselves.

**Comment by nickolashe** [comment]
Ok, because I am able to add new users

**Comment by nickolashe** [comment]
are we ok with closing this?
