### ISSUE TITLE
invite-volunteers: Npf admin individually invites volunteers with openCurrents account (non-event based) without personal message

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#720]
Unhappy path

**Comment by MaxTattenbach** [comment]
@tevtonez @nickolashe @dannypernik   I believe that when and NPF invites volunteers with the openCurrents account (non-event based) there should be no email sent to volunteer. 

I tried with both user with password and user w/out a password and both are getting the emails.  What makes more sense is if volunteer is to send emails to those who don't have a password created.  If user and password then don't invite if non event based.

**Comment by tevtonez** [comment]
@MaxTattenbach @nickolashe 
after commit d962236 all volunteers, registered in the system, won't receive email if they were invited non-event based.
@nickolashe is there a way to distinguish volunteer users with and w/o passwords?
