### ISSUE TITLE
Approve Hours

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#732]
Implemented

**Comment by nickolashe** [comment]
@tevtonez @dannypernik @MaxTattenbach what is the status of this epic now? can the implementation and tests be considered done?

**Comment by MaxTattenbach** [comment]
I'll move to be tested bucket and can run testing. 

@tevtonez @nickolashe  Once functionality for the unit test is ready to be tested feel free to move to "To be Tested" in the pipeline.

**Comment by MaxTattenbach** [comment]
I'll move this one.

**Comment by dannypernik** [comment]
@nickolashe given that there's no implementation issues in this milestone, if the unit tests look good, @tevtonez 's work here can be considered done. Max will be testing all use cases, but any additional implementation will be separate work.
