### ISSUE TITLE
invite-volunteers: Send optional personal message to invite emails

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#738]

**Comment by nickolashe** [comment]
@dannypernik Has personal message been added to the UI yet?

**Comment by dannypernik** [comment]
@nickolashe yes it's present in `personal_message` branch

**Comment by nickolashe** [comment]
@MaxTattenbach @dannypernik you can give this one a test now

**Comment by dannypernik** [comment]
@nickolashe status message when inviting 1 volunteer to non-event:
<img width="1051" alt="screen shot 2017-12-12 at 10 09 12 pm" src="https://user-images.githubusercontent.com/3347095/33921392-2c196a94-df89-11e7-9dd4-e494f1d6ea02.png">

Have not yet received any of the 3 test emails I had sent to dannypernik@gmail.com (an email with existing account)  from event- and non-event-based invite-volunteers. I then deleted this user and tried again from both use cases.

**Comment by dannypernik** [comment]
@nickolashe @MaxTattenbach I just upgraded MailChimp/Mandrill since we're out of free trials. It appears that the cheapest paid plan is $30 per month ($10 for MailChimp and $20 for 1 block per month of 25,000 emails - they don't have a smaller option). I'm sure there are cheaper options out there but we have relatively high switching costs given that all our emails are created with MailChimp.

**Comment by dannypernik** [comment]
I've now tested invite-volunteer-event-new and invite-volunteer-event-existing. Both are working with optional status message after I included the message variable in the template. However, invite-volunteer (when admin invites volunteer to create an account, not attend an event) is not passing in variables:

<img width="683" alt="screen shot 2017-12-13 at 12 17 20 am" src="https://user-images.githubusercontent.com/3347095/33924297-066e449c-df9b-11e7-98c4-5cfd2f4cfb85.png">

All of these and `PERSONAL_MESSAGE`need to be passed into the template.

**Comment by nickolashe** [comment]
@tevtonez please take a look

**Comment by nickolashe** [comment]
we've bombed out some of our mailchimp quota before we switched to mocking sending emails in unit tests

**Comment by tevtonez** [comment]
@nickolashe 
it should be covered in this commit: f938ed0
