### ISSUE TITLE
invite-volunteers: Submit emails from bulk-invites-box if shown (do not send from single-invites-box)

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#739]

**Comment by nickolashe** [comment]
@MaxTattenbach @dannypernik you can give this one a test now

**Comment by MaxTattenbach** [comment]
@tevtonez emails don't seem to be sending from invite volunteer form I can't test, unfortunately.

**Comment by MaxTattenbach** [comment]
Can't test due to email problem

**Comment by tevtonez** [comment]
@MaxTattenbach are there any additional info on where it fails, eg logs or anything I could use to pinpoint the issue?

**Comment by MaxTattenbach** [comment]
@tevtonez I believe Nicko solved the email issues will retest and let you know

**Comment by nickolashe** [comment]
@MaxTattenbach following up
