### ISSUE TITLE
email templates undefined variables

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#74]
Copyright © 2017 *|LIST:COMPANY|*, All rights reserved.
*|LIST:DESCRIPTION|*

Our mailing address is:
*|HTML:LIST_ADDRESS_HTML|*

**Comment by nickolashe** [comment]
?

**Comment by dannypernik** [comment]
@nickolashe the text I copied here is at the bottom of all the emails we send out. I can just delete it from the templates or we can define the variables.

**Comment by nickolashe** [comment]
Ok, lets just delete

**Comment by dannypernik** [comment]
Mailchimp informed me that by law, we need contact info in emails. It's not clear to me why Mailchimp's own merge tags are not populating with the company info, as I found the settings page where these fields are defined, and our info is there. Maybe a bug with MC. I'm just hard-coding these fields instead.

**Comment by nickolashe** [comment]
@dannypernik I think because this is not a list but a transactional email. I am pretty sure I saw an equivalent set of variables being populated for transactional emails before.
