### ISSUE TITLE
profile: Save answer to yes/no question in autopopup; do not display popup if previously answered

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#741]

**Comment by MaxTattenbach** [comment]
@nickolashe how do I check this in db?

**Comment by dannypernik** [comment]
@MaxTattenbach you can see the checkbox in the "User settings" table in admin panel.

**Comment by MaxTattenbach** [comment]
@tevtonez somehow the pop-up is appearing with users that already selected answer and doesn't allow them to click "yes" or "no".  proper functionality should be that once yes or no is selected it doesn't reappear.

**Comment by MaxTattenbach** [comment]
@tevtonez note that the popup is now showing up every time go into the profile from org admin or any other page.

**Comment by nickolashe** [comment]
FYI, latest issue had to do with a change i made
