### ISSUE TITLE
profile: In 'Community activity' section, display totals for Currents created, active volunteers, and Currents accepted

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#742]
If "Currents created" is clicked, 1st select box should be changed to "Top organizations";
If "Currents accepted" clicked, 1st select should be changed to "Top businesses";
If "Active volunteers" clicked, 1st select should be changed to "Top volunteers"

**Comment by MaxTattenbach** [comment]
@nickolashe @dannypernik to define if want to see Redeemed Currents

**Comment by MaxTattenbach** [comment]
@maxtattenbach check accepted vs redeemed close if working properly

**Comment by dannypernik** [comment]
@dannypernik

**Comment by MaxTattenbach** [comment]
@tevtonez, this is a pretty top issue.   

The Active volunteer's button is only displaying 10 active volunteers when there is more than 10.  I am imagining you are pointing it to the public record where we only display 10 volunteers maximum.

Active volunteers button under Community Activity:  Must add all the users that have been issued Currents too and that have a password w/ openCurrents.   There are cases where users have not created a password and get Currents like in live dashboard, those should not be counted as active volunteers.  We can discuss if this seems complicated to implement as we may have a simpler route for MVP.  @nickolashe 

While Currents issued:  should be the sum of all the Currents issued in the platform regardless if users have or don't have password with open Currents. 

![image](https://user-images.githubusercontent.com/26234440/34328869-022f5b44-e8b2-11e7-968b-d73f3eb39c44.png)

**Comment by tevtonez** [comment]
@nickolashe I think the changes in 4afdd14 should do the job. Please, let me know.

**Comment by nickolashe** [comment]
@tevtonez changes look good. i think we need to add a test for handling users without a password and then we can merge.

**Comment by tevtonez** [comment]
@nickolashe thanks.
I added assertion as a part of the same test case https://github.com/opencurrents/opencurrents/commit/9cacbb509c3cc1b6d63380f061e1a6c32cdf7396#diff-74d59739237d4413f6babaeba70721beR229

**Comment by nickolashe** [comment]
@tevtonez yes, the check looks good

**Comment by nickolashe** [comment]
@tevtonez per Max’s comment above, what about asserting that all volunteers are included in currents issued (both with and w/o password)?

**Comment by nickolashe** [comment]
@MaxTattenbach needs testing

**Comment by MaxTattenbach** [comment]
@nickolashe @tevtonez  will close this issues.  Active volunteers are now displaying properly.   The implementation is able to differentiate between those who have and don't have passwords which are great!

@nickolashe  The redeemed vs. accepted still pending but we have an epic for this so will close this one,
