### ISSUE TITLE
profile: add a section for group event activity

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#756]
hours listed similar to Hours approved section

**Comment by dannypernik** [comment]
@nickolashe what if we included event hours within "Hours approved"? The hours description could be the name of the event. And perhaps we should abandon the "Lets... " format for the event names. Bike Austin ignores it when creating their events

**Comment by nickolashe** [comment]
@dannypernik i think this would work, want to make the change

**Comment by dannypernik** [comment]
@nickolashe I'm not clear how `{% for record in hours_list %}` should change to include event-based records.

**Comment by nickolashe** [comment]
this would be a backend change actually
