### ISSUE TITLE
offer: Display duplicate offer error on biz-admin or edit-offer

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#761]
Currently this error stays on offer instead of directing user to a page where the offer can actually be edited:
<img width="640" alt="screen shot 2017-11-28 at 1 45 47 am" src="https://user-images.githubusercontent.com/3347095/33307935-0b2ce86c-d3de-11e7-9578-bbc400da071e.png">
Ideally this error would display on top of edit-offer with fields autofilled based on name of offer attempted. Also works to display error on top of biz-admin.

**Comment by nickolashe** [comment]
#776
