### ISSUE TITLE
approve-hours: Same record displays after successfully approving previous record

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#762]
@nickolashe see video I shared with you on Slack

**Comment by nickolashe** [comment]
@dannypernik can you save a snapshot of your db file (.sqlite) so we can reproduce the issue

**Comment by dannypernik** [comment]
Sent you a copy of .sqlite file on Slack. Also, notice that these blank AdminActionUserTimes have been created, presumably after clicking "Confirm" on approve-hours for the entry that is not getting approved/declined:
<img width="976" alt="screen shot 2017-11-29 at 10 51 00 am" src="https://user-images.githubusercontent.com/3347095/33387918-2520df3c-d4f4-11e7-8a71-566f321b5549.png">

I tried deleting the blank entries but got this error:
![image](https://user-images.githubusercontent.com/3347095/33387958-3abc7aea-d4f4-11e7-8c7e-8864747c48d2.png)

**Comment by MaxTattenbach** [comment]
@dannypernik  I am not sure what you mean with this issue.  Can you test?   If its working the Approve Hours epic seems to be completed.

**Comment by dannypernik** [comment]
I'm no longer getting this error, and no one else has experienced it so I'm closing
