### ISSUE TITLE
nominate, public-record: admin-required menu items not displaying

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#763]
@nickolashe I noticed that for nominate and public-record templates, we lose the full menu when an admin is logged in:

<img width="1049" alt="screen shot 2017-11-29 at 2 49 11 pm" src="https://user-images.githubusercontent.com/3347095/33398464-a7b8d9ac-d514-11e7-8b50-2fe6e84ee18c.png">
<img width="1050" alt="screen shot 2017-11-29 at 2 49 23 pm" src="https://user-images.githubusercontent.com/3347095/33398468-abed0c1e-d514-11e7-9d59-e3550f662a85.png">
<img width="1050" alt="screen shot 2017-11-29 at 2 49 35 pm" src="https://user-images.githubusercontent.com/3347095/33398469-ada49efa-d514-11e7-9dbf-81fd342cdce7.png">

**Comment by nickolashe** [comment]
#776
