### ISSUE TITLE
business: Automatically accept user as biz admin on signup

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#768]
bizdev@opencurrents.com should still receive notification email

**Comment by nickolashe** [comment]
@dannypernik can you clarify what you mean by this exactly?

**Comment by dannypernik** [comment]
@nickolashe currently a user who creates a business must be manually added to the business admin group before getting admin access. Access should be automatic for businesses but not for nonprofits.

**Comment by nickolashe** [comment]
@dannypernik i can do the change for business users. let track functionality for regular users separately.

**Comment by dannypernik** [comment]
Regular users creating org tracked in #770

**Comment by nickolashe** [comment]
@MaxTattenbach

**Comment by MaxTattenbach** [comment]
@nickolashe affiliation seems to be happening automatic, although no email is being sent so I can't create an account to create a password. 

![image](https://user-images.githubusercontent.com/26234440/34089821-7a77e614-e378-11e7-8d4a-591dacd03d71.png)

![image](https://user-images.githubusercontent.com/26234440/34089889-f5785092-e378-11e7-904f-11d07f9ee563.png)

**Comment by nickolashe** [comment]
@MaxTattenbach i've also been seeing email issues in production. where are you testing this?

**Comment by nickolashe** [comment]
nothing changed on the backend in terms of sending email verification emails

**Comment by MaxTattenbach** [comment]
@nickolashe testing in develop server.  I haven't done any testing in production.

**Comment by MaxTattenbach** [comment]
@nickolashe somehow now the association is not being created automatically on the backend.  I think the nonprofit form and the biz form now may be mistaken.   I registered Fast Folks1  

@dannypernik  @nickolashe note that form comming into biz dev is missing a variable in the header.  

![image](https://user-images.githubusercontent.com/26234440/34263201-4db3e3a8-e634-11e7-9219-80e2c746ac51.png)

![image](https://user-images.githubusercontent.com/26234440/34263383-e87547f6-e634-11e7-8a79-f048b88aa71e.png)

![image](https://user-images.githubusercontent.com/26234440/34263254-741ff19e-e634-11e7-9de6-a2e7e90bed45.png)

**Comment by MaxTattenbach** [comment]
@nickolashe, Even after creating the associating email with org on the database I am not getting the account is not getting any affiliation on the frontend.

![image](https://user-images.githubusercontent.com/26234440/34272314-6af6347c-e655-11e7-96d4-e0b01b0bd39e.png)

![image](https://user-images.githubusercontent.com/26234440/34272383-b7a673f4-e655-11e7-92c3-b7df7d7f5253.png)

**Comment by dannypernik** [comment]
@MaxTattenbach I'm a little confused that you made the comment above then closed the issue. Is it fixed? If you can leave a clarification comment when you close issues it will help.

**Comment by MaxTattenbach** [comment]
@dannypernik this is working now.  I'll clarify for other cases.
