### ISSUE TITLE
Change email message. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#77]
Lets add a touchier email message for confirmation!

"Changing the world with one Current at time"

**Comment by nickolashe** [comment]
@MaxTattenbach Welcome to GH issues!

**Comment by dannypernik** [comment]
@MaxTattenbach @nickolashe @karbmk what do you think of this as the subject line once email is confirmed: "Let's make waves - one Current at a time"

**Comment by nickolashe** [comment]
what's the status of this one?
