### ISSUE TITLE
redeem-currents: Variables on Confirmation page reset on error message

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#774]

**Comment by dannypernik** [comment]
I'd say no, it's an edge case

**Comment by nickolashe** [comment]
i mean blocking launch

**Comment by dannypernik** [comment]
No I don't think so. But I should be able to find a solution regardless.

**Comment by dannypernik** [comment]
@nickolashe In addition to changing values of variables when the price input changes here...
https://github.com/opencurrents/opencurrents/blob/develop/openCurrents/templates/redeem-currents.html#L348
...we will also need to have the variables set equal to the price input when the page loads. This is because the input will already be filled if there's an error on the page. I see that you've defined some functions within the .on('input') function, but could they be moved outside that function in order to call them on page load as well?

**Comment by nickolashe** [comment]
there are no function definitions inside .on('input'). instead i am calling the getUserBalance asynchronously. same call can be issued on page load, just copy it over (not move)

**Comment by dannypernik** [comment]
@nickolashe Does this look right? Seems unDRY?

**Comment by nickolashe** [comment]
yes, very undry. why don't we turn https://github.com/opencurrents/opencurrents/blob/develop/openCurrents/templates/redeem-currents.html#L348-L377 into a function and call it in both places?

**Comment by dannypernik** [comment]
@nickolashe agreed:
https://github.com/opencurrents/opencurrents/blob/develop/openCurrents/templates/redeem-currents.html#L347
