### ISSUE TITLE
Events Creating negative balance in Currents.   Hours are actually summing up negative Currents not positive. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#777]
![image](https://user-images.githubusercontent.com/26234440/33580833-43588b0c-d914-11e7-9f5c-bc0be8f82514.png)

**Comment by MaxTattenbach** [comment]
@nickolashe note that events either pass negative balances in Develop and don't pass any balances at all in Master.

**Comment by nickolashe** [comment]
@MaxTattenbach can elaborate pls, which events you mean here? group events and checking in through live-dashboard, or something else?

**Comment by MaxTattenbach** [comment]
Yeah its the live-dashboard event.  @nickolashe

**Comment by nickolashe** [comment]
looks like i swapped the roles of start and end time accidentally:
https://github.com/opencurrents/opencurrents/blob/develop/openCurrents/views.py#L2195

**Comment by nickolashe** [comment]
should be a quick one, thanks for catching @MaxTattenbach

**Comment by dannypernik** [comment]
Thanks @nickolashe and @MaxTattenbach

**Comment by MaxTattenbach** [comment]
@nickolashe tested this on develop and it continues issuing negative Currents after registering at event on live-dashboard.  I'm assuming it hasn't been pushed to develop yet?

**Comment by nickolashe** [comment]
@MaxTattenbach fix pushed, moving to "To be tested" pipeline
