### ISSUE TITLE
Biz Details form to be added. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#782]
As agreed we will release with once the businesses can add some details as contact information, address, etc etc.

**Comment by nickolashe** [comment]
biz detail form is in develop now

**Comment by nickolashe** [comment]
moved to "To be tested"

**Comment by nickolashe** [comment]
@dannypernik @MaxTattenbach has this been tested? please close if so.

**Comment by dannypernik** [comment]
@nickolashe 3 fields display "None" as the default value instead of blank
<img width="745" alt="screen shot 2017-12-12 at 6 21 29 pm" src="https://user-images.githubusercontent.com/3347095/33915526-6eb52840-df69-11e7-8489-5c24690f6a74.png">

**Comment by dannypernik** [comment]
@nickolashe "Introduce your business" field does not save

**Comment by dannypernik** [comment]
Does not check if website is valid - not required for MVP

**Comment by nickolashe** [comment]
are you sure intro is saved? i think it was on my end

**Comment by MaxTattenbach** [comment]
@dannypernik @nickolashe added a dependency to this issue, to complete this issues form must be displayed in the marketplace so users can access biz information.

**Comment by dannypernik** [comment]
@nickolashe I've designed a dropdown to display biz details on `biz_details` form (#837). See that PR for the variables we need. If you let me know the variable names, I can add them to the HTML.

**Comment by nickolashe** [comment]
please note the following discrepancies here:
1. biz details on marketplace should not be referred to as a form - its not taking any user input
2. this issue (#782) is not blocked by anything, #837 does not depend on it

**Comment by MaxTattenbach** [comment]
@nickolashe understood on dependencies. Looks good.
