### ISSUE TITLE
openCurrents.com - Size:  I think the site looks better when zoomed in at 125%, see the difference.  Have had a few folks tell me the same. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#783]
![image](https://user-images.githubusercontent.com/26234440/33617299-f9c07e14-d9a4-11e7-9697-554b322da083.png)
![image](https://user-images.githubusercontent.com/26234440/33617343-0c7be732-d9a5-11e7-803e-de580ce4a572.png)

**Comment by dannypernik** [comment]
Updated in `new_home` branch
