### ISSUE TITLE
opencurrents.com/business - Let's change title:  Join openCurrents and register a business 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#785]
![image](https://user-images.githubusercontent.com/26234440/33617860-865ab5fa-d9a6-11e7-8e7b-73d52d9af6f6.png)

**Comment by dannypernik** [comment]
@MaxTattenbach it needs to be one or the other - both is too long. Which do you prefer?

**Comment by dannypernik** [comment]
@MaxTattenbach

**Comment by MaxTattenbach** [comment]
@dannypernik  Let's keep it as is in the meantime.
