### ISSUE TITLE
openCurrents.com/nonprofit.  Let's change to Join openCurrents and register a nonprofit

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#786]
![image](https://user-images.githubusercontent.com/26234440/33618658-be1fbb14-d9a8-11e7-96d1-b9075b0177b8.png)

**Comment by dannypernik** [comment]
@MaxTattenbach I think it's important to distinguish between individual and nonprofit/business. "Join openCurrents" as the link is not specific and applies to individuals, nonprofits, and businesses.
