### ISSUE TITLE
openCurrents.com - Lets add text box when hovering over register as business or nonprofit. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#788]
Let's discuss the following. I suggest text box says the following:
When hovering over:
- business:  Businesses receive Currents from customers, you can also volunteer to earn Currents
- nonprofit: Nonprofits issue Currents to their volunteers, you can also volunteer to earn Currents 

When hovering over  "Register as Individual" on nonprofit or business page: 
Individuals earn Currents by volunteering 

![image](https://user-images.githubusercontent.com/26234440/33619197-2c48b220-d9aa-11e7-8521-70b06934557a.png)

**Comment by dannypernik** [comment]
I prefer what we have.
