### ISSUE TITLE
openCurrents.com/ourstory  - After clicking "join community" it should take you to bottom of page not a pop-up.  

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#791]
![image](https://user-images.githubusercontent.com/26234440/33623543-f41a29d0-d9b6-11e7-8400-2eb0d019eb61.png)

**Comment by dannypernik** [comment]
@MaxTattenbach we agreed that the "Join" buttons would display popup on all landing pages. Scrolling to bottom is distracting. Please close if we're good here.

**Comment by dannypernik** [comment]
@MaxTattenbach
