### ISSUE TITLE
public-record:   All Time on public record doesn't be to summing Currents Correctly. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#795]
Note Last 30 days and all time are the same, see the discrepancy with Org Profile page.   I believe what's happening is that it's not filtering correctly in the database.  All Time and Org hours track should be matching. 

![image](https://user-images.githubusercontent.com/26234440/33735306-8bf0bf64-db54-11e7-9309-4263d9a4c363.png)
![image](https://user-images.githubusercontent.com/26234440/33735329-9aef3b94-db54-11e7-88d9-035727bfd52f.png)
![image](https://user-images.githubusercontent.com/26234440/33735357-af2d98a8-db54-11e7-8b70-899904600730.png)

**Comment by nickolashe** [comment]
we've only started tracking ledger recently. could you verify this claim further by creating an event more than 30 days in the past and checking some in?

**Comment by nickolashe** [comment]
@MaxTattenbach

**Comment by nickolashe** [comment]
@MaxTattenbach still waiting to hear from you on this one

**Comment by MaxTattenbach** [comment]
@nickolashe so I created an event in the past 7th of Nov.  Currents are adding up on public profile on both All Time and Past 30 days.   The issue now seems that Currents issued with more than 30 days in the past are been added to Last 30 days.

**Comment by nickolashe** [comment]
that is correct, working on a fix

**Comment by nickolashe** [comment]
@MaxTattenbach can you give another test pls

**Comment by MaxTattenbach** [comment]
@nickolashe same issue as above.  Created an event 9th of November.  Currents adding up in public record in last 30 days and all time.

**Comment by MaxTattenbach** [comment]
@nickolashe same issue as before.  Events with more than 30 days are showing in the public record on "past 30 days"
 
Although I do notice for first time a difference between "all time" and "past 30 days" in public record.  Maybe that the DB is filtering Currents by the day recorded rather than day of work.  

Not sure how to test for manual tracking on same issue as I would have to wait 30 days.

**Comment by nickolashe** [comment]
can you check what the difference is between the two (which events)?

**Comment by MaxTattenbach** [comment]
I'll add "to be tested" and follow-up with this

**Comment by MaxTattenbach** [comment]
@nickolashe   I erased everything in the database and started from 0.  

Both events and manual tracking with more than 30 days is showing up in past 30 days.   For manual tracking, I did went past the restriction by entering past date manually.   

 Currents are been created but the filter in public record doesn't seem to be working.

**Comment by nickolashe** [comment]
found the bug. you should not need to recreate anything, it should filter existing fixtures correctly now.
