### ISSUE TITLE
Discrepancy in hours approved in Events. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#797]
The following illustrates the flow of the issues with hours approved via events. 

Max Gmail dot = Admin  ;    Max oC = Volunteer registered to event.   

Max oC was checked in via live dashboard to 10 hour event by Max Gmail dot. 

#1. Issue: Hours Approved on Org Admin Profile did not change.  Max Gmail dot should have increased by 10 Hours.  Org Hours Tracked on Profile is not changing with events. 

1. Pre Event (Admin Profile)

![image](https://user-images.githubusercontent.com/26234440/33736526-8019d708-db58-11e7-8207-2f71aa79ba05.png)

1. Post Event (Admin Profile)

![image](https://user-images.githubusercontent.com/26234440/33737085-8fb60a2c-db5a-11e7-8edb-490ed4b7b96a.png)
 
#2. Issue: Hours Approved in User Profile should have increased by 10 Hours, inside of the Casa Marianella button.  Currents issued in activity working properly

2. Pre Event (User Profile)

![image](https://user-images.githubusercontent.com/26234440/33736585-c0c243bc-db58-11e7-9330-cb952caed337.png)

2. Post Event (User Profile)

![image](https://user-images.githubusercontent.com/26234440/33737344-67860268-db5b-11e7-9d91-24f123e8864a.png)

#3 Issue. Hours-details:  Hours of events not being logged to hours detail. 

![image](https://user-images.githubusercontent.com/26234440/33737555-312f2a5e-db5c-11e7-9978-af78c2d82016.png)

#4 Issue: Let's Change "Hours approved":  Currently the name Hours approved is being used in Org Admin profile and User profile and they are two different things.  The name is confusing.  I suggest the following. 

Hours approved by Admins  - for org admin 

Volunteer hours approved -  for user profile

**Comment by nickolashe** [comment]
@MaxTattenbach the reason why live-dashboard was not working is because it was not showing already checked in users correctly (it is now)

**Comment by nickolashe** [comment]
merged the fixes, can you retest please @max

**Comment by MaxTattenbach** [comment]
@nickolashe issues on User Profile seem to have been fixed.  I'll close this issue epic.    Although added three new issues into an epic, related to org-profile where hours of events don't seem moving displaying properly.
