### ISSUE TITLE
Public Record:  Mismatch between Title and data displayed in the default

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#799]
Note that the default labels correspond to Orgs and data displays volunteers.   Let's keep Orgs as the default in the meantime. 

![image](https://user-images.githubusercontent.com/26234440/33740556-b921dac4-db66-11e7-8106-f6bf53b2367b.png)

**Comment by nickolashe** [comment]
to be tested

**Comment by dannypernik** [comment]
@MaxTattenbach 's change of pipeline from Tested then to Closed begs the question - when issues are tested and working, do we move to Tested or Closed? I suggest we test things twice - first person moves it to Tested, the 2nd moves it to Closed.

@nickolashe also note that we've added a bucket "Tested needs work" and changed the name of the Tested bucket to "Tested and working".

**Comment by nickolashe** [comment]
does that assume each issue is going to be tested by two persons?

**Comment by MaxTattenbach** [comment]
@dannypernik @nickolashe  I am doing most of the testing and will close once I double check and I feel confident its working properly. 

I'll go ahead and change the label  from "tested and working"  to "Working to be Retested"

**Comment by dannypernik** [comment]
@nickolashe Max and I discussed it makes sense to use "retest" bucket for new features so that we get 2 people verifying proper functionality. However for smaller issues or bugs, we'll close after one successful test.
