### ISSUE TITLE
admin-profile: Event start and end time displays incorrectly

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#80]
I created an event from 10:00am to 12:00pm, and it's showing on admin-profile as 10:06am to 12:06pm

**Comment by nickolashe** [comment]
???

**Comment by dannypernik** [comment]
Two things now - first, timezone has changed to system timezone, pushing start and end times back 5 hours. 2nd, it says 5:06 to 7:06 when it was entered into the db as 5:00 to 7:00 (timezone adjusted). See screenshot.
<img width="640" alt="screen shot 2017-06-07 at 1 24 56 pm" src="https://user-images.githubusercontent.com/3347095/26894835-2f601060-4b85-11e7-8f47-4107bf1098af.png">

**Comment by nickolashe** [comment]
@dannypernik The minute thing was an easy fix:
https://github.com/opencurrents/opencurrents/commit/cb0bd48837e7fd93f7dd29d3252aa0a0608dd0b1

**Comment by nickolashe** [comment]
The "system timezone" thing is the expected behavior. When you enter dates into admin it takes them as UTC. But the event is showing in local (Austin) time.

**Comment by nickolashe** [comment]
@dannypernik Feel free to close the issue if you are happy with this
