### ISSUE TITLE
Org- Admin:  Hours Approved not adding

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#805]

**Comment by MaxTattenbach** [comment]
Hous approved for Max Gmail dot, should have increased by 20 hours and gone from 18 to 38 hours. 
Max Gmail dot registered Max oC for a 10-hour event.   

![image](https://user-images.githubusercontent.com/26234440/33776622-9a539b36-dc07-11e7-9310-d0ba204fc0b7.png)

**Comment by nickolashe** [comment]
@MaxTattenbach can you provide more details please? is this for a group event again? why 20 hr, and not 10? have you checked if admin Max gdot already received hours for this event (by checking anyone else in prior to this)?

**Comment by nickolashe** [comment]
@tevtonez like to be the same issue as #804

**Comment by MaxTattenbach** [comment]
@nickolashe regarding question above:   It is 20 Currents because its giving Currents to both admin and volunteer once the volunteer gets checked in.  

A bit confused because yesterday it was only giving Currents to the Volunteer.  Either or are Ok but it should be consistent throughout the platform.

**Comment by nickolashe** [comment]
@MaxTattenbach it only issues the currents to the admin once per event. that's why i wanted to check if the admin has checked in anyone to this event prior to this

**Comment by MaxTattenbach** [comment]
All events had the volunteer check-in.  And yes the functionality seems to
be working fine.

Max Tattenbach
Cofounder & CEO
opencurrents.com <http://www.opencurrents.com>

**Comment by MaxTattenbach** [comment]
Working now.
