### ISSUE TITLE
Hours-detail: Event hours are not passing on to organization Hour detail 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#806]

**Comment by MaxTattenbach** [comment]
All the three events below in which volunteers, where checked in, should be showing up in Hours-detail (Org).    Note:  Event hours are being passed along to Hours detail (user) are being passed along.  (see the lowest screen shoot.) 

![image](https://user-images.githubusercontent.com/26234440/33776983-bc29fef2-dc08-11e7-832b-8dd2b71321ee.png)

![image](https://user-images.githubusercontent.com/26234440/33777053-f5443e64-dc08-11e7-9fc4-32d7513b5375.png)

![image](https://user-images.githubusercontent.com/26234440/33777158-5e523b36-dc09-11e7-876d-7ba6cc6fdf11.png)

**Comment by nickolashe** [comment]
@tevtonez lets remove the manual filter here:
https://github.com/opencurrents/opencurrents/blob/kostya_profile_additions/openCurrents/interfaces/orgadmin.py#L50-L52

**Comment by nickolashe** [comment]
this should fix it

**Comment by tevtonez** [comment]
@nickolashe this one should be fixed with my latest commit...

**Comment by nickolashe** [comment]
@tevtonez can link to the commit pls

**Comment by nickolashe** [comment]
alternatively, can mention #<issue_number> in the commit message

**Comment by tevtonez** [comment]
ok, will do @nickolashe

**Comment by MaxTattenbach** [comment]
Working now!  Thanks   @nickolashe @tevtonez
