### ISSUE TITLE
Invite Volunteer: Lets Change Email Subject line: From: An invitation from [org] to  [Admin  first name], [last name] from [org] is inviting you to [event]

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#812]

**Comment by MaxTattenbach** [comment]
![image](https://user-images.githubusercontent.com/26234440/33801037-adb0c39a-dd13-11e7-99d3-ebd0ce4f1822.png)

**Comment by dannypernik** [comment]
@MaxTattenbach I'd like to use the same subject line for all emails related to invite-volunteer template. How about "An invitation from [admin first] [admin last] of [org]"

**Comment by MaxTattenbach** [comment]
I am ok with your proposed, although have a feeling that if Admin Name is first in subject people are more likely to open. 

We could do:
[admin first] [admin last] from [org] is inviting you to...

Pick which ever you like better.  I'm ok here

**Comment by dannypernik** [comment]
Alright thanks, I went with the first change.
