### ISSUE TITLE
Invite Volunteer:  Lets Change Text in body of Email. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#813]
Lets Change To: 

[Admin FN] [Admin LN] is inviting you to volunteer on [Event date] at [time], in [location].

[Project description] 

Click the link below to register for the event to volunteer.  You can earn Currents for volunteering at this event.
 
You can also reach out to Max by replying to this email.

Original:

![image](https://user-images.githubusercontent.com/26234440/33801038-bfc9205e-dd13-11e7-872d-464e297bef68.png)

**Comment by dannypernik** [comment]
@MaxTattenbach I'm not clear on why the original is an issue or why the new one is better.

**Comment by dannypernik** [comment]
@MaxTattenbach

**Comment by MaxTattenbach** [comment]
@dannypernik I want an invitation to show admin on the subject versus org.  I believe people are more inclined of opening email when the name of a person is displayed on the subject.  Especially if the email is coming from info@openCurrents. com

**Comment by dannypernik** [comment]
@MaxTattenbach got it. Changed subject in preview to "An invitation from [Admin FN LN] of [orgname]" as we previously agreed.
