### ISSUE TITLE
Profile Pop-up: Let's change text to make it more enticing. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#823]
I read over the pop-up when signing in.  I think it could be improved significantly.   I suggest the following. 

Title:  Would you like to be a  "community developer" with openCurrents? 

Community developers are those who actively seek to grow our community and get special benefits on the platform for doing.  For example, you introduce to your network of friends, non-profits, and business so we all can all benefit from a community that values social action.  

You can always opt-in later from your profile to become a community developer. 

 (Yes, I want to be community developer)    (Not now,  Maybe later)

![image](https://user-images.githubusercontent.com/26234440/33808612-5adc9288-ddaf-11e7-84f1-22e8cd2e3a48.png)

**Comment by dannypernik** [comment]
@MaxTattenbach how about:

Title: Would you like to be a community connector?

Community connectors actively seek to grow this movement and get special benefits for doing so. You could bring massive value to the community by simply asking your favorite business, "Do you accept Currents?"

What do you say, do you want to help us create Currents in the world?

Yes, count me in / Not now

**Comment by MaxTattenbach** [comment]
@dannypernik I like it!  

Let's add after (Yes, count me in/Not now)

You can always opt-in later to become a community connector.
