### ISSUE TITLE
live-dashboard: Remove last name autofill 

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#827]
Leading to incorrect volunteers being added. Last names are frequently shared by multiple users and there's no way to tell who is who when multiple last names appear. If you select the wrong name, selecting another option does not revise the last name. I've found at least one occasion where I was checked in to a volunteer event under the wrong email.

Let's remove autofill until we have a search field.

**Comment by nickolashe** [comment]
sounds good @dannypernik , want to take a shot at it?

**Comment by dannypernik** [comment]
@nickolashe looks like this takes care of it?
https://github.com/opencurrents/opencurrents/pull/835/files#diff-4bb47c5b5349a08b7772a129a0bbcb0dL301

**Comment by nickolashe** [comment]
right
