### ISSUE TITLE
Market Place:  Create way to access biz detail form from the marketplace.

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#834]
There is no way for users to access the biz detail form. 

![image](https://user-images.githubusercontent.com/26234440/33961067-536df176-e012-11e7-9fdd-adaef2d8a35a.png)

**Comment by dannypernik** [comment]
Added in PR #837. Adding a bucket in pipeline "PR in Progress".

**Comment by nickolashe** [comment]
what does PR in Progress mean? does it mean a finished PR or not?

**Comment by dannypernik** [comment]
@nickolashe it means a PR is open but not merged. Currently includes PRs that I open that need backend work, or PRs that are ready to merge. Not sure if you want to split them.

**Comment by nickolashe** [comment]
yes, i think i prefer to have those separate

**Comment by dannypernik** [comment]
I've added bucket "PR needs backend" and "PR ready to merge"
