### ISSUE TITLE
Link to All upcoming projects from user profile

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#84]
Currently if the user is not registered for any events, the page only shows the balance and nothing else. would be nice to link to all upcoming projects so they can register.

**Comment by nickolashe** [comment]
@dannypernik Thoughts? Lets try to respond to issues within 24 hr.

**Comment by dannypernik** [comment]
@nickolashe I suggest we leave this until after Saturday, then merge profile with admin-profile.

**Comment by nickolashe** [comment]
sounds good

**Comment by nickolashe** [comment]
@dannypernik What's the status of this one?

**Comment by dannypernik** [comment]
@nickolashe We are now linking to both upcoming-projects and time-tracker on the profile page. I've added 2 events to upcoming-projects, but the event start/end times are displaying the month instead of the minutes (#145). Also, time-tracker is not ready so I'm removing that link for now. Please review PR #146.

**Comment by nickolashe** [comment]
@dannypernik can you doublecheck re: times? I think they are showing up properly for me in the app.

**Comment by dannypernik** [comment]
@nickolashe huh interesting. ok so all of Karen's volunteers had been manually checked out. I checked all 31 volunteers back into the event. KAB's total went from 67 to 115.2. The expected total was 67 + 62 = 129.

**Comment by nickolashe** [comment]
to be accurate, this logic is conditional upon them being excluded from the original count.
otherwise, the expected total would still be 67.

**Comment by dannypernik** [comment]
@nickolashe not following. We have a total of 62 volunteers- 31 at 2 events. If each volunteer gets exactly 2 hrs (which I realize isnt necessarily the case) the total should be 124

**Comment by nickolashe** [comment]
if they were included in the original 67 in whatever form they won't get credit for the same event twice
