### ISSUE TITLE
Live Dashboard: Hours are not been recorded when users don't have a existing password or active account openCurrents. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#846]
@dannypernik @nickolashe;  seems to me that we want to track hours on live dashboard no matter if a person is on the platfrom or not.  

Note despite hours not tracked new users are being created in the DB although hours aren't being associated. 

Image #1 checked everyone in. 

![image](https://user-images.githubusercontent.com/26234440/34074927-e5b73a6a-e27e-11e7-90df-a973adb69d69.png)

Image #2. Went back to org and then back into the live dashboard and all the new users were unselected.     Note I added a name for one of the Dustin's when invited to the event to see if not adding name when adding new user was the problem, but it's not.   

![image](https://user-images.githubusercontent.com/26234440/34074933-f7a4bb1c-e27e-11e7-9bc8-43678f89edd2.png)

Image #3 

Created a new event inviting two existing users in the database.  max@opencurrents.com and Max@opencurrents.com (capital M).   Note that Max@opencurrents.com (capital M) was previously created in the database from the previous event, but has not yet created a password. 

Hours were not tracked for Max@opencurrents.com (capital M) 

![image](https://user-images.githubusercontent.com/26234440/34074993-dc18d90e-e27f-11e7-94ee-dd3402ceaa58.png)

Image #4
When going back to org profile after checking both in and coming back to the event preview (capital M) is unselected.   No hours were recorded for (Capital M)

![image](https://user-images.githubusercontent.com/26234440/34075021-592cc748-e280-11e7-8ee3-975e3eae34aa.png)

@nickolashe it seems that we should also solve the Capital letter issue in the database.  Perhaps kostya can take a lead there.

**Comment by nickolashe** [comment]
@tevtonez lets take a look at this one
