### ISSUE TITLE
Profile:  Currents "Accepted" no longer displaying in Profile nor Public record. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#847]
@dannypernik  @nickolashe -  Not sure if the confusion here is the definition of "Accepted".  I believe we actually want to display Currents redeemed as before.  

 Before (as of a couple of days ago)  the public record and profile were displaying Redeem Currents now its not.   Not sure what it is?

![image](https://user-images.githubusercontent.com/26234440/34075071-6676fcec-e281-11e7-92cc-cb9937529fc1.png)

![image](https://user-images.githubusercontent.com/26234440/34075152-566fea0a-e283-11e7-8752-c1a9b60359b1.png)

**Comment by nickolashe** [comment]
could it be due to the fact you cleared everything? you'll need to rerun the setup_fixtures.py script to create some accepted.

**Comment by MaxTattenbach** [comment]
@nickolashe  we were before showing Currents redeemed.   I think we should show currents redeemed vs. accepted.  On the openCurrents platform to date, there haven't been "accepted" Currents - I don't believe this functionality exists from biz admin side.

**Comment by nickolashe** [comment]
@MaxTattenbach so the idea was to transition `pending` (the initial state) to `accepted` after a certain time window. then once the funds are transferred move to `redeemed`. there won't be any accepted or redeemed in production yet, but you can create those using the script locally or test in develop. let me know what you think.

**Comment by MaxTattenbach** [comment]
@nickolashe, thanks for the clarification on timing that makes sense. 

Although, I believe before we were illustrating # Currents used to redeem offers in both profile and public record.  I remember numbers changing as we redeemed offers.  Or did you now include the timing variable which gives it some type of time lag. 

I think the more we can illustrate the movement in a "live" form in the ecosystem the better.

**Comment by MaxTattenbach** [comment]
@nickolashe per agreed we will convert Currents accepted to "Currents Redeemed for offers". This should show the number of Currents used in the ecosystems to redeem offers whether accepted or not.   We will decide if we want to include Currents Accepted post MVP.
