### ISSUE TITLE
Profile: Let's display active npf and active biz in the community activity - currently we aren't.

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#848]
@dannypernik  @nickolashe let's make it very simple and just add the amount of biz on the platform and on openCurrents.  It doesn't matter if they have issued Currents for npf or accepted Currents as a business.

Note ecosystem buttons: "active orgs" and "active biz" can point to the public record Currents issued and Currents "Accepted"
 
![image](https://user-images.githubusercontent.com/26234440/34075173-24ce38ca-e284-11e7-8864-6d5cf33344bc.png)

![image](https://user-images.githubusercontent.com/26234440/34075166-026eb25a-e284-11e7-89f9-5ffa5b127618.png)

**Comment by dannypernik** [comment]
@MaxTattenbach so you want 5 buttons? feels like too much

**Comment by MaxTattenbach** [comment]
@dannypernik profiles will be pretty empty at the beginning.  Let's discuss.  For the future lets try and stick to the spec sheet and if we feel we want to change it let raise it up on an issue. 

@dannypernik what's  your position on Currents accepted and redeemed.

**Comment by dannypernik** [comment]
@MaxTattenbach I suggest we use 3 buttons for community activity as we originally agreed on.  Logic of current buttons is to have bigger numbers showing. I'm happy with Currents redeemed over Currents accepted for that reason.

**Comment by MaxTattenbach** [comment]
@dannypernik  Sounds good.  We can keep it to three buttons.
