### ISSUE TITLE
profile: Opencurrents icon click redirection error.

### ISSUE THREAD

**Issue by karbmk** [opencurrents/opencurrents#86]
When you login into the dashboard of Opencurrents as a legitimate user and click the Opencurrents icon on the top left the website behaves as expected. 
1. But when you move the "Organisation signup" page after login and try clicking the Opencurrents icon on the top left error occurs. Find attached the screenshot of the same.
2. Also, in login page when you click Opencurrents icon same behaviour is observed.

![screen shot 2017-06-07 at 12 04 19 pm](https://user-images.githubusercontent.com/8406712/26898500-163fc1f6-4b81-11e7-84fd-6ac21bc4252b.png)

**Comment by nickolashe** [comment]
@karbmk Thanks
@dannypernik Is the link on org-signup correct?

**Comment by dannypernik** [comment]
@nickolashe @karbmk earlier I changed the link on my branch to /user-home as Nicko and I agreed. This link is in header.html which is extended to all the templates. I just tested on my version and header img successfully directs to user-home. This ties back into my suggestion that we merge or delete the 6 outstanding PRs.

**Comment by dannypernik** [comment]
@nickolashe @karbmk however if we do want to direct to /profile after all, we'll need to figure this out. I suggest we leave it as user-home for Saturday and merge profile with admin-profile afterwards.

**Comment by nickolashe** [comment]
@dannypernik lets step through the outstanding PR's together sometime today

**Comment by dannypernik** [comment]
@nickolashe from an admin account, if I go to org-signup and click the home logo, it takes me to user-home instead of admin-profile. I'm guessing orgid is not passed into org-signup template? This leads to the question: is passing in orgid to every template the most efficient way of checking admin status?

**Comment by nickolashe** [comment]
@dannypernik We need to add `SessionContextView` to every view that needs `orgid` context, including this one:
https://github.com/opencurrents/opencurrents/blob/master/openCurrents/views.py#L153
Feel free to open a PR with these changes.

**Comment by nickolashe** [comment]
@dannypernik It is not passed explicitly, every view that needs it inherits it from that parent view. Do you have a suggestion on how to do this better?

**Comment by dannypernik** [comment]
@nickolashe since every view has a header logo which links to profile, every view will require orgid. I'm just hoping it's not something you have to add every single time. But if there's no other way, then so be it.

**Comment by nickolashe** [comment]
@dannypernik Its just a matter of adding an extra word to the def. Follow the example here:
https://github.com/opencurrents/opencurrents/blob/master/openCurrents/views.py#L173
