### ISSUE TITLE
Emails from invite volunteers form is not working. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#871]
@tevtonez @nickolashe emails from invite volunteer form is not been sent.

**Comment by tevtonez** [comment]
@MaxTattenbach I've just tried it during the fix for #846 and it worked for me (bulk and individual emails)
it's possible that this feature will work again after PR is approved.

**Comment by nickolashe** [comment]
@tevtonez which PR did you mean, #882?

**Comment by nickolashe** [comment]
this is ready for testing, if so
