### ISSUE TITLE
Currents Accepted to Currents Redeemed in Profile and Public Record.

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#874]

**Comment by MaxTattenbach** [comment]
@nickolashe I believe you had mentioned a few days ago on Slack you had done work on this one.   See my comment on 12/24 on #697 

I'll retest once ready.

**Comment by nickolashe** [comment]
@MaxTattenbach i have not merged the changes yet. see the discussion on #880.

**Comment by MaxTattenbach** [comment]
@nickolashe thanks for heads up.

**Comment by MaxTattenbach** [comment]
@nickolashe  this is working on master.  If the code is the same I believe we should close.  Last time I checked I didn't see it working properly on develop.

**Comment by nickolashe** [comment]
yes
