### ISSUE TITLE
business signup form. The upper form of the website is not working.  

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#889]
Email Received to biz dev after creating two biz accounts from top form and bottom form.   Notice that the top is not complete.   

The top form is not creating the biz, it does create an Org id but when associating them on the DB nothing happens.  not the case for the bottom form which works fine. 

Top form:
![image](https://user-images.githubusercontent.com/26234440/34272735-192b55f8-e657-11e7-9d81-6e826390d302.png)

Bottom Form.
![image](https://user-images.githubusercontent.com/26234440/34272703-f116c188-e656-11e7-8973-13972ee64fce.png)

**Comment by MaxTattenbach** [comment]
@dannypernik  -  can we just send user to the bottom after creating join community in biz and eliminate top form.  That would be the easiest way around it.  Also, I believe we should do these for NPF page and Volunteer and User, this way when signing in they always see what they want to sign in as.

**Comment by nickolashe** [comment]
@dannypernik could you compare the two forms in the template to see if you find any differences?

**Comment by dannypernik** [comment]
@nickolashe there's a difference with the hidden field. Here's the field in the form at the bottom of the page:
`<input class="lead center" type="hidden" name="org_status" value="biz"/>`
and here's the one in the popup:
<input class="lead center" type="hidden" name="org_type" value="business"/>

Seems like we want both fields to be named "org_status" with value "business", correct?

**Comment by MaxTattenbach** [comment]
@dannypernik 

Neither forms for biz signup seem to be working now


![image](https://user-images.githubusercontent.com/26234440/34284114-4ffeeb88-e695-11e7-862e-2d0e75fa7085.png)
