### ISSUE TITLE
live-dashboard:  Incorrect status message showing up. Says volunteered is already enrolled when not.  Functionality on back-end working fine.  

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#891]
No new volunteers can be invited once event is created. 

![image](https://user-images.githubusercontent.com/26234440/34274934-97596542-e660-11e7-9c6e-d2a66e025e8f.png)

**Comment by MaxTattenbach** [comment]
@nickolashe admins are now able to invite volunteers from live dashboard although the status message is incorrect.  I suggest the following. 

When the volunteer is not already registered at the event and added through live-dashboard the status message should be.  
"volunteer successfully added to the event, please refresh the page to check volunteer in".  Note that volunteers aren't appearing until the page is refreshed. 

 Keep the same message as below when the volunteer is already logged in. 

![image](https://user-images.githubusercontent.com/26234440/34323406-f1081f72-e80c-11e7-8618-0541fa31d8e6.png)

**Comment by nickolashe** [comment]
@MaxTattenbach:
1. i am not sure i am following, are you saying new volunteers don't show up in the list after adding them in the top form?
2. have you confirmed that all currents are assigned as expected? we don't have unit tests for this view yet so we have to resort to testing everything manually in this case.

**Comment by MaxTattenbach** [comment]
@nickolashe this is working fine now.  Volunteers are appearing on the live dashboard after adding them without the need to refresh the page. 

Yes, Currents are being added successfully in the ecosystem. 

I
