### ISSUE TITLE
Email Template New NPF invited to through time tracker. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#897]
@dannypernik  note the email template coming to Admin and Biz Dev when volunteer records hours selecting new npf.  This info is insufficient for us to do anything on the backed as assign pending Currents, etc.   I believe you had created the proper templates. 

Also please include the email of a volunteer in template to biz dev not only name - not sure we will be able to find volunteer in database by name especially if name is repeated.

![image](https://user-images.githubusercontent.com/26234440/34284263-3f41b900-e696-11e7-9aeb-ad284edd6e53.png)

![image](https://user-images.githubusercontent.com/26234440/34284288-690a1f3e-e696-11e7-9e92-dde0c696c50b.png)

**Comment by dannypernik** [comment]
@nickolashe I'll need to add variables for time-tracker fields description of work, date, start time, end time, organization name (typed into textbox after "Request other org" clicked), and suggested admin name and email. I also need to add logged in user's email, would that be `self.request.user.email`?

I'm thinking I can add this to `email_vars` PR and try to get this and volunteer-confirmation email sending.

**Comment by nickolashe** [comment]
@dannypernik {{ user.email }}

**Comment by dannypernik** [comment]
@nickolashe I'm trying to set variables in views.py to pass into email template.

**Comment by dannypernik** [comment]
@nickolashe

**Comment by nickolashe** [comment]
missed this one earlier. it's all in `form_data` @dannypernik, see implementation of `track_hours` in TimeTrackerView

**Comment by dannypernik** [comment]
This one has more to it than I realized so creating a new issue #1002 for clarity and assigning to Kostya.
