### ISSUE TITLE
live-dashboard: Make first and last name optional

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#902]
We'll need to change the registration list to display email if first + last are not present. (Similar to see-invitees popup on event-detail)

**Comment by nickolashe** [comment]
@dannypernik could you provide a use case for this request? would admin only have access to user's email here?

**Comment by nickolashe** [comment]
currently, live-dashboard is set up to use `UserSignupForm`, which requires names.

**Comment by dannypernik** [comment]
Ok @nickolashe let's not worry about this now. Use case is an admin who has multiple new volunteers wanting to be checked in and doesn't want to type so much on phone.
