### ISSUE TITLE
Time-tracker: Lets not display in the dropdown those admins who have not yet been granted admin access.

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#903]
@tevtonez note that the admins which are have not yet been granted admin access are being displayed in the drop-down. The were added to drop down when selecting someone else.   

Note this is not a top priority. 

![image](https://user-images.githubusercontent.com/26234440/34328630-8183a9c6-e8a9-11e7-846a-33c62d6f742e.png)

**Comment by tevtonez** [comment]
@nickolashe please review this change, and let me know if we should create a separate view for this case only (I'm not sure if this filter works for other possible cases in the app).

**Comment by nickolashe** [comment]
@tevtonez:
1. added a comment on that commit
2. not sure what you mean by a separate view here

**Comment by MaxTattenbach** [comment]
@tevtonez  This seems to be working!
