### ISSUE TITLE
Complete use cases

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#905]

**Comment by dannypernik** [comment]
@nickolashe is this specific to live dashboard?

**Comment by nickolashe** [comment]
yes, hence the choice of the epic

**Comment by dannypernik** [comment]
@nickolashe want to verify that these use cases are complete?
https://docs.google.com/spreadsheets/d/15mnrkl4Rc5dsFX8VAGOeuPPfCQTPHyOWV1SVwkXIqNQ/edit#gid=1471884877

**Comment by nickolashe** [comment]
@dannypernik i am not sure i am following completely. 

1. when you say "registered", do you mean registered to the event or to oC?
2. are you differentiating between the cases where the volunteer exists on the platform and not?

**Comment by nickolashe** [comment]
@dannypernik

**Comment by dannypernik** [comment]
@nickolashe:
1. "Registered" means registered to an event, I've adjusted the descriptions to be more explicit
2. I've now added use cases for existent and nonexistent users: https://docs.google.com/spreadsheets/d/15mnrkl4Rc5dsFX8VAGOeuPPfCQTPHyOWV1SVwkXIqNQ/edit#gid=1471884877
