### ISSUE TITLE
invite-volunteers: Parse all valid emails from bulk-email and single-email fields

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#906]
make sure email is received

**Comment by nickolashe** [comment]
@tevtonez can we make sure this is handled properly on the backend? i am seeing the following discrepancies in the old functionality in production:
1. a separate user is created for both names and emails (if those are space separated)
2. for the user created from email <> is not removed from the email address, if provided

**Comment by MaxTattenbach** [comment]
@nickolashe  I have increased the level of priority of the issue.  Note that email addresses between <> are not being received/invited.  This is the main format that Gmail uses and most everyone using the copy paste function will be using this format.

**Comment by nickolashe** [comment]
Got it. This will also mean we’ll need to “replay” this step in production once the fix is pushed.

**Comment by tevtonez** [comment]
@nickolashe I see on master it's implemented like this: https://github.com/opencurrents/opencurrents/blob/master/openCurrents/views.py#L1684
Basically, backend takes anything that user enters into text area, splits it by commas and doesn't distinguish names from emails.

if we're going to implement `username <user@email.com>` thing, we have to cover at least 3 options 
```John Snow <mrsnow@snow.com>
Snow <js@snow.com>
js@snow.com```
so the possible regex would look like 
```(?:([^<>\s]+)(?: )([^<>\s]+)(\s<[^<>]+@[^<>]+>))|([^<>\s]+) <([^<>]+@[^<>]+)>|([^<>]+@[^<>]+)```

please, let me know if we're going to implement it this way, thanks!

**Comment by nickolashe** [comment]
@tevtonez i think the primary use case is when they copy email list from gmail, which means it may be 1 and 3 above + <email> alone

**Comment by nickolashe** [comment]
what about current implementation in develop? i think its doing the same thing? lets implement the proper way in develop considering the above three options i mentioned.

**Comment by MaxTattenbach** [comment]
@nickolashe let me know once this has been merged and where to test.  Will we be testing in develop?

**Comment by nickolashe** [comment]
@MaxTattenbach in develop

**Comment by MaxTattenbach** [comment]
@nickolashe @tevtonez functionality is working properly.   Thanks @tevtonez

**Comment by MaxTattenbach** [comment]
@nickolashe @tevtonez  seems that this was also implemented in the invite volunteers from events which is proper functionality.    Great!

**Comment by MaxTattenbach** [comment]
@nickolashe  not sure what I am supposed to test here?

**Comment by dannypernik** [comment]
@MaxTattenbach all valid emails should be extracted from text, regardless of what is typed, and create users/send emails to those users. You can start by copying an email list from Gmail.

**Comment by nickolashe** [comment]
Yes that would be a good way to test

**Comment by MaxTattenbach** [comment]
@nickolashe @dannypernik, this had been tested before and was working properly hence I closed it. 

@dannypernik why did you re-open issue?

**Comment by MaxTattenbach** [comment]
@dannypernik  I retested and its working fine.   I'll go ahead and close.  Please reopen if you can replicate the issue.
