### ISSUE TITLE
Org-Admin:  Can't enter into approve hours as a admin. Can't approve hours as an admin. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#907]
I have sent hours from "max costas" for approval to max gmail dot but can't approve as admin.  Note that the approve hours button is not blue. 

![image](https://user-images.githubusercontent.com/26234440/34371632-6e768cbc-ea94-11e7-81a9-f09bd80e9cd7.png)

![image](https://user-images.githubusercontent.com/26234440/34371656-a29af7d0-ea94-11e7-9567-0951800993a3.png)

**Comment by nickolashe** [comment]
Hmm.. any ideas @tevtonez?

**Comment by tevtonez** [comment]
@nickolashe it appeared that context variable name has been changed in views but wasn't updated in the template

**Comment by nickolashe** [comment]
@tevtonez nice catch, thanks!

**Comment by tevtonez** [comment]
sure thing!
