### ISSUE TITLE
live-dashboard: Manually enter names/emails of registrants from lunch meeting

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#91]
The lunch group will all be added under Linda's event. I've created Karen's event in production. I also added my friend Curry, who has agreed to come volunteer, to Linda's event. Unless we get some emails from Karen, I don't know that we'll have anyone for her to check in. Max will be attending at her site, however. I'll add him to Karen's and me to Linda's.

**Comment by dannypernik** [comment]
I've added users from the lunch group. I will continue adding any names of friends who wish to join.

**Comment by nickolashe** [comment]
@dannypernik Can we close this?
