### ISSUE TITLE
Change Logo

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#914]

**Comment by dannypernik** [comment]
@MaxTattenbach looks like #916 is in 2 different epics. Is Epic #917 all MVP? Let's separate MVP and non-MVP into separate epics, and select milestones for the epics themselves (as you've done here but not in 917)

**Comment by MaxTattenbach** [comment]
@dannypernik I was trying to create epics based on themes. independent of MVP or not. If not MVP it would say no MVP.   But I guess we can create separate epics.

**Comment by nickolashe** [comment]
i think it may make sense to keep epics independent but instead use releases to track time-wise. i am thinking it can be useful to have the entire context when looking at an epic.
