### ISSUE TITLE
Change oC logo on all email templates.   

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#916]
@dannypernik, I believe all email templates have the old logo. 

@nickolashe @dannypernik   are we in agreement of making the o smaller inside the C?   I think new version of logo is looking better.

**Comment by dannypernik** [comment]
@nickolashe are you good with this logo?
<img width="788" alt="screen shot 2017-12-17 at 7 28 46 pm" src="https://user-images.githubusercontent.com/3347095/34503259-02b2440a-efdd-11e7-94e0-2a106da4f3ce.png">

**Comment by nickolashe** [comment]
yep, thx

**Comment by nickolashe** [comment]
what's the status here?

**Comment by dannypernik** [comment]
done now
