### ISSUE TITLE
After successfully nominating an org the status message shows in red - should be green.  Emails are not being sent and incorrect status message now appears.

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#919]
![image](https://user-images.githubusercontent.com/26234440/34425894-75707a2e-ebf6-11e7-909f-ee632ba0ce43.png)

**Comment by nickolashe** [comment]
@dannypernik are you planning to work on this or is it @tevtonez ?

**Comment by dannypernik** [comment]
@nickolashe I've discussed this some with @tevtonez. He suggested adding an entry to urls.py for templates where msg_type needs to be set (essentially any page we want a green message to display). Ex: `url(r'^profile/(?P<status_msg>.*)/(?P<msg_type>.*)$'`

Is this the optimal implementation for green vs red status messages?

**Comment by tevtonez** [comment]
As per discussion with @nickolashe  we're changing default messages to green and will take care of red messages by adding code to url for tracking `msg_status` flag

**Comment by tevtonez** [comment]
this should be fixed in PR #964

**Comment by MaxTattenbach** [comment]
@tevtonez it seems that there is an error with status message and logic.  I nominated a new org from http://openc.herokuapp.com/nominate and the incorrect status message came up.  The org does not exist on the database and status message says it does.  Emails to biz dev were not sent which they should have. 

![image](https://user-images.githubusercontent.com/26234440/34645856-09aad6f2-f31e-11e7-9f19-e980f4c10603.png)

![image](https://user-images.githubusercontent.com/26234440/34645861-1c5bef2a-f31e-11e7-9bc8-88066e2069ce.png)

**Comment by nickolashe** [comment]
@tevtonez @MaxTattenbachnot sure if this is related to the merge issue - I commented re: merge on #967

**Comment by tevtonez** [comment]
fixing along with #926 in 4a6645d

**Comment by tevtonez** [comment]
ok, so we always send email to bizdev if the org isn't registered in the system.
and the messages should appear in the green color if org is nominated successfully.

**Comment by nickolashe** [comment]
@MaxTattenbach is the status correct? could you comment what's left here, if anything?

**Comment by nickolashe** [comment]
@MaxTattenbach @dannypernik continuation of work on this task is pending review of the use cases, put together here:
https://docs.google.com/spreadsheets/d/15mnrkl4Rc5dsFX8VAGOeuPPfCQTPHyOWV1SVwkXIqNQ/edit?ts=5a3acf6c#gid=1026415208

**Comment by MaxTattenbach** [comment]
@nickolashe  thanks, I have completed them.

**Comment by tevtonez** [comment]
the functionality is fixed in 67ec3db, except sending emails to invited admins (seems like the template doesn't exist in mandrill)

**Comment by dannypernik** [comment]
@tevtonez https://github.com/opencurrents/opencurrents/commit/67ec3db0a9c0949bb8f58938ccf0c92042e1d4bf
