### ISSUE TITLE
Org Sign-up:  Improper functionality on org sign-up when accessed from home - join as Nonprofit

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#923]
This error is only happening when using the bottom form of opencurrents.com/nonprofit  which is also accessed from home clicking register a nonprofit.    The top form of opencurrents.com/nonprofit is working properly. 

@dannypernik @nickolashe note that Org user is being created in DB but with no affiliation.   I had registered Costas Verdes as npf on sign up, and when visiting "Orgs" it appeared with no affiliation.  Although when clicking on the particular org it appeared to be registered with biz.  When changing org from biz to npf, the user was proper functionality was achieved. . 

![image](https://user-images.githubusercontent.com/26234440/34426554-7e7cea06-ebfd-11e7-81ce-18d27f21321e.png)

![image](https://user-images.githubusercontent.com/26234440/34426265-2e5aa9ee-ebfa-11e7-9d0a-2dd3c128a441.png)

Below:  Costas Verdes had originally no affiliation with Orgs - this is after changing it. 

![image](https://user-images.githubusercontent.com/26234440/34426637-41831dae-ebfe-11e7-8bf2-ea211fa570ab.png)

**Comment by dannypernik** [comment]
@MaxTattenbach made a change, can you check this?

**Comment by dannypernik** [comment]
@MaxTattenbach @nickolashe note that issues can be assigned multiple releases, though I don't think we want that.

**Comment by nickolashe** [comment]
that's correct, we don't want that

**Comment by MaxTattenbach** [comment]
Sign up form is working properly now.
