### ISSUE TITLE
Nominate Org - Creating a way to invite businesses. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#925]
@dannypernik how about if we change the language so users can invite businesses as well.  I would think its more likely that users know more folks related to businesses over nonprofits. 

![image](https://user-images.githubusercontent.com/26234440/34426771-9b7dd76c-ebff-11e7-8fbc-f2cf9b511f7e.png)

**Comment by dannypernik** [comment]
@MaxTattenbach pushed to develop branch.

**Comment by MaxTattenbach** [comment]
@dannypernik  Lets change to the side bar as well.  It say nonminate and org.  I doubt anybody referes to businesses as "org".   

How about: "Let's grow - Invite biz or Org."

**Comment by dannypernik** [comment]
Made changes in develop. That suggestion for the menu will not fit. I used "Grow the community"
