### ISSUE TITLE
Invite Volunteers bulk and individual (non-event based):  We should change the logic so only those that have password don't receive invitation.

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#928]
Note that currently, volunteers that have been previously invited and didn't create a password are not receiving the invitation.

**Comment by nickolashe** [comment]
@MaxTattenbach are you saying the logic is flipped here?

**Comment by MaxTattenbach** [comment]
@nickolashe I think logic could be improved.  Currently, any existing email in the database doesn't receive emails from invite volunteer (non-event based).  I believe the proper functionality should be to not email volunteers which already have created a password.

**Comment by nickolashe** [comment]
ok, so send to those without password and do not send to those with password then?

**Comment by nickolashe** [comment]
@MaxTattenbach

**Comment by dannypernik** [comment]
@nickolashe yes that's my understanding

**Comment by MaxTattenbach** [comment]
@tevtonez a few things. 

When inviting volunteer (non-event based)  from the drop-down menu of the profile of org admin. 

1.  When Volunteer being invited is not in DB. 
Proper email is being sent.    invite-volunteers

2. When volunteer being invited is in DB and has no password
The wrong email template is being sent.  It should send invite-volunteers  it is currently sending  invite-volunteers-event-existing.  

Note in this case the admin is inviting to volunteer to openCurrents not to an event.

3. When volunteer being invited is in DB and has a password.
No email should be sent.  This is working properly.

**Comment by nickolashe** [comment]
Looks like 1 out of 3 use cases needs a slight tweak
