### ISSUE TITLE
Event-Detail: Error upon sending message through event detail. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#929]
@nickolashe note that email are coming into admin successfully it's just the post state that displays the error. 

![image](https://user-images.githubusercontent.com/26234440/34427798-c6d48daa-ec0b-11e7-87a2-ebabd84b2e0f.png)

![image](https://user-images.githubusercontent.com/26234440/34427782-a617537c-ec0b-11e7-9e14-fff10cfe49a9.png)

![image](https://user-images.githubusercontent.com/26234440/34427779-8c385852-ec0b-11e7-9d23-df87746cd63e.png)

**Comment by nickolashe** [comment]
@tevtonez @dannypernik i suspect it has to do with the recent changes. any ideas?

**Comment by tevtonez** [comment]
@nickolashe this issue should be fixed in 60de095

**Comment by nickolashe** [comment]
@MaxTattenbach in develop

**Comment by MaxTattenbach** [comment]
@nickolashe @tevtonez, this is working properly will close.
