### ISSUE TITLE
Event-Detail:  Create status message when no text in box and volunteer wants to contact admin. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#930]
Blank email is NOT being sent to admin which is proper functionality although we should let the volunteer know.

**Comment by nickolashe** [comment]
@dannypernik this should be as simple as adding a status message div to event-detail, which currently appears to be missing. i am not sure what the current way of doing this is, so reassigning to you.

**Comment by nickolashe** [comment]
@dannypernik

**Comment by dannypernik** [comment]
@nickolashe this should be inheriting(?) the block from layouts/base.html. This is one of the pages that has been refusing to display status message for awhile now.

**Comment by MaxTattenbach** [comment]
@nickolashe note that status message is green and should be red.
