### ISSUE TITLE
Hours Detail and Profile: Date description using Server Time.  Entries in the late evening use the display next day date. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#931]
@nickolashe events and time logs created in the evening are being picked up on "hours-details' and time logs with server time.   All of the hours you see below are of 12/28  and show up as 12/29. 

I am ok to leave for post MVP not a big issue. 

![image](https://user-images.githubusercontent.com/26234440/34428033-0edab3a2-ec0e-11e7-8912-370922104f69.png)

![image](https://user-images.githubusercontent.com/26234440/34428035-1c4494b8-ec0e-11e7-9c55-b2c359f247e2.png)

**Comment by nickolashe** [comment]
@MaxTattenbach i see the screenshot from hours-detail. can you clarify re: profile pls.

**Comment by MaxTattenbach** [comment]
@nickolashe will reproduce check and come back on this one.

**Comment by MaxTattenbach** [comment]
![image](https://user-images.githubusercontent.com/26234440/34581212-45b24cfe-f155-11e7-9b61-6af5565f682b.png)


![image](https://user-images.githubusercontent.com/26234440/34581186-2e2d016e-f155-11e7-884c-a6e68d084500.png)

**Comment by nickolashe** [comment]
@tevtonez 
this change should be as simple as applying the correct tag to the event start time here:
https://github.com/opencurrents/opencurrents/blob/develop/openCurrents/templates/hours-detail.html#L56

For example, see:
https://github.com/opencurrents/opencurrents/blob/develop/openCurrents/templates/profile.html#L85

**Comment by nickolashe** [comment]
While we are at it, lets also change the number of decimal places shown for hours from 3 to 2:
https://github.com/opencurrents/opencurrents/blob/develop/openCurrents/templates/hours-detail.html#L87

**Comment by MaxTattenbach** [comment]
@tevtonez This happens after manually tracking hours in the evening.

When admin goes to approve hours it displays the wrong day with correct time.   (see Test Time #2)  URL Hour Detail is displaying correctly the date. 

![image](https://user-images.githubusercontent.com/26234440/34644466-d9b63854-f2fc-11e7-9936-cde147c57241.png)

![image](https://user-images.githubusercontent.com/26234440/34644477-0ab1c23e-f2fd-11e7-8943-206591d0a2ad.png)

**Comment by MaxTattenbach** [comment]
@tevtonez this is working properly
