### ISSUE TITLE
live-dashboard:  Let's change status message after adding volunteer in upcoming event.  

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#932]
The status message is currently red as if it was an error, lets change to green.   

I suggest it says:  Successfully invited volunteer to the event, you must check him/her in at the event or after the event to record his/her hours. 

![image](https://user-images.githubusercontent.com/26234440/34429051-8f9accf2-ec18-11e7-9007-6924ad9de8b6.png)

**Comment by nickolashe** [comment]
@MaxTattenbach can you elaborate on the relationship to #935 pls

**Comment by dannypernik** [comment]
@nickolashe looks like #935 is not related to the status message but to keeping the checkbox checked.

**Comment by nickolashe** [comment]
@MaxTattenbach @dannypernik now that "add volunteer" button has been disabled outside of the event timeframe, what's the plan of action with this one?
