### ISSUE TITLE
live-dashboard:  Incorrect email is being sent from live dash board when selecting the box. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#933]
@dannypernik  I think we should use invite volunteer template. 

![image](https://user-images.githubusercontent.com/26234440/34429164-f96a13f8-ec19-11e7-8a0d-fa51ab32e259.png)

![image](https://user-images.githubusercontent.com/26234440/34429158-e1876ce0-ec19-11e7-8d4c-38322ce62659.png)

**Comment by nickolashe** [comment]
https://github.com/opencurrents/opencurrents/blob/develop/openCurrents/views.py#L3090

**Comment by dannypernik** [comment]
@nickolashe not understanding the relevance of the link above. I believe the issue is inside the JS of live-dashboard:

```
let invite_optin = $('#invite-optin').prop('checked');
          let process_signup_url;

          if (invite_optin) {
            process_signup_url = "{% url 'openCurrents:process_signup' endpoint=True verify_email=True %}"
          }
          else {
            process_signup_url = "{% url 'openCurrents:process_signup' endpoint=True verify_email=False %}"
          }
```

process_signup sends verify-email template instead of invite-volunteer.

**Comment by nickolashe** [comment]
@dannypernik that's not true, please check out the implementation:
https://github.com/opencurrents/opencurrents/blob/develop/openCurrents/views.py#L3263

**Comment by nickolashe** [comment]
most likely will need to be carried over to the next release
