### ISSUE TITLE
live-dashboard:  Incorrect status message - when selecting box invite box when user already has oC account. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#934]
@dannypernik  @nickolashe   Seems to me that correct functionality should be.  If invited volunteer already has oC account with password and check box is selected then add volunteer below but do not send an invitation. 

If a volunteer doesn't have password or email then it should send an invitation upon clicking the box. 

Post States: 

Selecting box
![image](https://user-images.githubusercontent.com/26234440/34429287-dbc949ca-ec1b-11e7-89d8-e980bff9c31b.png)

Not Selecting Box
![image](https://user-images.githubusercontent.com/26234440/34429395-46023c88-ec1d-11e7-9d8c-7fd1eeb12860.png)

**Comment by nickolashe** [comment]
@MaxTattenbach closing the issue since i believe its the union of #1014 and #1017
