### ISSUE TITLE
Event-Detail: See Invitees pop-up not displaying those users that were invited through live dash-board. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#937]
@nickolashe note that accounts in DB are being created through live-dashboard which is proper functionality.  But the see invitees seems to be pointing at those that were invited through the invite volunteer form and not through live dash board.  See Invititees should be pointing to the complete list shown in on live-dashboard. 

![image](https://user-images.githubusercontent.com/26234440/34429683-02566f78-ec21-11e7-8c6d-1a9e1b22daeb.png)

![image](https://user-images.githubusercontent.com/26234440/34429614-2d86491c-ec20-11e7-9be7-e2a2d659546f.png)

![image](https://user-images.githubusercontent.com/26234440/34429632-830fc6e2-ec20-11e7-9915-0195b4fe9312.png)

**Comment by nickolashe** [comment]
note: check if we are registering live-dashboard users to the event

**Comment by tevtonez** [comment]
@nickolashe excluding line from filter https://github.com/opencurrents/opencurrents/blob/develop/openCurrents/views.py#L2385 
will allow admins to see all invited users. Let me know if you want me to proceed.

**Comment by nickolashe** [comment]
@tevtonez are you sure you referenced the correct issue in https://github.com/opencurrents/opencurrents/commit/008a9fd3419a36af28c7655eab4b8706b48d8121

**Comment by nickolashe** [comment]
@tevtonez i am not sure whether you mean excluding all of https://github.com/opencurrents/opencurrents/blob/develop/openCurrents/views.py#L2382-L2385?

i think we should rather register the users to the event when they are added from live-dashboard

**Comment by tevtonez** [comment]
@nickolashe I've been thinking of removing one line `is_confirmed=True` line from filter to show all confirmed and not-confirmed user registration to events
Or is it better to create a 'confirmed' user UserEventRegistration object when a volunteer is invited from live-dashboard?

**Comment by nickolashe** [comment]
@tevtonez yes, lets create a confirmed one since the user showed up at the event in this case.

**Comment by MaxTattenbach** [comment]
@nickolashe @dannypernik  Let's discuss if it should we just inhibit adding volunteers though live dashboard if the event is not live.

**Comment by MaxTattenbach** [comment]
@nickolashe per agreed.   Lets actually block the add volunteer button before your actually allowed check-in volunteers.  Nicko perhaps you have to point Kostya to this variable.  I believe it one hour before event but I am not sure.   

@tevtonez please take a look at this functionality. 

Proper functionality.
1. Volunteers can't be added to an event via live-dash board until admin is allowed to check them in. 
2.  If admin adds volunteers via live dash-board no invitation or email is sent unless the checkbox is clicked.
3.  If Admin tries to add volunteer before it can check in volunteers then the following error/status message should display:  You may only add-volunteers via live-dash board during or after the event.  To invite volunteers to the event please use invite volunteers.

**Comment by nickolashe** [comment]
@tevtonez let’s proceeds based on the above spec

**Comment by nickolashe** [comment]
As far as registering users to the event through live-dashboard, it appears we are already doing so:
https://github.com/opencurrents/opencurrents/blob/develop/openCurrents/views.py#L2940

**Comment by nickolashe** [comment]
So let’s leave event registration topic outside of scope

**Comment by dannypernik** [comment]
@nickolashe @tevtonez we'll want to include a link to invite-volunteers in status message. To shorten the status msg a bit, let's use "To invite volunteers before event begins, please visit `<a>Invite volunteers</a>` page."
Note that we will need to pass event ID into link.
