### ISSUE TITLE
Email from Invite Volunteer when existing Volunteer is in DB

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#938]
@dannypernik  I suggest we change the language of these emails.  

Current: openCurrents rewards you for giving time to Costas Verdes and other social organizations. Log in to confirm your attendance:  [RSVP]

Suggested: You can earn Currents by volunteering with Costas Verdes and other social organizations.  This event has been added to your dashboard.  Don't miss out!  [See Event Details]

I don't think the RSVP has been implemented. 

![image](https://user-images.githubusercontent.com/26234440/34429791-90a2c33e-ec22-11e7-8c3a-c32bed1fa1de.png)

**Comment by dannypernik** [comment]
@MaxTattenbach edited the text as you suggested. RSVP is in fact implemented - button on event details says "Register" and it notifies coordinator when someone registers.
