### ISSUE TITLE
Invite Volunteers Event based when user has not been created. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#939]
@dannypernik  same let's shy away from using language that openCurrents rewards.   How about. You can earn Currents by volunteering with Costas Verdes and other nonprofits.  Currents can be exchanged with businesses as payments.  Create your account today and earn Currents for volunteering with 
[Yes, im in]

![image](https://user-images.githubusercontent.com/26234440/34429872-ad339ba8-ec23-11e7-94c6-6013cda58077.png)

**Comment by dannypernik** [comment]
@MaxTattenbach I worked off your version:

openCurrents is a community that values social action like never before. Earn Currents for giving time to *|ORG_NAME|* and other social organizations. Then visit the marketplace to use Currents with participating businesses. Create your account and start today!

I tried "Yes, I'm in" but decided "Join openCurrents" worked better in this instance.

**Comment by MaxTattenbach** [comment]
@dannypernik thanks!
