### ISSUE TITLE
Hour Detail - Should be ordered by date with nearest date on top. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#940]
![image](https://user-images.githubusercontent.com/26234440/34430036-eb7729b4-ec25-11e7-8840-13a0818ca576.png)

**Comment by tevtonez** [comment]
@nickolashe it seems that sorting by event eliminates the confusion, since we're showing event dates on that pagen(06cb487)

**Comment by nickolashe** [comment]
@MaxTattenbach in develop

**Comment by MaxTattenbach** [comment]
THis is working properly will close

![image](https://user-images.githubusercontent.com/26234440/34582669-583e6cf4-f15a-11e7-928d-235d570c25c2.png)
