### ISSUE TITLE
Market Place:  Let's show no detail have been added when a biz hasn't added details and volunteer clicks on show detail.  Currently just blank.

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#944]
![image](https://user-images.githubusercontent.com/26234440/34440359-56ef500a-ec7a-11e7-9ee9-fcbdf44f9e75.png)

**Comment by dannypernik** [comment]
@nickolashe we currently have 5 separate `if` statements for `if org.phone`, `if org.email`, etc. In order to accomplish what Max is suggesting, do we need a statement such as `if not org.phone or org.email or org.website...`?

**Comment by nickolashe** [comment]
`if not (org.phone or org.email or ... )`

**Comment by nickolashe** [comment]
@dannypernik the way you wrote it does not achieve what we want.

**Comment by dannypernik** [comment]
@nickolashe got this error when trying to add 'if not (org.phone or org.email ...)` see bottom of error image to see the code I tried.

<img width="959" alt="screen shot 2018-01-10 at 3 25 23 pm" src="https://user-images.githubusercontent.com/3347095/34796262-885b4302-f61a-11e7-877b-fde6a986f671.png">

**Comment by nickolashe** [comment]
which branch is this on @dannypernik ?

**Comment by dannypernik** [comment]
@nickolashe `no_biz_deets`

**Comment by nickolashe** [comment]
Which is logically equivalent
