### ISSUE TITLE
Cash-out Pop-up:  Let's change language. Also note that it says click "redeem" we no longer have that link. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#945]
Original:
No dollars available
You do not yet have dollars available to transfer to your bank account. If you have redeemed an offer and have pending dollars in your account, you'll need to wait until the business verifies your proof of purchase at the end of the month.
To see offers from businesses in the community, please visit the marketplace by clicking "Redeem" in your profile.

Suggested:
No Available Dollars  (I would use capitals because "Available Dollars" is a term that we define)

You will need Available Dollars to be able to transfer to your bank account or to donate them back to your favorite nonprofit. If you have redeemed an offer and have Pending Dollars in your account, you'll need to wait until the business verifies your proof of purchase at the end of the month.
To see offers from businesses in the community, please visit the marketplace by clicking "Market Place" in your profile.

![image](https://user-images.githubusercontent.com/26234440/34441326-8f8fc6aa-ec80-11e7-9aff-dc8b6a0b5dcb.png)

**Comment by dannypernik** [comment]
<img width="902" alt="screen shot 2018-01-03 at 11 48 31 pm" src="https://user-images.githubusercontent.com/3347095/34551561-c726ae08-f0e0-11e7-91c8-e37f946a621a.png">
