### ISSUE TITLE
Admins are being blocked when more than one org admin has admin privileges. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#946]
This happened when inviting new admin through "someone else" and then giving the new admin, admin privileges.  I tested providing admin privileges both before creating the new admin password and after.  

Both admins can't access org-admin profile when another admin is associated.

Once I remove admin privileges from either admin the other admin is able to access org-admin profile 

![image](https://user-images.githubusercontent.com/26234440/34442720-9388e9ae-ec89-11e7-9ed2-7bac34afd369.png)

This is what displays when another admin has admin privileges. 

![image](https://user-images.githubusercontent.com/26234440/34442465-ffbc4410-ec87-11e7-9596-ed881bf83e19.png)

**Comment by tevtonez** [comment]
fixed in c9a3504

**Comment by MaxTattenbach** [comment]
@tevtonez @nickolashe functionality seems to be working properly now.
