### ISSUE TITLE
Time Tracker:  Missing Status message when Requesting Currents from another organization and email is associated with an org. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#947]
@tevtonez note that email is not being sent to either biz dev or admin which is CORRECT functionality although we should have a status message.  Same messages in "someone else" should be present under "request Currents from another organization"

Currently, post state after submitting just refreshes the form. 

Status message should only appear with emails that are associated with orgs and have already been granted admin status.   Note this is how it is Currently working just that its not displaying status message.

**Comment by tevtonez** [comment]
@MaxTattenbach this is what I see on dev currently:
![screenshot 2018-01-03 09 42 24](https://user-images.githubusercontent.com/343347/34513813-6ba1d11e-f06a-11e7-9f01-f3840d19ce31.png)

![screenshot 2018-01-03 09 40 41](https://user-images.githubusercontent.com/343347/34513792-45c71102-f06a-11e7-9e04-cefc98777148.png)

Could you, please, provide steps to reproduce, if the issue persists? Thanks!

**Comment by MaxTattenbach** [comment]
@tevtonez  You're right!   I'll close.   Also seems that the form is recognizing capitals!

**Comment by MaxTattenbach** [comment]
@tevtonez  I was testing if status message was appearing when adding an existing admin with CAPS lock and it's not.  Then I noticed that status message is no longer appearing in "someone else"  or "Request Currents from another organization"  With or without caps lock. 

I'll add to Tested needs work.

Could you please retest?

**Comment by tevtonez** [comment]
@MaxTattenbach 
I tested it on kostya_profile_additions and develop branch and cannot reproduce:
here are some screenshots:
requesting hours from new NPF with existing admin email with CAPS:
![screenshot 2018-01-05 11 27 40](https://user-images.githubusercontent.com/343347/34605402-ca8924b4-f20b-11e7-8a2d-43f6b3122530.png)
result:
![screenshot 2018-01-05 11 27 46](https://user-images.githubusercontent.com/343347/34605401-ca6519f2-f20b-11e7-8a7e-5de74f081af0.png)

the result of requesting hours from existing NPF with existing admin email with CAPS as _someone else_:
![screenshot 2018-01-05 11 15 21](https://user-images.githubusercontent.com/343347/34605458-ffe9b0e2-f20b-11e7-881c-ed9823f7bbdb.png)

I got same results for emails with no caps lock...

**Comment by MaxTattenbach** [comment]
@tevtonez - thanks seems to be working good!
