### ISSUE TITLE
Time-tracked: When coming from "Request Currents from another organization" message should be difference. I suggest two different URLs

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#948]
Note it really isn't time tracked - but suggested to be tracked.  Since we removed the Currents being created we should say something like. 

A request for Currents has been received - once we verify the organization your hours will be converted to pending Currents and once the admin approves the hours you will have available Currents. 

Thanks for making this world a better place. 

![image](https://user-images.githubusercontent.com/26234440/34444024-ad8d3e20-ec90-11e7-8254-d8e8579515a5.png)

**Comment by dannypernik** [comment]
@MaxTattenbach I think this confirmation message is still accurate. @nickolashe do you see a straightforward way we could add a var to this page if user clicks "Request Currents from another org"? Using different URLs would require changing the ref with JS.

**Comment by nickolashe** [comment]
yes, we can add a var

**Comment by MaxTattenbach** [comment]
Right proposed language

**Comment by dannypernik** [comment]
@nickolashe would you like to start a branch for the var or add on develop and let me know what it is, then I can change the wording? I guess the var needs to be set on time-tracker based on whether time is sent to new or existing org.

**Comment by nickolashe** [comment]
@dannypernik #1009
