### ISSUE TITLE
Invite Admin: from "Request Currents from another Organization", email should be changed.

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#949]
Note that we are using the same email template for new admin when Org is existent or not existent.  We should create a new template for when org is not yet on openCurrents.

Note that Yahoo is not using openCurrents yet.  

Also, note that there is no way we can add pending Currents on the backend if we don't have those variables in the email biz dev receives.  Hours worked, detail of work, etc.   I am not sure if this is even possible to collect as we are currently not storing info on the info on the DB?   

Let's only address the top issue for MVP if the bottom issue/picture is a hard fix. 

![image](https://user-images.githubusercontent.com/26234440/34444459-f222e7e4-ec93-11e7-8a45-79a1a6d950ff.png)

![image](https://user-images.githubusercontent.com/26234440/34444480-1807be8a-ec94-11e7-89fb-26bb7e5bbea7.png)

**Comment by nickolashe** [comment]
@dannypernik could you pick an estimate

**Comment by MaxTattenbach** [comment]
@nickolashe @dannypernik  I am ok for 1/12 although do note that if users record Currents for new organizations then we will be sending false emails stating that the NGO already tracks hours with openC, when they don't.   

@dannypernik if we could create a simple email template for new orgs that would be quick fix.

**Comment by nickolashe** [comment]
@dannypernik

**Comment by dannypernik** [comment]
email template: volunteer-invites-org

<img width="606" alt="screen shot 2018-01-04 at 11 17 24 pm" src="https://user-images.githubusercontent.com/3347095/34596459-73554b34-f1a5-11e7-8705-cc511aad4f3a.png">

**Comment by nickolashe** [comment]
@dannypernik what's left to be done here?

**Comment by dannypernik** [comment]
@nickolashe we'll need to set up logic in views.py to send `volunteer-invites-org` template when "Request Currents from other organization" is clicked and org name and admin email are populated. Will be similar to this but for new orgs:
https://github.com/opencurrents/opencurrents/blob/develop/openCurrents/views.py#L1268

I don't know how we are detecting when Request new org is selected instead of an existing org. @tevtonez did you work on this logic in JS on time-tracker or in views?

**Comment by nickolashe** [comment]
@tevtonez assigning to you (high priority)

**Comment by tevtonez** [comment]
@dannypernik the logic for this is implemented in views

**Comment by MaxTattenbach** [comment]
@tevtonez  Admin is still receiving improper email. 

To replicate go to time tracker select request Currents from other organization.   New Admin is NOT receiving "volunteer-invites-org"

![image](https://user-images.githubusercontent.com/26234440/34696281-bfa4a8e0-f493-11e7-8279-ae9e9613a90d.png)

**Comment by tevtonez** [comment]
@MaxTattenbach this is the last email I received 14 hours ago when I've been working on this issue. Does it use the correct template?

![screenshot 2018-01-08 23 52 57](https://user-images.githubusercontent.com/343347/34696447-2bc0d4e6-f4cf-11e7-9f1e-9648cafb72a4.png)

**Comment by tevtonez** [comment]
@MaxTattenbach again, this code should be on develop branch: https://github.com/opencurrents/opencurrents/commit/58333455546d61013583b0e2344ee2f1bb60c37b#diff-cdc3208e7bac1d05986424d1285c7fe1R1137

and I don't see it there

**Comment by nickolashe** [comment]
@tevtonez I am not exactly following your last statement, since you linked to a commit from a develop branch. What do you mean you are not seeing it there?

**Comment by MaxTattenbach** [comment]
@tevtonez this working now
