### ISSUE TITLE
delete-offer: keep existing related objects

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#956]

**Comment by nickolashe** [comment]
@tevtonez can you focus on this one next (prior to live-dashboard) pls. ideally, we'd get it out by end of day 1/15.

**Comment by nickolashe** [comment]
use case: https://docs.google.com/spreadsheets/d/15mnrkl4Rc5dsFX8VAGOeuPPfCQTPHyOWV1SVwkXIqNQ/edit#gid=1791551587&range=B10

**Comment by nickolashe** [comment]
delete offer functionality has already implemented on `offer_delete` branch, main thing is making sure existing redemptions remain. possibly, this is as simple as this:
https://stackoverflow.com/questions/38388423/what-does-on-delete-do-on-django-models

**Comment by nickolashe** [comment]
needs a unit test as well

**Comment by tevtonez** [comment]
@nickolashe  as per our discussion this weekend PR #1001

**Comment by MaxTattenbach** [comment]
@nickolashe @tevtonez this working as desired objects are not being deleted when offers are deleted!
