### ISSUE TITLE
Organization already exists status  message to be centered. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#960]
![image](https://user-images.githubusercontent.com/26234440/34578078-4987318e-f149-11e7-978a-51fa76a3f59d.png)

**Comment by dannypernik** [comment]
@MaxTattenbach change made in develop

**Comment by dannypernik** [comment]
@nickolashe @MaxTattenbach I'm moving these status messages to the top of the page with a white background, because the status message was hidden either behind the popup or at the bottom of the page on pageload.

**Comment by tevtonez** [comment]
@nickolashe @dannypernik this is what I see currently:
![screenshot 2018-01-05 11 07 24](https://user-images.githubusercontent.com/343347/34604629-d8e39b5a-f208-11e7-9de8-3de8d0646909.png)
could you please specify what's my role in fixing this issue?

**Comment by dannypernik** [comment]
@tevtonez I took care of this one. Unassigning you
