### ISSUE TITLE
Org Signup: User is being created when trying to register existing org. Proper functionality should be to not create any entry if there is an error in submitting complete form

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#961]
![image](https://user-images.githubusercontent.com/26234440/34578571-150c56b2-f14b-11e7-8c24-bdd10dde43cf.png)

![image](https://user-images.githubusercontent.com/26234440/34578544-02d59e04-f14b-11e7-8b5b-481809a8e97e.png)

**Comment by MaxTattenbach** [comment]
Lets discuss what we want with this functionality.

**Comment by dannypernik** [comment]
Simplest viable option is we don't want a user created in this case. Alternatively, we could create OrgUser under same org and allow user to continue signup. However, there's the possibility that someone could create a 2nd illegitimate account under same business name and gain access to existing offers.

**Comment by nickolashe** [comment]
lets not create the user
