### ISSUE TITLE
Lets increase value of Currents to $20/C

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#963]
@nickolashe and @dannypernik we have been conveying the message that the Currents will be $20/hr to the outer world.  This needs to be changed both in frontend and backend. 

Assigning front end MVP first.

**Comment by MaxTattenbach** [comment]
@nickolashe Note that that transaction fee is actually showing up in the pending $ balance after offer is redeemed

![image](https://user-images.githubusercontent.com/26234440/34679260-0d316aaa-f45b-11e7-8ec8-de450889f880.png)

**Comment by nickolashe** [comment]
Weird, i’ll take a look

**Comment by MaxTattenbach** [comment]
@nickolashe @dannypernik  Currents are worth $20/C.  Will close issue!
