### ISSUE TITLE
Org-Admin:  Hours Pending Approval on Org Admin Profile only displaying when current admin has hours Pending.

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#966]
All Org admins should always be able see hours pending of other admins.  Currently current Admin most have hours pending to see other admins pending hours. 

Note screenshot below is of two admins accounts, in which one has hours pending and the other doesn't. 

![image](https://user-images.githubusercontent.com/26234440/34645686-b72e4af2-f319-11e7-8c2b-c717caf1708b.png)

Now when both admins have hours pending. 

![image](https://user-images.githubusercontent.com/26234440/34645785-17651ef8-f31c-11e7-8381-08f9d801b685.png)

Don't get names confused - there is a Max Tattenbach which is only a volunteer.

**Comment by nickolashe** [comment]
good find @MaxTattenbach

**Comment by MaxTattenbach** [comment]
@tevtonez  See that "Hours pending approval" are not displaying the hours.    Max Costas Tattenbach submitted hours to admin NS from Casa Marianella.    Admin Max Dot Gmail can't isn't displaying those hours. 

![image](https://user-images.githubusercontent.com/26234440/34695222-a20db8b6-f48f-11e7-9a1a-e4428d65305a.png)

![image](https://user-images.githubusercontent.com/26234440/34695263-ca3f4d36-f48f-11e7-84d0-a22fcb88821e.png)

**Comment by tevtonez** [comment]
@MaxTattenbach I cannot confirm the last issue on develop (please see screenshot)
![screenshot 2018-01-08 23 36 38](https://user-images.githubusercontent.com/343347/34695970-290e2ebc-f4cd-11e7-8fbd-d537bc9097e4.png)

**Comment by nickolashe** [comment]
@MaxTattenbach:
1. what do you mean by the last statement there, "Max Costas submitted hours Max Yahoo from Casa Marienella"?
2. do you think you can change your account names to be something more intuitive as to where it will be clear on the role of the user from the name? (i.e. something along the lines of the fixtures produced by the setup script). reason is i find it difficult to trace the logic of the test cases in some instances.

**Comment by MaxTattenbach** [comment]
@nickolashe @tevtonez functionality is working. 

@nickolashe, yes I will start using more intuitive names.
