### ISSUE TITLE
Org-Admin:  Admin of of org is not displaying nothing under Hours Approved until he approves an hour. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#967]
Until NPF admin approves hours is he able to see hours approved in for his NPF.   He should be able to see Hours Approved regardless if he has accepted hours or not. 

![image](https://user-images.githubusercontent.com/26234440/34645727-90aafcb2-f31a-11e7-96a1-1e89c4c491f2.png)

After "Max Tattenbach"  new registered admin approves hour are the buttons displaying under Hours Approved.
  
![image](https://user-images.githubusercontent.com/26234440/34645789-41572e7c-f31c-11e7-99b5-6ad9e3eac31f.png)

**Comment by nickolashe** [comment]
good find @MaxTattenbach

**Comment by MaxTattenbach** [comment]
@tevtonez issues persist.  Current admin needs is not displaying hours pending approval or hours tracked until he has approved or one hour pending.

**Comment by tevtonez** [comment]
@MaxTattenbach @nickolashe it doesn't seem that my code get to develop, this part shouldn't be in views.py
![screenshot 2018-01-08 23 40 54](https://user-images.githubusercontent.com/343347/34696031-6e628a76-f4cd-11e7-961b-7d96f150dd93.png)

**Comment by tevtonez** [comment]
views.py on my branch: https://github.com/opencurrents/opencurrents/blob/kostya_profile_additions/openCurrents/views.py#L1527

views.py on develop:
https://github.com/opencurrents/opencurrents/blob/develop/openCurrents/views.py#L1511

**Comment by nickolashe** [comment]
@tevtonez No diffs between develop and kostya_profile_additions:

https://github.com/opencurrents/opencurrents/compare/develop...kostya_profile_additions?expand=1
