### ISSUE TITLE
Live-dashboard: opt-in checkbox to receive oC invite

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#97]

**Comment by nickolashe** [comment]
@dannypernik What's the status of this one? Are we aiming to have this by tomorrow?

**Comment by nickolashe** [comment]
@dannypernik Can you please associate the PR with the issue to make reasoning easier.

**Comment by nickolashe** [comment]
https://github.com/opencurrents/opencurrents/pull/104
