### ISSUE TITLE
admin-profile: Live event from a different Org is showing in Keep Austin Beautiful's live events

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#98]
Only KAB events should display in live event section. Note that my account is currently associated with Keep Austin Beautiful for testing purposes.
<img width="1205" alt="screen shot 2017-06-09 at 4 14 24 pm" src="https://user-images.githubusercontent.com/3347095/26994782-bc7e70ea-4d2e-11e7-9b47-4cc3ecef8170.png">

**Comment by dannypernik** [comment]
@nickolashe @karbmk in fact, upcoming events have the same problem:
<img width="1207" alt="screen shot 2017-06-09 at 4 16 46 pm" src="https://user-images.githubusercontent.com/3347095/26994841-30b091aa-4d2f-11e7-8a5f-836b29bea1c0.png">

I'm deleting both test events in case one of the admins log in.

**Comment by nickolashe** [comment]
@dannypernik Your accounts is associated with two orgs, KAB and test org, correct?

**Comment by nickolashe** [comment]
@dannypernik I did not quite follow the last statement where you said you are deleting something.

**Comment by nickolashe** [comment]
https://github.com/opencurrents/opencurrents/pull/104

**Comment by dannypernik** [comment]
@nickolashe sorry I didn't get to these sooner but seems we got them sorted out. My account was only associated with one org, for the record
