### ISSUE TITLE
menu: Grow the Community does not fit

### ISSUE THREAD

**Issue by nickolashe** [opencurrents/opencurrents#987]

**Comment by nickolashe** [comment]
<img width="278" alt="screen shot 2018-01-10 at 12 27 02 am" src="https://user-images.githubusercontent.com/6278359/34762566-0c17e61a-f59d-11e7-8953-e348963312ed.png">

**Comment by dannypernik** [comment]
@nickolashe I'm unable to reproduce, even when I zoom into page. Do you have text magnified on your browser? and which browse

**Comment by dannypernik** [comment]
Nvm just found text size setting on Chrome and reproduced. Will push a fix to develop
