### ISSUE TITLE
Lets create a Biz Admin Form in Pop-up, to get businesses adding their details. 

### ISSUE THREAD

**Issue by MaxTattenbach** [opencurrents/opencurrents#989]
Pop should display when accessing biz profile and none of the fields in the form are filled out.

**Comment by MaxTattenbach** [comment]
@tevtonez I created the use case for this one.

https://docs.google.com/spreadsheets/d/15mnrkl4Rc5dsFX8VAGOeuPPfCQTPHyOWV1SVwkXIqNQ/edit?ts=5a3acf6c#gid=312328589

**Comment by tevtonez** [comment]
`Pop-up of Biz Detail saved with information` and `Access Biz Profile with none-blank biz detail form` from the spec are implemented in 94be6ee (pr #988 )

For `Pop-up of Biz Detail form clicked outside of pop-up  w/out saving` JS is probably the best solution.

**Comment by tevtonez** [comment]
@MaxTattenbach 3 of 4 features from spec are completed.
I suggest to use JS to implement 'Pop-up of Biz Detail form clicked outside of pop-up  w/out saving' functionality. I believe Danny could take care of it.

**Comment by dannypernik** [comment]
@tevtonez @nickolashe prevent click outside of popup added to `kostya_profile_additions` branch

**Comment by MaxTattenbach** [comment]
@tevtonez everything is looking good here. 

Could we add the same feature in which pop-up also appears if blank in /biz-admin/ .  Note that currently pop-up only appears in /profile/  if the user is associated with biz. 

This should be a quick fix.  I'll add additional use case in the excel sheet.

**Comment by dannypernik** [comment]
@MaxTattenbach what do you think of only displaying this on biz-admin? It may be annoying to see it on both profile and biz-admin if user does not want to add details.

**Comment by tevtonez** [comment]
as per discussion wit Max: I removed the label and implemented the popup on biz-admin

**Comment by nickolashe** [comment]
@tevtonez where is this change residing?

**Comment by nickolashe** [comment]
i think i found it - i wonder why it was not linked to this issue by github

**Comment by tevtonez** [comment]
my bad, @nickolashe , I didn't add # of the story to the commit message

**Comment by MaxTattenbach** [comment]
@tevtonez this is looking good and desired functionality is achieved.
